export type CuratedSpot = {
  name: string;
  name_en?: string;
  type: "visit" | "tour" | "meal" | "event" | "free" | "transport";
  category: "landmark" | "viewpoint" | "beach" | "hiking" | "street-art" | "stadium" | "museum" | "park" | "nightlife" | "food";
  description: string;
  viral_trend?: string;
  address: string;
  lat: number;
  lng: number;
  search_query: string;
  emoji: string;
};

export const CURATED_SPOTS_SP: CuratedSpot[] = [
  {
    name: "Beco do Batman",
    name_en: "Batman's Alley",
    type: "free",
    category: "street-art",
    description:
      "Callejón emblemático de Vila Madalena repleto de murales y graffitis en constante cambio. Punto de peregrinación para amantes del arte urbano y uno de los spots más instagramables de São Paulo.",
    viral_trend: "Murales cambiantes + fotos con arte urbano",
    address: "R. Gonçalo Afonso, 157 - Vila Madalena, São Paulo - SP",
    lat: -23.5544,
    lng: -46.6906,
    search_query: "Beco do Batman Vila Madalena São Paulo",
    emoji: "🎨",
  },
  {
    name: "MASP - Museu de Arte de São Paulo",
    name_en: "São Paulo Museum of Art",
    type: "visit",
    category: "museum",
    description:
      "Icono arquitectónico en la Avenida Paulista con la colección de arte europeo más importante del hemisferio sur. Su estructura suspendida deja un vacío libre debajo, plaza muy fotografiada.",
    viral_trend: "Foto bajo el vano libre del edificio + cristales suspendidos",
    address: "Av. Paulista, 1578 - Bela Vista, São Paulo - SP",
    lat: -23.5614,
    lng: -46.6565,
    search_query: "MASP Museu de Arte São Paulo Avenida Paulista",
    emoji: "🖼️",
  },
  {
    name: "Avenida Paulista",
    name_en: "Paulista Avenue",
    type: "free",
    category: "landmark",
    description:
      "El principal eje financiero y cultural de São Paulo. Llena de museos, centros culturales, cafés y ciclovía. Los domingos se cierra al tráfico y se llena de artistas callejeros.",
    viral_trend: "Ciclovía dominical + skyline de rascacielos",
    address: "Av. Paulista - Bela Vista, São Paulo - SP",
    lat: -23.5613,
    lng: -46.6565,
    search_query: "Avenida Paulista São Paulo",
    emoji: "🏙️",
  },
  {
    name: "Parque Ibirapuera",
    name_en: "Ibirapuera Park",
    type: "free",
    category: "park",
    description:
      "El 'Central Park' paulistano: 158 hectáreas de lagos, museos (Niemeyer), pabellones y senderos. Ideal para correr, andar en patineta o hacer picnic. Uno de los parques urbanos más visitados de Latinoamérica.",
    viral_trend: "Lago con reflejos + arquitectura de Niemeyer",
    address: "Av. Pedro Álvares Cabral - Vila Mariana, São Paulo - SP",
    lat: -23.5874,
    lng: -46.6576,
    search_query: "Parque Ibirapuera São Paulo",
    emoji: "🌳",
  },
  {
    name: "Farol Santander",
    name_en: "Santander Lighthouse",
    type: "visit",
    category: "viewpoint",
    description:
      "Mirador en lo alto del Edifício Altino Arantes (Banespa) a 160 m. Vistas 360° de la ciudad, incluida la cúpula del Theatro Municipal. Acceso gratuito con reserva.",
    viral_trend: "Vista 360 de São Paulo desde el mirador",
    address: "R. João Brícola, 24 - Centro Histórico, São Paulo - SP",
    lat: -23.5473,
    lng: -46.6373,
    search_query: "Farol Santander Banespa mirador São Paulo",
    emoji: "🗼",
  },
  {
    name: "Terraço Itália",
    name_en: "Terraço Itália",
    type: "visit",
    category: "viewpoint",
    description:
      "Restaurante y mirador en el piso 45 del Edifício Itália, a 168 m. Una de las mejores vistas panorámicas del centro de São Paulo, especialmente al atardecer.",
    viral_trend: "Atardecer panorámico desde el piso 45",
    address: "Av. Ipiranga, 344 - 45º andar - República, São Paulo - SP",
    lat: -23.5449,
    lng: -46.6477,
    search_query: "Terraço Itália mirador Edifício Itália São Paulo",
    emoji: "🌆",
  },
  {
    name: "Edifício Copan",
    name_en: "Copan Building",
    type: "free",
    category: "landmark",
    description:
      "Rascacielos ondulado diseñado por Oscar Niemeyer en el centro histórico, con 1.160 apartamentos y su icónica fachada curva. Símbolo modernista de la ciudad.",
    viral_trend: "Fachada ondulada de Niemeyer desde la calle",
    address: "Av. São Luís, 23 - República, São Paulo - SP",
    lat: -23.5466,
    lng: -46.6428,
    search_query: "Edifício Copan Niemeyer São Paulo",
    emoji: "🏢",
  },
  {
    name: "Theatro Municipal de São Paulo",
    name_en: "São Paulo Municipal Theatre",
    type: "visit",
    category: "landmark",
    description:
      "Teatro lírico inaugurado en 1911 con inspiración en la Ópera de París. Interior lujoso, escalinatas de mármol y cúpula de vidrio. Escenario de la Semana de Arte Moderna de 1922.",
    viral_trend: "Escaleras de mármol + cúpula de vidrio",
    address: "Praça Ramos de Azevedo, s/n - República, São Paulo - SP",
    lat: -23.5452,
    lng: -46.6393,
    search_query: "Theatro Municipal São Paulo",
    emoji: "🎭",
  },
  {
    name: "Mercado Municipal de São Paulo",
    name_en: "Municipal Market of São Paulo",
    type: "meal",
    category: "food",
    description:
      "Mercado histórico con vitrales y arquitectura de inspiración europea. Famoso por el sándwich de mortadela y los pasteis de bacalao. Paraíso gastronómico en el centro.",
    viral_trend: "Sándwich de mortadela gigante + vitrales",
    address: "R. da Cantareira, 306 - Centro Histórico, São Paulo - SP",
    lat: -23.5418,
    lng: -46.6294,
    search_query: "Mercado Municipal São Paulo mortadela",
    emoji: "🥪",
  },
  {
    name: "Escadaria do Patápio",
    name_en: "Patápio Staircase",
    type: "free",
    category: "street-art",
    description:
      "Escalera colorida de Vila Madalena decorada con mosaicos y pinturas, conectando la Rua Harmonia con el Beco do Batman. Cada escalón es una obra de arte colectiva.",
    viral_trend: "Escaleras de mosaico colorido",
    address: "Escadaria do Patápio - Vila Madalena, São Paulo - SP",
    lat: -23.5538,
    lng: -46.6908,
    search_query: "Escadaria do Patápio Vila Madalena São Paulo",
    emoji: "🪜",
  },
  {
    name: "Anjo da Vila Madalena",
    name_en: "Angel of Vila Madalena",
    type: "free",
    category: "street-art",
    description:
      "Mural de un ángel de grandes alas pintado por Thiago Versonato en Vila Madalena. Las alas sirven de telón de fondo para fotos: el spot 'alas de ángel' más viral de São Paulo.",
    viral_trend: "Alas de ángel para fotos",
    address: "R. Gonçalo Afonso - Vila Madalena, São Paulo - SP",
    lat: -23.5543,
    lng: -46.6904,
    search_query: "Anjo da Vila Madalena mural alas São Paulo",
    emoji: "😇",
  },
  {
    name: "Japan House São Paulo",
    name_en: "Japan House São Paulo",
    type: "visit",
    category: "museum",
    description:
      "Centro cultural japonés en la Avenida Paulista con exposiciones itinerantes, gastronomía, diseño y tecnología. Una ventana a la cultura japonesa en el corazón de São Paulo.",
    viral_trend: "Exposiciones inmersivas + diseño japonés",
    address: "Av. Paulista, 52 - Bela Vista, São Paulo - SP",
    lat: -23.5626,
    lng: -46.6548,
    search_query: "Japan House São Paulo Avenida Paulista",
    emoji: "🇯🇵",
  },
  {
    name: "Catedral Metropolitana da Sé",
    name_en: "Sé Cathedral",
    type: "free",
    category: "landmark",
    description:
      "Catedral neogótica en el corazón histórico de São Paulo, con cripta y vitrales coloridos. Símbolo de la ciudad frente a la Praça da Sé, punto cero de sus carreteras.",
    viral_trend: "Vitrales góticos + plaza del marco cero",
    address: "Praça da Sé, s/n - Centro Histórico, São Paulo - SP",
    lat: -23.5532,
    lng: -46.6332,
    search_query: "Catedral da Sé São Paulo",
    emoji: "⛪",
  },
  {
    name: "Mirante Sesc Paulista",
    name_en: "Sesc Paulista Observatory",
    type: "visit",
    category: "viewpoint",
    description:
      "Mirador en el piso 26 del Sesc Paulista con vista abierta hacia la Avenida Paulista y el skyline. Acceso accesible con programación cultural y restaurante.",
    viral_trend: "Vista de la Avenida Paulista desde arriba",
    address: "Av. Paulista, 119 - Bela Vista, São Paulo - SP",
    lat: -23.5631,
    lng: -46.6541,
    search_query: "Mirante Sesc Paulista observatorio",
    emoji: "🔭",
  },
  {
    name: "Instituto Moreira Salles - São Paulo",
    name_en: "Moreira Salles Institute - São Paulo",
    type: "visit",
    category: "museum",
    description:
      "Centro cultural en la Avenida Paulista con fotografía, cine, literatura y música. Entrada gratuita, café y una de las bibliotecas más bonitas de la ciudad para fotografiar.",
    viral_trend: "Biblioteca y exposiciones de fotografía",
    address: "Av. Paulista, 2424 - Jardim Paulista, São Paulo - SP",
    lat: -23.5696,
    lng: -46.6679,
    search_query: "Instituto Moreira Salles IMS Paulista",
    emoji: "📚",
  },
  {
    name: "Pinacoteca de São Paulo",
    name_en: "São Paulo Art Gallery",
    type: "visit",
    category: "museum",
    description:
      "El museo de arte más antiguo de São Paulo (1905), en un edificio neoclásico reformado. Colección destacada de arte brasileño del siglo XIX y XX, con patio de vidrio muy fotogénico.",
    viral_trend: "Patio de vidrio + arte brasileño",
    address: "Praça da Luz, 2 - Bom Retiro, São Paulo - SP",
    lat: -23.534,
    lng: -46.6336,
    search_query: "Pinacoteca de São Paulo Praça da Luz",
    emoji: "🏛️",
  },
  {
    name: "Estação da Luz",
    name_en: "Luz Station",
    type: "free",
    category: "landmark",
    description:
      "Estación de tren de estilo victoriano inaugurada en 1901, con torre de reloj inspirada en la Big Ben. Sede del Museu da Língua Portuguesa y punto histórico del centro.",
    viral_trend: "Arquitectura victoriana + torre del reloj",
    address: "Praça da Luz, 1 - Bom Retiro, São Paulo - SP",
    lat: -23.5354,
    lng: -46.6333,
    search_query: "Estação da Luz São Paulo",
    emoji: "🚉",
  },
  {
    name: "Parque da Luz",
    name_en: "Luz Park",
    type: "free",
    category: "park",
    description:
      "Jardín histórico del siglo XIX frente a la Estação da Luz, con esculturas, fuentes y árboles centenarios. Espacio tranquilo y museo al aire libre en pleno centro.",
    viral_trend: "Esculturas + jardín histórico",
    address: "Praça da Luz, s/n - Bom Retiro, São Paulo - SP",
    lat: -23.5351,
    lng: -46.6341,
    search_query: "Parque da Luz São Paulo esculturas",
    emoji: "🌿",
  },
  {
    name: "Praça do Pôr do Sol",
    name_en: "Sunset Square",
    type: "free",
    category: "park",
    description:
      "Plaza elevada en Pinheiros con vista abierta al horizonte, uno de los mejores lugares de São Paulo para ver el atardecer. Ambiente joven con food trucks y música.",
    viral_trend: "Atardecer con vista al horizonte",
    address: "R. Des. Eliseu Guilherme, 200 - Pinheiros, São Paulo - SP",
    lat: -23.5679,
    lng: -46.6964,
    search_query: "Praça do Pôr do Sol Pinheiros São Paulo",
    emoji: "🌇",
  },
  {
    name: "Rua Augusta",
    name_en: "Augusta Street",
    type: "free",
    category: "nightlife",
    description:
      "Calle bohemia que conecta el centro con los Jardins, epicentro de la vida nocturna paulistana. Bares, clubes, tiendas alternativas y ambiente LGBTQIA+ vibrante hasta el amanecer.",
    viral_trend: "Nocturna + neón + ambiente bohemio",
    address: "R. Augusta - Consolação, São Paulo - SP",
    lat: -23.5576,
    lng: -46.6643,
    search_query: "Rua Augusta nightlife São Paulo",
    emoji: "🌃",
  },
];
