// Spots trending/instagramables curados de ciudades de Latinoamérica.
// Solo lugares icónicos que un grupo de amigos querría visitar y fotografiar.
// Las coordenadas son aproximadas y sirven para sesgar búsquedas en Google Places.

export type CuratedSpot = {
  name: string;
  name_en?: string;
  type: "visit" | "tour" | "meal" | "event" | "free" | "transport";
  category:
    | "landmark"
    | "viewpoint"
    | "beach"
    | "hiking"
    | "street-art"
    | "stadium"
    | "museum"
    | "park"
    | "nightlife"
    | "food";
  description: string;
  viral_trend?: string;
  address: string;
  lat: number;
  lng: number;
  search_query: string;
  emoji: string;
};

export const CURATED_SPOTS_BUENOS_AIRES: CuratedSpot[] = [
  {
    name: "Caminito (La Boca)",
    name_en: "Caminito (La Boca)",
    type: "free",
    category: "street-art",
    description:
      "Callejón museo al aire libre en el barrio de La Boca, famoso por sus casas de chapa pintadas de colores vibrantes y por ser el lugar donde nació el tango. Una de las postales más icónicas de Buenos Aires.",
    viral_trend: "Foto bailando tango en la calle colorida con los artistas callejeros",
    address: "Caminito, La Boca, Buenos Aires",
    lat: -34.6442,
    lng: -58.3719,
    search_query: "Caminito La Boca Buenos Aires",
    emoji: "🎨",
  },
  {
    name: "El Ateneo Grand Splendid",
    name_en: "El Ateneo Grand Splendid",
    type: "visit",
    category: "landmark",
    description:
      "Librería instalada en un antiguo teatro de 1919, considerada una de las más bellas del mundo. Conserva el escenario, las balconadas y la cúpula pintada, con estanterías donde antes estaban los butacas.",
    viral_trend: "Foto sentado en una butaca leyendo con el escenario de fondo",
    address: "Av. Santa Fe 1860, Recoleta, Buenos Aires",
    lat: -34.5953,
    lng: -58.4103,
    search_query: "El Ateneo Grand Splendid Buenos Aires",
    emoji: "📚",
  },
  {
    name: "Palacio Barolo",
    name_en: "Barolo Palace",
    type: "tour",
    category: "landmark",
    description:
      "Edificio neogótico de 1923 inspirado en la Divina Comedia de Dante. Su faro en la cima se enciende ocasionalmente y ofrece vistas panorámicas del Congreso y la ciudad.",
    viral_trend: "Foto nocturna con el faro del palacio iluminado",
    address: "Av. de Mayo 1370, Monserrat, Buenos Aires",
    lat: -34.6097,
    lng: -58.3925,
    search_query: "Palacio Barolo Buenos Aires",
    emoji: "🏛️",
  },
  {
    name: "Galerías Pacífico",
    name_en: "Galerías Pacífico",
    type: "visit",
    category: "landmark",
    description:
      "Centro comercial en un edificio histórico de 1889 con una cúpula pintada al fresco por grandes muralistas argentinos. El patio de comidas y los pasillos son una joya arquitectónica.",
    viral_trend: "Foto bajo la cúpula de frescos mirando hacia arriba",
    address: "Florida 753, San Nicolás, Buenos Aires",
    lat: -34.6033,
    lng: -58.3756,
    search_query: "Galerías Pacífico Buenos Aires",
    emoji: "🛍️",
  },
  {
    name: "Obelisco",
    name_en: "Obelisk",
    type: "free",
    category: "landmark",
    description:
      "El símbolo de Buenos Aires, un obelisco de 67 metros erigido en 1936 en el cruce de Corrientes y 9 de Julio, la avenida más ancha del mundo. Punto de reunión para celebraciones y protestas.",
    viral_trend: "Foto abrazando el Obelisco desde abajo con perspectiva",
    address: "Av. Corrientes y Av. 9 de Julio, Buenos Aires",
    lat: -34.6037,
    lng: -58.3817,
    search_query: "Obelisco Buenos Aires",
    emoji: "🗼",
  },
  {
    name: "Casa Rosada",
    name_en: "Pink House",
    type: "visit",
    category: "landmark",
    description:
      "Sede del gobierno argentino, famosa por su fachada rosada y por el balcón desde el que hablaba Evita Perón. Una de las postales más reconocibles de la Plaza de Mayo.",
    viral_trend: "Foto imitando a Evita en el balcón (desde la plaza)",
    address: "Balcarce 50, Monserrat, Buenos Aires",
    lat: -34.6081,
    lng: -58.3703,
    search_query: "Casa Rosada Buenos Aires",
    emoji: "🩷",
  },
  {
    name: "Plaza de Mayo",
    name_en: "May Square",
    type: "free",
    category: "landmark",
    description:
      "La plaza histórica más importante de Buenos Aires, rodeada por la Casa Rosada, la Catedral y el Cabildo. Escenario de los grandes momentos políticos del país.",
    viral_trend: "Foto panorámica de la plaza con la Pirámide de Mayo y la Casa Rosada",
    address: "Plaza de Mayo, Monserrat, Buenos Aires",
    lat: -34.6086,
    lng: -58.3728,
    search_query: "Plaza de Mayo Buenos Aires",
    emoji: "🏛️",
  },
  {
    name: "Cementerio de la Recoleta",
    name_en: "Recoleta Cemetery",
    type: "visit",
    category: "landmark",
    description:
      "Cementerio histórico con mausoleos de mármol labrado y callejones laberínticos. Aquí está la tumba de Evita Perón. Un museo al aire libre de arquitectura funeraria.",
    viral_trend: "Foto entre los mausoleos con la luz filtrándose entre las bóvedas",
    address: "Junín 1760, Recoleta, Buenos Aires",
    lat: -34.5886,
    lng: -58.4172,
    search_query: "Cementerio de la Recoleta Buenos Aires",
    emoji: "🕯️",
  },
  {
    name: "Teatro Colón",
    name_en: "Colón Theatre",
    type: "visit",
    category: "landmark",
    description:
      "Uno de los teatros de ópera más prestigiosos del mundo, con una acústica legendaria y una arquitectura neoclásica deslumbrante. La sala principal es una joya dorada.",
    viral_trend: "Foto en la sala principal con la lámpara central y los palcos dorados",
    address: "Cerrito 628, San Nicolás, Buenos Aires",
    lat: -34.6011,
    lng: -58.3831,
    search_query: "Teatro Colón Buenos Aires",
    emoji: "🎭",
  },
  {
    name: "Puerto Madero",
    name_en: "Puerto Madero",
    type: "free",
    category: "nightlife",
    description:
      "Antiguo puerto reconvertido en barrio moderno con rascacielos, restaurantes sobre los diques y el Puente de la Mujer de Santiago Calatrava. El waterfront más elegante de la ciudad.",
    viral_trend: "Foto en el Puente de la Mujer al atardecer con los rascacielos reflejados",
    address: "Puerto Madero, Buenos Aires",
    lat: -34.6106,
    lng: -58.3642,
    search_query: "Puerto Madero Buenos Aires",
    emoji: "🌆",
  },
  {
    name: "Puente de la Mujer",
    name_en: "Women's Bridge",
    type: "free",
    category: "landmark",
    description:
      "Puente giratorio peatonal diseñado por Santiago Calatrava que simula una pareja bailando tango. Se ha vuelto el ícono moderno de Puerto Madero.",
    viral_trend: "Foto en el puente con el atardecer y los edificios de fondo",
    address: "Puente de la Mujer, Puerto Madero, Buenos Aires",
    lat: -34.6094,
    lng: -58.3647,
    search_query: "Puente de la Mujer Buenos Aires",
    emoji: "🌉",
  },
  {
    name: "Plaza San Martín",
    name_en: "San Martín Square",
    type: "free",
    category: "park",
    description:
      "Plaza arbolada en Retiro con el monumento al General San Martín y vistas a la Torre de los Ingleses. Un oasis verde en el centro de la ciudad.",
    viral_trend: "Foto en la plaza con la Torre Monumental de fondo",
    address: "Plaza San Martín, Retiro, Buenos Aires",
    lat: -34.5914,
    lng: -58.3747,
    search_query: "Plaza San Martín Retiro Buenos Aires",
    emoji: "🌳",
  },
];

export const CURATED_SPOTS_CARTAGENA: CuratedSpot[] = [
  {
    name: "Callejón Angosto (Umbrella Street)",
    name_en: "Umbrella Street",
    type: "free",
    category: "street-art",
    description:
      "Callejón decorado con paraguas de colores suspendidos en Getsemaní. Se ha vuelto viral en Instagram como el spot más colorido de Cartagena.",
    viral_trend: "Foto bajo el túnel de paraguas de colores",
    address: "Callejón Angosto, Getsemaní, Cartagena",
    lat: 10.4214,
    lng: -75.5481,
    search_query: "Callejón Angosto Getsemaní Cartagena",
    emoji: "☂️",
  },
  {
    name: "Torre del Reloj",
    name_en: "Clock Tower",
    type: "free",
    category: "landmark",
    description:
      "La puerta principal de la ciudad amurallada y el símbolo de Cartagena. La torre del reloj de estilo neoclásico separa el centro histórico de Getsemaní.",
    viral_trend: "Foto de noche con la torre iluminada y los colores cálidos",
    address: "Plaza de los Coches, Centro, Cartagena",
    lat: 10.4231,
    lng: -75.5478,
    search_query: "Torre del Reloj Cartagena",
    emoji: "🕰️",
  },
  {
    name: "Las Bóvedas",
    name_en: "Las Bóvedas",
    type: "visit",
    category: "landmark",
    description:
      "Antiguas mazmorras coloniales en el extremo de las murallas, hoy convertidas en mercado de artesanías. Los arcos de piedra son una postal clásica.",
    viral_trend: "Foto bajo los arcos de piedra con las artesanías coloridas",
    address: "Las Bóvedas, Santa Catalina, Cartagena",
    lat: 10.4267,
    lng: -75.5519,
    search_query: "Las Bóvedas Cartagena",
    emoji: "🏛️",
  },
  {
    name: "Barrio San Diego",
    name_en: "San Diego Neighborhood",
    type: "free",
    category: "landmark",
    description:
      "Barrio colonial con calles empedradas, balcones cubiertos de buganvillas y plazas tranquilas. Una de las zonas más encantadoras dentro de la ciudad amurallada.",
    viral_trend: "Foto en una calle empedrada con buganvillas y balcones coloniales",
    address: "San Diego, Centro Histórico, Cartagena",
    lat: 10.4258,
    lng: -75.5506,
    search_query: "Barrio San Diego Cartagena",
    emoji: "🌺",
  },
  {
    name: "Castillo San Felipe de Barajas",
    name_en: "San Felipe de Barajas Castle",
    type: "visit",
    category: "landmark",
    description:
      "La fortaleza colonial más grande construida por los españoles en América. Sus túneles laberínticos y murallas ofrecen vistas panorámicas de la ciudad.",
    viral_trend: "Foto en los túneles oscuros o en la cima con la ciudad al fondo",
    address: "Calle 30, San Diego, Cartagena",
    lat: 10.4228,
    lng: -75.5403,
    search_query: "Castillo San Felipe de Barajas Cartagena",
    emoji: "🏰",
  },
  {
    name: "Convento de la Popa",
    name_en: "La Popa Convent",
    type: "visit",
    category: "viewpoint",
    description:
      "Convento agustino del siglo XVII en el punto más alto de Cartagena. Ofrece la mejor vista panorámica de la ciudad amurallada, el mar y la bahía.",
    viral_trend: "Foto panorámica de Cartagena desde el convento al atardecer",
    address: "Cerro de La Popa, Cartagena",
    lat: 10.4169,
    lng: -75.5328,
    search_query: "Convento de la Popa Cartagena",
    emoji: "⛪",
  },
  {
    name: "Playa de Bocagrande",
    name_en: "Bocagrande Beach",
    type: "free",
    category: "beach",
    description:
      "Playa urbana en el barrio de rascacielos de Bocagrande, con vista a la bahía y al skyline de Cartagena. Arena dorada y ambiente playero a minutos del centro.",
    viral_trend: "Foto en la playa con los rascacielos de Bocagrande de fondo",
    address: "Av. San Martín, Bocagrande, Cartagena",
    lat: 10.4014,
    lng: -75.5536,
    search_query: "Playa de Bocagrande Cartagena",
    emoji: "🏖️",
  },
  {
    name: "Getsemaní",
    name_en: "Getsemaní",
    type: "free",
    category: "nightlife",
    description:
      "Barrio bohemio fuera de las murallas, lleno de arte callejero, música y bares. La Plaza de la Trinidad es su corazón, donde se reúnen locales y viajeros de noche.",
    viral_trend: "Foto con los murales callejeros y la Plaza de la Trinidad de noche",
    address: "Getsemaní, Cartagena",
    lat: 10.4219,
    lng: -75.5481,
    search_query: "Getsemaní Cartagena",
    emoji: "🎺",
  },
  {
    name: "Las Murallas",
    name_en: "The Walls",
    type: "free",
    category: "landmark",
    description:
      "Las murallas coloniales que rodean el casco antiguo, de más de 11 km. Caminar por encima al atardecer con una copa de vino es una tradición cartagenera.",
    viral_trend: "Foto sentado en las murallas viendo el atardecer sobre el mar",
    address: "Murallas de Cartagena, Centro Histórico, Cartagena",
    lat: 10.4242,
    lng: -75.5508,
    search_query: "Murallas de Cartagena",
    emoji: "🌅",
  },
  {
    name: "Plaza Santo Domingo",
    name_en: "Santo Domingo Square",
    type: "free",
    category: "landmark",
    description:
      "Plaza colonial presidida por la Iglesia de Santo Domingo y la escultura 'Mujer Reclinada' de Botero. Llena de cafés y terrazas, es un punto de encuentro icónico.",
    viral_trend: "Foto con la escultura de Botero y la iglesia de fondo",
    address: "Plaza Santo Domingo, Centro, Cartagena",
    lat: 10.4244,
    lng: -75.5503,
    search_query: "Plaza Santo Domingo Cartagena",
    emoji: "🗿",
  },
  {
    name: "Plaza de la Trinidad",
    name_en: "Trinidad Square",
    type: "free",
    category: "nightlife",
    description:
      "La plaza más animada de Getsemaní, rodeada de bares y restaurantes. De noche se llena de música en vivo, artistas callejeros y ambiente festivo.",
    viral_trend: "Video de la plaza de noche con música y ambiente callejero",
    address: "Plaza de la Trinidad, Getsemaní, Cartagena",
    lat: 10.4214,
    lng: -75.5489,
    search_query: "Plaza de la Trinidad Getsemaní Cartagena",
    emoji: "🎶",
  },
];

export const CURATED_SPOTS_BOGOTA: CuratedSpot[] = [
  {
    name: "La Candelaria",
    name_en: "La Candelaria",
    type: "free",
    category: "landmark",
    description:
      "El barrio histórico y cultural de Bogotá, con calles empedradas, casas coloniales coloridas, murales y museos. El corazón fundacional de la ciudad.",
    viral_trend: "Foto en una calle empedrada con murales y casas coloniales",
    address: "La Candelaria, Bogotá",
    lat: 4.5981,
    lng: -74.0728,
    search_query: "La Candelaria Bogotá",
    emoji: "🏘️",
  },
  {
    name: "Cerro de Monserrate",
    name_en: "Monserrate Hill",
    type: "tour",
    category: "viewpoint",
    description:
      "Cerro de 3.152 m con una iglesia en la cima y la mejor vista panorámica de Bogotá. Se sube en teleférico, funicular o caminando por un sendero de 1.500 m de desnivel.",
    viral_trend: "Foto en la cima con Bogotá extendida a los pies al atardecer",
    address: "Cerro de Monserrate, Bogotá",
    lat: 4.6056,
    lng: -74.0575,
    search_query: "Cerro de Monserrate Bogotá",
    emoji: "⛪",
  },
  {
    name: "Plazoleta Chorro de Quevedo",
    name_en: "Chorro de Quevedo Square",
    type: "free",
    category: "landmark",
    description:
      "Pequeña plazoleta donde se fundó Bogotá en 1538. Ambiente bohemio, artistas callejeros y la famosa bebida local: el chicha en barro.",
    viral_trend: "Foto con un vaso de chicha en la plazoleta bohemio",
    address: "Calle 12C #2-82, La Candelaria, Bogotá",
    lat: 4.5969,
    lng: -74.0714,
    search_query: "Chorro de Quevedo Bogotá",
    emoji: "🍺",
  },
  {
    name: "Museo del Oro",
    name_en: "Gold Museum",
    type: "visit",
    category: "museum",
    description:
      "El museo más importante de Colombia, con más de 34.000 piezas de oro precolombino. La sala final de la exposición es una experiencia inmersiva de luz y oro.",
    viral_trend: "Foto en la sala dorada rodeado de piezas de oro iluminadas",
    address: "Calle 16 #5-41, La Candelaria, Bogotá",
    lat: 4.6020,
    lng: -74.0728,
    search_query: "Museo del Oro Bogotá",
    emoji: "🥇",
  },
  {
    name: "Plaza Bolívar",
    name_en: "Bolívar Square",
    type: "free",
    category: "landmark",
    description:
      "La plaza principal de Bogotá, rodeada por la Catedral, el Capitolio, el Palacio de Justicia y el Alcaldía. Monumento ecuestre a Bolívar en el centro.",
    viral_trend: "Foto panorámica de la plaza con la Catedral y el Capitolio",
    address: "Plaza de Bolívar, La Candelaria, Bogotá",
    lat: 4.5981,
    lng: -74.0728,
    search_query: "Plaza Bolívar Bogotá",
    emoji: "🏛️",
  },
  {
    name: "Usaquén",
    name_en: "Usaquén",
    type: "free",
    category: "food",
    description:
      "Barrio colonial anexado a Bogotá, con plazas encantadoras, restaurantes y un mercado de pulgas los domingos. Ambiente relajado y arquitectura de pueblo.",
    viral_trend: "Foto en el mercado dominical de Usaquén con artesanías",
    address: "Usaquén, Bogotá",
    lat: 4.7014,
    lng: -74.0392,
    search_query: "Usaquén Bogotá",
    emoji: "🛍️",
  },
  {
    name: "Parque Simón Bolívar",
    name_en: "Simón Bolívar Park",
    type: "free",
    category: "park",
    description:
      "El parque más grande de Bogotá, pulmón verde de la ciudad. Lago, jardines, ciclovías y escenario para conciertos masivos. Ideal para picnic y día al aire.",
    viral_trend: "Foto en bote en el lago o picnic en el césped",
    address: "Av. Calle 63, Bogotá",
    lat: 4.6583,
    lng: -74.0956,
    search_query: "Parque Simón Bolívar Bogotá",
    emoji: "🌳",
  },
  {
    name: "Jardín Botánico de Bogotá",
    name_en: "Bogotá Botanical Garden",
    type: "visit",
    category: "park",
    description:
      "Jardín botánico con invernaderos de cristal, bosque de niebla y colección de flora andina. El invernadero de palmas es uno de los más grandes del mundo.",
    viral_trend: "Foto dentro del invernadero de cristal con plantas tropicales",
    address: "Calle 63 #68-95, Bogotá",
    lat: 4.6683,
    lng: -74.1039,
    search_query: "Jardín Botánico Bogotá",
    emoji: "🌿",
  },
  {
    name: "Catedral de Sal de Zipaquirá",
    name_en: "Salt Cathedral of Zipaquirá",
    type: "visit",
    category: "landmark",
    description:
      "Catedral tallada dentro de una mina de sal a 200 m bajo tierra. Una de las maravillas arquitectónicas de Colombia, con iluminación dramática en las naves de sal.",
    viral_trend: "Foto en la nave principal con la cruz iluminada en la roca de sal",
    address: "Parque de la Sal, Zipaquirá, Cundinamarca",
    lat: 5.0219,
    lng: -74.0042,
    search_query: "Catedral de Sal Zipaquirá",
    emoji: "⛏️",
  },
];

export const CURATED_SPOTS_LIMA: CuratedSpot[] = [
  {
    name: "Barranco",
    name_en: "Barranco",
    type: "free",
    category: "nightlife",
    description:
      "El barrio bohemio de Lima, con casas republicanas, murales, bares y galerías de arte. El Puente de los Suspiros es su ícono romántico.",
    viral_trend: "Foto en el Puente de los Suspiros con la vista al mar",
    address: "Barranco, Lima",
    lat: -12.1467,
    lng: -77.0219,
    search_query: "Barranco Lima",
    emoji: "🎨",
  },
  {
    name: "Parque del Amor",
    name_en: "Love Park",
    type: "free",
    category: "viewpoint",
    description:
      "Parque en el malecón de Miraflores con mosaicos de Gaudí y la escultura 'El Beso'. Vistas al océano Pacífico y lugar favorito para ver el atardecer.",
    viral_trend: "Foto imitando el beso de la escultura con el océano de fondo",
    address: "Malecón Cisneros, Miraflores, Lima",
    lat: -12.1325,
    lng: -77.0306,
    search_query: "Parque del Amor Lima",
    emoji: "💋",
  },
  {
    name: "Circuito Mágico del Agua",
    name_en: "Magic Water Circuit",
    type: "event",
    category: "park",
    description:
      "Parque con 13 fuentes ornamentales que se iluminan de noche con show de luces y agua. La fuente principal tiene un espectáculo de proyecciones sincronizado con música.",
    viral_trend: "Video del show de luces y agua en la fuente principal",
    address: "Parque de la Reserva, Lima",
    lat: -12.1414,
    lng: -77.0283,
    search_query: "Circuito Mágico del Agua Lima",
    emoji: "⛲",
  },
  {
    name: "Plaza Mayor",
    name_en: "Main Square",
    type: "free",
    category: "landmark",
    description:
      "La plaza fundacional de Lima, rodeada por la Catedral, el Palacio de Gobierno y la Municipalidad. Patrimonio de la Humanidad y corazón del Centro Histórico.",
    viral_trend: "Foto panorámica con la Catedral y el Palacio de Gobierno",
    address: "Plaza Mayor, Centro Histórico, Lima",
    lat: -12.0464,
    lng: -77.0303,
    search_query: "Plaza Mayor Lima",
    emoji: "🏛️",
  },
  {
    name: "Malecón de Miraflores",
    name_en: "Miraflores Boardwalk",
    type: "free",
    category: "viewpoint",
    description:
      "Paseo peatonal sobre los acantilados de Miraflores con vistas al Pacífico. Parques, áreas de parapente y los mejores atardeceres de Lima.",
    viral_trend: "Foto con parapentistas volando sobre el acantilado al atardecer",
    address: "Malecón de Miraflores, Lima",
    lat: -12.1306,
    lng: -77.0311,
    search_query: "Malecón de Miraflores Lima",
    emoji: "🪂",
  },
  {
    name: "Huaca Pucllana",
    name_en: "Huaca Pucllana",
    type: "visit",
    category: "landmark",
    description:
      "Sitio arqueológico preinca de adobe en pleno corazón de Miraflores. Pirámide de 500 d.C. que contrasta con el moderno barrio que la rodea.",
    viral_trend: "Foto de la pirámide de adobe con los edificios modernos detrás",
    address: "Calle General Borgoño, Miraflores, Lima",
    lat: -12.1186,
    lng: -77.0342,
    search_query: "Huaca Pucllana Lima",
    emoji: "🏺",
  },
  {
    name: "Museo Larco",
    name_en: "Larco Museum",
    type: "visit",
    category: "museum",
    description:
      "Museo en una casona colonial del siglo XVIII con la mejor colección de cerámica precolombina del Perú. Famoso por su sala de arte erótico mochica.",
    viral_trend: "Foto en el jardín del museo con buganvillas y la casona colonial",
    address: "Av. Bolívar 1515, Pueblo Libre, Lima",
    lat: -12.0719,
    lng: -77.0703,
    search_query: "Museo Larco Lima",
    emoji: "🏺",
  },
  {
    name: "Parque Kennedy",
    name_en: "Kennedy Park",
    type: "free",
    category: "park",
    description:
      "El parque central de Miraflores, lleno de gatos que se han vuelto una atracción. Rodeado de cafés, ferias de arte y ambiente animado de día y noche.",
    viral_trend: "Foto con los gatos del parque que se han vuelto famosos",
    address: "Parque Kennedy, Miraflores, Lima",
    lat: -12.1214,
    lng: -77.0297,
    search_query: "Parque Kennedy Miraflores Lima",
    emoji: "🐱",
  },
  {
    name: "Puente de los Suspiros",
    name_en: "Bridge of Sighs",
    type: "free",
    category: "landmark",
    description:
      "Puente de madera en Barranco, rodeado de leyendas románticas. Se dice que quien cruza sin mirar el río y pide un deseo, este se cumple.",
    viral_trend: "Foto en el puente de noche con las luces y el ambiente bohemio",
    address: "Jirón de la Unión, Barranco, Lima",
    lat: -12.1464,
    lng: -77.0217,
    search_query: "Puente de los Suspiros Barranco Lima",
    emoji: "🌉",
  },
];

export const CURATED_SPOTS_SANTIAGO: CuratedSpot[] = [
  {
    name: "Cerro Santa Lucía",
    name_en: "Santa Lucía Hill",
    type: "free",
    category: "viewpoint",
    description:
      "Cerro histórico donde Pedro de Valdivia fundó Santiago en 1541. Hoy es un parque con terrazas, fuentes y miradores con vistas al centro y la cordillera.",
    viral_trend: "Foto en el mirador con la cordillera de los Andes de fondo",
    address: "Cerro Santa Lucía, Santiago",
    lat: -33.4389,
    lng: -70.6478,
    search_query: "Cerro Santa Lucía Santiago",
    emoji: "⛰️",
  },
  {
    name: "Templo Bahá'í",
    name_en: "Bahá'í Temple",
    type: "free",
    category: "landmark",
    description:
      "Templo bahá'í de Sudamérica, una obra arquitectónica de cristal translúcido que parece una flor. La luz que filtra crea un ambiente etéreo único.",
    viral_trend: "Foto del templo de cristal con la luz filtrándose al atardecer",
    address: "Av. Francisco Bilbao 7400, Las Condes, Santiago",
    lat: -33.3619,
    lng: -70.5189,
    search_query: "Templo Bahá'í Santiago Chile",
    emoji: "🪷",
  },
  {
    name: "Parque Bicentenario",
    name_en: "Bicentennial Park",
    type: "free",
    category: "park",
    description:
      "Parque urbano de 27 hectáreas en Vitacura con lagos, esculturas y áreas verdes. Uno de los pulmones más elegantes de Santiago con vista a la cordillera.",
    viral_trend: "Foto junto al lago con la cordillera de los Andes reflejada",
    address: "Parque Bicentenario, Vitacura, Santiago",
    lat: -33.4056,
    lng: -70.6056,
    search_query: "Parque Bicentenario Vitacura Santiago",
    emoji: "🌳",
  },
  {
    name: "Cerro San Cristóbal",
    name_en: "San Cristóbal Hill",
    type: "tour",
    category: "viewpoint",
    description:
      "El cerro más alto de Santiago con 880 m, coronado por una estatua de la Virgen. Se sube en funicular o teleférico y ofrece la mejor vista de la ciudad y la cordillera.",
    viral_trend: "Foto junto a la Virgen con toda Santiago y los Andes al fondo",
    address: "Cerro San Cristóbal, Santiago",
    lat: -33.4256,
    lng: -70.6367,
    search_query: "Cerro San Cristóbal Santiago",
    emoji: "🚠",
  },
  {
    name: "Plaza de Armas",
    name_en: "Arms Square",
    type: "free",
    category: "landmark",
    description:
      "La plaza principal de Santiago, fundacional, rodeada por la Catedral, el Correo y el Museo Histórico. Corazón del casco histórico de la capital.",
    viral_trend: "Foto panorámica de la plaza con la Catedral Metropolitana",
    address: "Plaza de Armas, Santiago Centro",
    lat: -33.4378,
    lng: -70.6506,
    search_query: "Plaza de Armas Santiago",
    emoji: "🏛️",
  },
  {
    name: "Palacio de La Moneda",
    name_en: "La Moneda Palace",
    type: "visit",
    category: "landmark",
    description:
      "Sede del gobierno chileno, palacio neoclásico del siglo XVIII. Testigo de la historia, incluyendo el bombardeo de 1973. Cambio de guardia cada dos días.",
    viral_trend: "Foto con el cambio de guardia en la Plaza de la Constitución",
    address: "Plaza de la Constitución, Santiago Centro",
    lat: -33.4436,
    lng: -70.6539,
    search_query: "Palacio de La Moneda Santiago",
    emoji: "🛡️",
  },
  {
    name: "Sky Costanera",
    name_en: "Sky Costanera",
    type: "visit",
    category: "viewpoint",
    description:
      "Mirador en el piso 61 de la Torre Costanera Center, el rascacielos más alto de Sudamérica. Vistas de 360° de Santiago y la cordillera a 300 m de altura.",
    viral_trend: "Foto panorámica de 360° con la cordillera y toda la ciudad",
    address: "Av. Andrés Bello 2425, Providencia, Santiago",
    lat: -33.4172,
    lng: -70.6097,
    search_query: "Sky Costanera Santiago",
    emoji: "🏙️",
  },
  {
    name: "Barrio Bellavista",
    name_en: "Bellavista Neighborhood",
    type: "free",
    category: "nightlife",
    description:
      "Barrio bohemio al pie del Cerro San Cristóbal, conocido por sus murales, bares, restaurantes y vida nocturna. La Chascona, casa de Neruda, está aquí.",
    viral_trend: "Foto con los murales callejeros y el ambiente bohemio de noche",
    address: "Bellavista, Providencia, Santiago",
    lat: -33.4336,
    lng: -70.6389,
    search_query: "Barrio Bellavista Santiago",
    emoji: "🎭",
  },
  {
    name: "La Chascona (Casa de Neruda)",
    name_en: "La Chascona (Neruda's House)",
    type: "visit",
    category: "museum",
    description:
      "Una de las tres casas del poeta Pablo Neruda en Chile, en Bellavista. Llena de objetos curiosos y con un diseño caprichoso que refleja la personalidad del Nobel.",
    viral_trend: "Foto en el jardín o junto a la entrada con la placa de Neruda",
    address: "Fernando Márquez de la Plata 0192, Bellavista, Santiago",
    lat: -33.4342,
    lng: -70.6386,
    search_query: "La Chascona Neruda Santiago",
    emoji: "✒️",
  },
];

export const CURATED_SPOTS_CUSCO: CuratedSpot[] = [
  {
    name: "Machu Picchu (Guardhouse Viewpoint)",
    name_en: "Machu Picchu (Guardhouse Viewpoint)",
    type: "tour",
    category: "viewpoint",
    description:
      "La vista clásica y más fotografiada de Machu Picchu, desde la caseta de guardia. La postal icónica con la ciudadela completa y el Huayna Picchu al fondo.",
    viral_trend: "Foto clásica de la postal de Machu Picchu desde la caseta de guardia",
    address: "Machu Picchu, Aguas Calientes, Cusco",
    lat: -13.1631,
    lng: -72.5450,
    search_query: "Machu Picchu Guardhouse viewpoint",
    emoji: "🏔️",
  },
  {
    name: "Machu Picchu Sun Gate (Inti Punku)",
    name_en: "Machu Picchu Sun Gate (Inti Punku)",
    type: "tour",
    category: "hiking",
    description:
      "La puerta por donde entraban los caminantes del Camino Inca. Caminata de 1 hora desde la ciudadela con vistas espectaculares de Machu Picchu desde lo alto.",
    viral_trend: "Foto en la puerta del sol con Machu Picchu al fondo",
    address: "Inti Punku, Machu Picchu, Cusco",
    lat: -13.1589,
    lng: -72.5356,
    search_query: "Inti Punku Sun Gate Machu Picchu",
    emoji: "☀️",
  },
  {
    name: "Plaza de Armas de Cusco",
    name_en: "Cusco Main Square",
    type: "free",
    category: "landmark",
    description:
      "El corazón de la capital inca, rodeada por la Catedral y la Iglesia de la Compañía. Arco de piedra, fuentes y el ambiente de la ciudad imperial a 3.400 m.",
    viral_trend: "Foto de noche con la Catedral iluminada y la plaza animada",
    address: "Plaza de Armas, Cusco",
    lat: -13.5164,
    lng: -71.9789,
    search_query: "Plaza de Armas Cusco",
    emoji: "🏛️",
  },
  {
    name: "Barrio San Blas",
    name_en: "San Blas Neighborhood",
    type: "free",
    category: "landmark",
    description:
      "El barrio de los artesanos en Cusco, con calles empinadas empedradas, talleres y galerías. El punto más alto del centro histórico con vistas a la ciudad.",
    viral_trend: "Foto en las calles empinadas de San Blas con vista a Cusco",
    address: "San Blas, Cusco",
    lat: -13.5136,
    lng: -71.9739,
    search_query: "Barrio San Blas Cusco",
    emoji: "🎨",
  },
  {
    name: "Sacsayhuamán",
    name_en: "Sacsayhuamán",
    type: "visit",
    category: "landmark",
    description:
      "Fortaleza inca con piedras ciclópeas de hasta 200 toneladas encajadas con precisión milimétrica. Sitio del Inti Raymi cada 24 de junio.",
    viral_trend: "Foto junto a las enormes piedras encajadas sin argamasa",
    address: "Sacsayhuamán, Cusco",
    lat: -13.5086,
    lng: -71.9706,
    search_query: "Sacsayhuamán Cusco",
    emoji: "🪨",
  },
  {
    name: "Rainbow Mountain (Vinicunca)",
    name_en: "Rainbow Mountain (Vinicunca)",
    type: "tour",
    category: "hiking",
    description:
      "Montaña a 5.200 m con franjas de colores minerales: rojo, ocre, turquesa y violeta. Una de las caminatas más espectaculares y virales del Perú.",
    viral_trend: "Foto en la cima con las franjas de colores de la montaña",
    address: "Vinicunca, Pitumarca, Cusco",
    lat: -13.8689,
    lng: -71.3039,
    search_query: "Vinicunca Rainbow Mountain Cusco",
    emoji: "🌈",
  },
  {
    name: "Sacred Valley (Valle Sagrado)",
    name_en: "Sacred Valley",
    type: "tour",
    category: "landmark",
    description:
      "El valle sagrado de los incas entre Cusco y Machu Picchu, con pueblos como Pisac y Ollantaytambo. Terrazas, ruinas y el río Urubamba con la cordillera de fondo.",
    viral_trend: "Foto en las terrazas de Ollantaytambo con el valle y montañas",
    address: "Valle Sagrado, Cusco",
    lat: -13.5756,
    lng: -72.0906,
    search_query: "Valle Sagrado de los Incas Cusco",
    emoji: "🌾",
  },
  {
    name: "Qorikancha",
    name_en: "Qorikancha (Temple of the Sun)",
    type: "visit",
    category: "museum",
    description:
      "El templo inca más importante, dedicado al dios Sol, recubierto de oro en su origen. Sobre él se construyó el convento de Santo Domingo, creando un contraste único.",
    viral_trend: "Foto de los muros incas perfectos con el convento colonial encima",
    address: "Plazoleta Santo Domingo, Cusco",
    lat: -13.5189,
    lng: -71.9756,
    search_query: "Qorikancha Cusco",
    emoji: "☀️",
  },
  {
    name: "Ollantaytambo",
    name_en: "Ollantaytambo",
    type: "tour",
    category: "landmark",
    description:
      "Fortaleza inca y pueblo viviente en el Valle Sagrado, con terrazas gigantescas y templo inacabado. Parada clave en el camino a Machu Picchu.",
    viral_trend: "Foto en lo alto de las terrazas con el valle y el río Urubamba",
    address: "Ollantaytambo, Valle Sagrado, Cusco",
    lat: -13.2586,
    lng: -72.2636,
    search_query: "Ollantaytambo Valle Sagrado Cusco",
    emoji: "🏛️",
  },
];
