import type { CuratedSpot } from "@/lib/photo-types";
export type { CuratedSpot };

// --- Salvador (Bahía) ---

export const CURATED_SPOTS_SALVADOR: CuratedSpot[] = [
  {
    name: "Pelourinho",
    name_en: "Pelourinho Historic Center",
    type: "visit",
    category: "landmark",
    description:
      "Centro histórico de Salvador, Patrimonio de la Humanidad por la UNESCO. Calles empedradas, iglesias coloniales coloridas y música en cada esquina.",
    viral_trend: "TikToks bailando en las escaleras coloridas del Pelô",
    address: "Pelourinho, Salvador - BA, 40026-010, Brasil",
    lat: -12.9714,
    lng: -38.5118,
    search_query: "Pelourinho Salvador Bahía Brasil",
    emoji: "🏛️",
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana temprano (8-10h) o atardecer dorado",
    photo_concepts: [
      {
        title: "Escaleras coloridas del Pelô",
        pose: "Sentada en el tercer escalón, una pierna extendida, mirando hacia arriba con sonrisa ligera",
        camera_angle: "Cámara baja desde la base de las escaleras, ligeramente inclinada hacia arriba",
        best_time: "Mañana temprano (8-10h), luz lateral cálida",
        clothing: "Vestido blanco o amarillo que contraste con las paredes de colores",
        instagram_score: 9,
        camera_tip: "iPhone 1x o 2x zoom para comprimir el fondo de casas coloniales",
        format: "Vertical 4:5",
      },
      {
        title: "Calle empedrada con iglesia al fondo",
        pose: "Caminando hacia la cámara, mirando de vuelta al hombro, paso natural",
        camera_angle: "Cámara a la altura del pecho, plano americano, calle en perspectiva",
        best_time: "Atardecer dorado (17-18h)",
        clothing: "Ropa ligera de colores tierra, sombrero de paja opcional",
        instagram_score: 8,
        camera_tip: "Gran angular 24mm para capturar la pendiente de la calle",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Elevador Lacerda",
    name_en: "Lacerda Elevator",
    type: "transport",
    category: "viewpoint",
    description:
      "Ascensor público que conecta la Cidade Alta y la Cidade Baixa. Mirador con las mejores vistas de la Bahía de Todos-os-Santos.",
    viral_trend: "Foto del atardecer desde la cima con la bahía",
    address: "Praça Tomé de Sousa, Salvador - BA, 40020-000, Brasil",
    lat: -12.9723,
    lng: -38.5134,
    search_query: "Elevador Lacerda Salvador",
    emoji: "🏙️",
    instagram_score: 8,
    difficulty: 1,
    best_time: "Atardecer (17:30-18:30h)",
    photo_concepts: [
      {
        title: "Silueta sobre la Bahía de Todos-os-Santos",
        pose: "De pie en la baranda del mirador, de espaldas, brazos abiertos",
        camera_angle: "Cámara baja desde atrás, contraluz con el sol poniéndose",
        best_time: "Atardecer (17:30-18:30h), blue hour justo después",
        clothing: "Ropa oscura para silueta nítida, chaqueta ligera",
        instagram_score: 8,
        camera_tip: "Exponer para el cielo, HDR si hay nubes",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Farol da Barra",
    name_en: "Barra Lighthouse",
    type: "visit",
    category: "viewpoint",
    description:
      "Faro histórico en el Fuerte de Santo Antônio da Barra, el más antiguo de Brasil. Punto icónico para ver el atardecer en Salvador.",
    viral_trend: "Videos del atardecer con gente aplaudiendo al sol",
    address: "Largo do Farol da Barra, Salvador - BA, 40140-650, Brasil",
    lat: -13.0047,
    lng: -38.5278,
    search_query: "Farol da Barra Salvador",
    emoji: "🌅",
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer (17:30-18:15h)",
    photo_concepts: [
      {
        title: "Aplauso al sol en el Farol",
        pose: "De pie frente al faro, manos aplaudiendo sobre la cabeza, silueta contra el sol",
        camera_angle: "Cámara baja, contraluz total, sol entre las manos",
        best_time: "Atardecer exacto (17:45-18:15h)",
        clothing: "Ropa ligera de colores vivos, vestido fluido",
        instagram_score: 9,
        camera_tip: "Modo retrato para mantener el faro enfocado, exponer para el cielo",
        format: "Vertical 4:5",
      },
      {
        title: "Faro con cielo dorado",
        pose: "Apoyada en la pared del fuerte, mirando al horizonte",
        camera_angle: "Plano americano lateral, faro como elemento de fondo a la derecha",
        best_time: "Blue hour (18:15-18:45h)",
        clothing: "Vestido blanco o claro que resalte contra el cielo",
        instagram_score: 8,
        camera_tip: "Trípode ligero para exposición larga del mar",
        format: "Horizontal",
      },
    ],
  },
  {
    name: "Farol de Itapuã",
    name_en: "Itapuã Lighthouse",
    type: "free",
    category: "viewpoint",
    description:
      "Faro pintoresco en la playa de Itapuã, inmortalizado por la canción de Dorival Caymmi. Ambiente tranquilo lejos del centro.",
    address: "Itapuã, Salvador - BA, 41610-010, Brasil",
    lat: -12.9556,
    lng: -38.3564,
    search_query: "Farol de Itapuã Salvador",
    emoji: "🗼",
    instagram_score: 7,
    difficulty: 2,
    best_time: "Mañana (7-10h) o atardecer",
    photo_concepts: [
      {
        title: "Faro solitario en la playa",
        pose: "Sentada en la arena con el faro al fondo, piernas cruzadas, mirando al mar",
        camera_angle: "Cámara baja en la arena, faro centrado al fondo",
        best_time: "Mañana (7-10h) luz suave",
        clothing: "Traje de baño con pareo, colores pasteles",
        instagram_score: 7,
        camera_tip: "Gran angular para incluir el faro completo",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Igreja do Bonfim",
    name_en: "Church of Bonfim",
    type: "visit",
    category: "landmark",
    description:
      "Iglesia famosa por las fitas do Bonfim, cintas que se atan con tres nudos para pedir un deseo. Símbolo religioso de Salvador.",
    viral_trend: "Atar la fita do Bonfim y pedir un deseo en video",
    address: "Largo do Bonfim, Salvador - BA, 40415-000, Brasil",
    lat: -12.9700,
    lng: -38.4922,
    search_query: "Igreja do Bonfim Salvador",
    emoji: "⛪",
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana (9-11h) para evitar multitudes",
    photo_concepts: [
      {
        title: "Atando la fita do Bonfim",
        pose: "Manos atando la cinta en la reja, ojos cerrados, expresión de deseo",
        camera_angle: "Primer plano de las manos, fondo desenfocado de la reja con otras fitas",
        best_time: "Mañana (9-11h) luz natural suave",
        clothing: "Ropa blanca o clara, tonos espirituales",
        instagram_score: 8,
        camera_tip: "Modo retrato o 2x zoom para aislar las manos",
        format: "Cuadrada",
      },
      {
        title: "Fachada con fitas al viento",
        pose: "De pie frente a la iglesia, sosteniendo una fita al viento",
        camera_angle: "Plano entero frontal, iglesia simétrica al fondo",
        best_time: "Mañana (9-11h)",
        clothing: "Vestido blanco o estampado floral",
        instagram_score: 7,
        camera_tip: "Esperar ráfaga de viento para mover las fitas",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Solar do Unhão / MAM",
    name_en: "Solar do Unhão / Museum of Modern Art",
    type: "visit",
    category: "museum",
    description:
      "Centro cultural y museo de arte moderno en un edificio colonial restaurado frente al mar. Atardeceres espectaculares en el muelle.",
    viral_trend: "Fotos en el muelle del MAM al atardecer",
    address: "Av. do Contorno, Salvador - BA, 40070-020, Brasil",
    lat: -12.9650,
    lng: -38.5100,
    search_query: "Solar do Unhão MAM Salvador",
    emoji: "🎨",
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer (17:30-18:30h)",
    photo_concepts: [
      {
        title: "Muelle del MAM al atardecer",
        pose: "Sentada al borde del muelle de madera, piernas colgando, mirando al mar",
        camera_angle: "Cámara baja desde el muelle, plano americano de perfil",
        best_time: "Atardecer dorado (17:30-18:15h)",
        clothing: "Vestido fluido de colores cálidos, naranja o rojo",
        instagram_score: 9,
        camera_tip: "HDR para equilibrar el cielo y el muelle",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Mercado Modelo",
    name_en: "Modelo Market",
    type: "visit",
    category: "food",
    description:
      "Mercado artesanal en un edificio histórico junto al Elevador Lacerda. Souvenirs, artesanía y comida típica bahiana.",
    address: "Praça Visconde de Cayrú, Salvador - BA, 40015-160, Brasil",
    lat: -12.9733,
    lng: -38.5133,
    search_query: "Mercado Modelo Salvador",
    emoji: "🛍️",
    instagram_score: 6,
    difficulty: 1,
    best_time: "Mañana (10-12h) menos concurrido",
    photo_concepts: [
      {
        title: "Artesanía bahiana en el mercado",
        pose: "Sosteniendo una pieza de cerámica o berimbau, sonriendo al vendedor",
        camera_angle: "Plano medio, fondo de puestos coloridos desenfocado",
        best_time: "Mañana (10-12h)",
        clothing: "Ropa casual de viaje, colores que no compitan con la artesanía",
        instagram_score: 6,
        camera_tip: "Modo retrato para separar el sujeto del fondo del mercado",
        format: "Cuadrada",
      },
    ],
  },
  {
    name: "Igreja de São Francisco",
    name_en: "Church of São Francisco",
    type: "visit",
    category: "landmark",
    description:
      "Iglesia barroca con interior totalmente revestido en oro. Considerada una de las más ricas y ornamentadas de Brasil.",
    address: "Rua da Ordem Terceira de São Francisco, Salvador - BA, 40026-010, Brasil",
    lat: -12.9728,
    lng: -38.5119,
    search_query: "Igreja de São Francisco Salvador",
    emoji: "✨",
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana (9-12h) luz natural entra por vitrales",
    photo_concepts: [
      {
        title: "Oro barroco de São Francisco",
        pose: "De pie en la nave central, mirando hacia el altar, silueta pequeña",
        camera_angle: "Cámara baja, simetría central, altar dorado dominando el encuadre",
        best_time: "Mañana (9-12h) luz natural desde vitrales",
        clothing: "Ropa modesta (iglesia), tonos oscuros para que el oro resalte",
        instagram_score: 8,
        camera_tip: "No usar flash (prohibido), ISO alto y manos firmes",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Largo do Carmo",
    name_en: "Largo do Carmo Square",
    type: "free",
    category: "landmark",
    description:
      "Plaza arbolada en el Pelourinho con la Iglesia do Carmo y el convento carmelita. Lugar tranquilo para descansar y observar.",
    address: "Largo do Carmo, Salvador - BA, 40026-010, Brasil",
    lat: -12.9710,
    lng: -38.5120,
    search_query: "Largo do Carmo Salvador",
    emoji: "🌳",
    instagram_score: 6,
    difficulty: 1,
    best_time: "Tarde (15-17h) sombra de los árboles",
    photo_concepts: [
      {
        title: "Sombra del Largo do Carmo",
        pose: "Sentada en un banco bajo la sombra de un árbol, libro o café en mano",
        camera_angle: "Plano medio lateral, luz filtrada por las hojas",
        best_time: "Tarde (15-17h) sombra dappled",
        clothing: "Ropa casual fresca, tonos verdes o tierra",
        instagram_score: 6,
        camera_tip: "Exponer para las zonas iluminadas, dejar sombras profundas",
        format: "Cuadrada",
      },
    ],
  },
  {
    name: "Praça da Sé",
    name_en: "Praça da Sé Square",
    type: "free",
    category: "landmark",
    description:
      "Plaza con vista panorámica de la Cidade Baixa y el Elevador Lacerda. Ruinas de la antigua Sé y ambiente histórico.",
    address: "Praça da Sé, Salvador - BA, 40020-000, Brasil",
    lat: -12.9720,
    lng: -38.5130,
    search_query: "Praça da Sé Salvador",
    emoji: "📸",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Mañana (8-10h) o atardecer",
    photo_concepts: [
      {
        title: "Vista de la Cidade Baixa desde Praça da Sé",
        pose: "Apoyada en la baranda, de espaldas, mirando hacia la bahía",
        camera_angle: "Cámara al hombro del fotógrafo, plano americano de espaldas",
        best_time: "Atardecer (17-18h)",
        clothing: "Camisa ligera, colores que contrasten con el cielo",
        instagram_score: 7,
        camera_tip: "Gran angular para incluir la bahía completa",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Forte de São Marcelo",
    name_en: "Forte de São Marcelo",
    type: "tour",
    category: "landmark",
    description:
      "Fuerte circular sobre el mar, único en Brasil. Se accede en barco desde el puerto. Vistas de la ciudad desde el agua.",
    address: "Forte de São Marcelo, Salvador - BA, Brasil",
    lat: -12.9670,
    lng: -38.5150,
    search_query: "Forte de São Marcelo Salvador",
    emoji: "🏰",
    instagram_score: 7,
    difficulty: 3,
    best_time: "Mañana (9-11h) mar tranquilo para el barco",
    photo_concepts: [
      {
        title: "Fuerte circular desde el barco",
        pose: "De pie en la proa del barco, brazos extendidos, fuerte al fondo",
        camera_angle: "Cámara desde el barco, plano entero, fuerte centrado",
        best_time: "Mañana (9-11h) mar en calma",
        clothing: "Ropa cómoda de día, gafas de sol, sombrero",
        instagram_score: 7,
        camera_tip: "Action cam o teléfono con estabilización para el movimiento del barco",
        format: "Horizontal",
      },
    ],
  },
  {
    name: "Dique do Tororó",
    name_en: "Tororó Dike",
    type: "free",
    category: "park",
    description:
      "Lago urbano con estatuas de los orixás en el agua. Lugar de paseo, running y fotografía espiritual.",
    address: "Dique do Tororó, Salvador - BA, 40060-090, Brasil",
    lat: -12.9830,
    lng: -38.4840,
    search_query: "Dique do Tororó Salvador",
    emoji: "🛶",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Atardecer (17-18h) reflejos en el agua",
    photo_concepts: [
      {
        title: "Orixás en el agua al atardecer",
        pose: "Sentada en la orilla del lago, estatuas de orixás reflejadas al fondo",
        camera_angle: "Cámara baja, reflejo de las estatuas en el agua",
        best_time: "Atardecer (17-18h) colores cálidos en el agua",
        clothing: "Ropa blanca o blanca-roja (colores de los orixás)",
        instagram_score: 7,
        camera_tip: "Usar reflejos del agua como composición, esperar viento calmado",
        format: "Horizontal",
      },
    ],
  },
];

// --- Recife (Pernambuco) ---

export const CURATED_SPOTS_RECIFE: CuratedSpot[] = [
  {
    name: "Praça do Marco Zero",
    name_en: "Marco Zero Square",
    type: "free",
    category: "landmark",
    description:
      "Punto cero de Recife, en el Recife Antigo. Plaza colorida con el pórtico do Marco Zero y vista del río Capibaribe.",
    viral_trend: "Foto bajo el pórtico del Marco Zero",
    address: "Praça do Marco Zero, Recife - PE, 50030-000, Brasil",
    lat: -8.0631,
    lng: -34.8711,
    search_query: "Praça do Marco Zero Recife",
    emoji: "📍",
    instagram_score: 8,
    difficulty: 1,
    best_time: "Atardecer (17-18h) o noche con luces",
    photo_concepts: [
      {
        title: "Bajo el pórtico del Marco Zero",
        pose: "De pie bajo el pórtico, mirando a la cámara, sonrisa amplia",
        camera_angle: "Plano entero frontal, pórtico enmarcando al sujeto",
        best_time: "Atardecer (17-18h) o noche con iluminación",
        clothing: "Ropa colorida, vestido o camisa vibrante",
        instagram_score: 8,
        camera_tip: "Esperar a que no haya gente detrás, usar 2x zoom",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Praia de Boa Viagem",
    name_en: "Boa Viagem Beach",
    type: "free",
    category: "beach",
    description:
      "Playa urbana más famosa de Recife, con 7 km de arena, piscinas naturales en marea baja. Atención: presencia de tiburones, no bañarse lejos de la orilla.",
    viral_trend: "Videos de las piscinas naturales en marea baja",
    address: "Boa Viagem, Recife - PE, 51011-000, Brasil",
    lat: -8.1200,
    lng: -34.9000,
    search_query: "Praia de Boa Viagem Recife",
    emoji: "🏖️",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Mañana (6-9h) marea baja y menos gente",
    photo_concepts: [
      {
        title: "Paseo en la orilla al amanecer",
        pose: "Caminando por la orilla, pies descalzos, olas rozando los tobillos",
        camera_angle: "Cámara baja lateral, plano americano, reflejos en la arena mojada",
        best_time: "Amanecer (6-8h) luz dorada baja",
        clothing: "Traje de baño, pareo, sombrero de ala ancha",
        instagram_score: 7,
        camera_tip: "Cámara baja para capturar reflejos en la arena",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Instituto Ricardo Brennand",
    name_en: "Ricardo Brennand Institute",
    type: "visit",
    category: "museum",
    description:
      "Castillo medieval en medio de Recife con colección de armas, armaduras y arte. Jardines y arquitectura imponente.",
    address: "Alameda Antônio Brennand, Recife - PE, 52051-180, Brasil",
    lat: -8.0720,
    lng: -34.8850,
    search_query: "Instituto Ricardo Brennand Recife",
    emoji: "🏰",
    instagram_score: 9,
    difficulty: 2,
    best_time: "Mañana (9-11h) luz sobre la fachada",
    photo_concepts: [
      {
        title: "Castillo medieval en Recife",
        pose: "De pie frente al puente levadizo, mirando hacia arriba al castillo",
        camera_angle: "Cámara baja, plano entero, castillo dominando el encuadre",
        best_time: "Mañana (9-11h) luz frontal sobre la fachada",
        clothing: "Vestido elegante o camisa formal, tonos oscuros para contrastar",
        instagram_score: 9,
        camera_tip: "Gran angular 24mm para incluir el castillo completo",
        format: "Vertical 4:5",
      },
      {
        title: "Jardines del castillo",
        pose: "Caminando por el sendero del jardín, vuelta al hombro",
        camera_angle: "Plano americano, jardines simétricos al fondo",
        best_time: "Mañana (9-11h)",
        clothing: "Vestido floral, colores pasteles",
        instagram_score: 8,
        camera_tip: "2x zoom para comprimir el fondo del castillo",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Oficina Cerâmica Francisco Brennand",
    name_en: "Francisco Brennand Ceramic Workshop",
    type: "visit",
    category: "museum",
    description:
      "Espacio surrealista del artista Francisco Brennand, lleno de esculturas de cerámica en medio de la vegetación. Obra de arte total.",
    viral_trend: "Fotos entre las esculturas oníricas",
    address: "Propriedade Santos Cosme e Damião, Recife - PE, 52051-180, Brasil",
    lat: -8.0800,
    lng: -34.8900,
    search_query: "Oficina Cerâmica Francisco Brennand Recife",
    emoji: "🏺",
    instagram_score: 8,
    difficulty: 2,
    best_time: "Mañana (9-12h) luz filtrada por la vegetación",
    photo_concepts: [
      {
        title: "Entre las esculturas oníricas",
        pose: "Tocando una escultura de cerámica, mirada introspectiva",
        camera_angle: "Plano medio, esculturas circundando al sujeto",
        best_time: "Mañana (9-12h) luz dappled",
        clothing: "Vestido blanco o nude para fundirse con la cerámica",
        instagram_score: 8,
        camera_tip: "Modo retrato para separar el sujeto de las esculturas",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Cais do Porto",
    name_en: "Port Quay",
    type: "free",
    category: "landmark",
    description:
      "Muelles históricos del Recife Antigo, hoy zona de paseo con bares, museos y vista de los puentes de la ciudad.",
    address: "Cais do Porto, Recife - PE, 50030-000, Brasil",
    lat: -8.0700,
    lng: -34.8800,
    search_query: "Cais do Porto Recife Antigo",
    emoji: "⚓",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Atardecer (17-18h) con los puentes iluminados",
    photo_concepts: [
      {
        title: "Muelles del Recife Antigo",
        pose: "Apoyada en la baranda del muelle, mirando los puentes",
        camera_angle: "Plano americano de espaldas, puentes al fondo",
        best_time: "Atardecer (17-18h)",
        clothing: "Camisa ligera, gafas de sol",
        instagram_score: 7,
        camera_tip: "HDR para equilibrar cielo y muelle",
        format: "Horizontal",
      },
    ],
  },
  {
    name: "Sinagoga Kahal Zur Israel",
    name_en: "Kahal Zur Israel Synagogue",
    type: "visit",
    category: "museum",
    description:
      "Primera sinagoga de las Américas (1636), restaurada como museo de la historia judía en Recife. Recife Antigo.",
    address: "Rua do Bom Jesus, 197, Recife - PE, 50030-000, Brasil",
    lat: -8.0640,
    lng: -34.8710,
    search_query: "Sinagoga Kahal Zur Israel Recife",
    emoji: "🕍",
    instagram_score: 6,
    difficulty: 1,
    best_time: "Mañana (10-12h) visita guiada",
    photo_concepts: [
      {
        title: "Primera sinagoga de las Américas",
        pose: "De pie en la entrada, mirando el interior histórico",
        camera_angle: "Plano entero, simetría del arco de entrada",
        best_time: "Mañana (10-12h)",
        clothing: "Ropa modesta, tonos sobrios",
        instagram_score: 6,
        camera_tip: "Sin flash, ISO alto para interior oscuro",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Paço do Frevo",
    name_en: "Paço do Frevo",
    type: "visit",
    category: "museum",
    description:
      "Centro cultural dedicado al frevo, ritmo y danza símbolo de Pernambuco. Exposiciones, clases y presentaciones.",
    address: "Praça do Arsenal da Marinha, Recife - PE, 50030-000, Brasil",
    lat: -8.0640,
    lng: -34.8705,
    search_query: "Paço do Frevo Recife",
    emoji: "💃",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Tarde (15-17h) con presentaciones de frevo",
    photo_concepts: [
      {
        title: "Bailando frevo con sombrilla",
        pose: "Saltando con la sombrilla colorida de frevo en alto, pierna en el aire",
        camera_angle: "Cámara baja, congelar el salto con ráfaga",
        best_time: "Tarde (15-17h) durante presentaciones",
        clothing: "Ropa ligera colorida, idealmente roja o amarilla",
        instagram_score: 7,
        camera_tip: "Modo ráfaga para capturar el salto perfecto",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Praia de Boa Viagem (Piscinas Naturais)",
    name_en: "Boa Viagem Natural Pools",
    type: "tour",
    category: "beach",
    description:
      "Piscinas naturales que se forman en la playa de Boa Viagem durante la marea baja. Paseo en jangada desde la orilla.",
    address: "Boa Viagem, Recife - PE, 51011-000, Brasil",
    lat: -8.1180,
    lng: -34.8980,
    search_query: "Piscinas naturais Boa Viagem Recife",
    emoji: "🐠",
    instagram_score: 8,
    difficulty: 3,
    best_time: "Mañana (6-9h) marea baja confirmada",
    photo_concepts: [
      {
        title: "Jangada en las piscinas naturales",
        pose: "Sentada en la jangada, remando, sonriendo al sol",
        camera_angle: "Cámara desde otra jangada, plano americano",
        best_time: "Mañana (6-9h) marea baja, mar tranquilo",
        clothing: "Traje de baño, sombrero, ropa de neopreno opcional",
        instagram_score: 8,
        camera_tip: "Action cam o teléfono con fundo impermeable",
        format: "Horizontal",
      },
      {
        title: "Piscinas turquesa desde arriba",
        pose: "De pie en la piscina natural, agua turquesa cristalina",
        camera_angle: "Cámara alta (drone o brazo extendido), vista cenital",
        best_time: "Mañana (6-9h) sol alto para ver el color del agua",
        clothing: "Traje de baño brillante, amarillo o naranja",
        instagram_score: 9,
        camera_tip: "Drone si permitido, o palo selfie para vista cenital",
        format: "Cuadrada",
      },
    ],
  },
];

// --- Fortaleza (Ceará) ---

export const CURATED_SPOTS_FORTALEZA: CuratedSpot[] = [
  {
    name: "Avenida Beira-Mar",
    name_en: "Beira-Mar Avenue",
    type: "free",
    category: "park",
    description:
      "Paseo marítimo de 5 km junto a la playa de Iracema y Meireles. Ciclovía, quioscos de comida y carruajes turísticos.",
    viral_trend: "Videos patinando o corriendo al atardecer",
    address: "Av. Beira Mar, Fortaleza - CE, 60165-081, Brasil",
    lat: -3.7300,
    lng: -38.4900,
    search_query: "Avenida Beira-Mar Fortaleza",
    emoji: "🚲",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Atardecer (17:30-18:30h) brisa fresca",
    photo_concepts: [
      {
        title: "Patín sobre la Beira-Mar al atardecer",
        pose: "Patina o corre por la ciclovía, mirada al mar, movimiento natural",
        camera_angle: "Cámara en movimiento lateral, plano americano",
        best_time: "Atardecer (17:30-18:30h)",
        clothing: "Ropa deportiva, colores vivos, gafas de sol",
        instagram_score: 7,
        camera_tip: "Modo video a 60fps para cámara lenta",
        format: "Vertical 9:16",
      },
    ],
  },
  {
    name: "Praia do Futuro",
    name_en: "Futuro Beach",
    type: "free",
    category: "beach",
    description:
      "Playa más popular de Fortaleza, con barracas de playa (carpas) que sirven comida cearense. Mar abierto, oleaje fuerte.",
    viral_trend: "Comiendo peixada na barraca en TikTok",
    address: "Praia do Futuro, Fortaleza - CE, 60182-000, Brasil",
    lat: -3.7500,
    lng: -38.4700,
    search_query: "Praia do Futuro Fortaleza",
    emoji: "🌊",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Mañana (8-11h) antes del sol fuerte",
    photo_concepts: [
      {
        title: "Peixada na barraca",
        pose: "Sentada en la barraca de playa, plato de peixada en mano, primer bocado",
        camera_angle: "Primer plano, plato y rostro, fondo de mar desenfocado",
        best_time: "Mediodía (12-14h) comida fresca",
        clothing: "Ropa de playa, traje de baño con camisa",
        instagram_score: 7,
        camera_tip: "Modo retrato para separar el plato del fondo",
        format: "Cuadrada",
      },
    ],
  },
  {
    name: "Mercado Central",
    name_en: "Central Market",
    type: "visit",
    category: "food",
    description:
      "Mercado de artesanía de 5 pisos en el centro. Souvenirs, encajes de bilro, cerámica y comida regional.",
    address: "Rua Conde d'Eu, 199, Fortaleza - CE, 60060-120, Brasil",
    lat: -3.7170,
    lng: -38.5300,
    search_query: "Mercado Central Fortaleza",
    emoji: "🛍️",
    instagram_score: 6,
    difficulty: 1,
    best_time: "Mañana (10-12h) menos concurrido",
    photo_concepts: [
      {
        title: "Encajes de bilro en el Mercado",
        pose: "Observando a la artesana trabajar el encaje, manos en primer plano",
        camera_angle: "Sobre el hombro, primer plano de las manos y el encaje",
        best_time: "Mañana (10-12h)",
        clothing: "Ropa casual, colores neutros",
        instagram_score: 6,
        camera_tip: "Modo retrato para aislar las manos",
        format: "Cuadrada",
      },
    ],
  },
  {
    name: "Theatro José de Alencar",
    name_en: "José de Alencar Theater",
    type: "visit",
    category: "landmark",
    description:
      "Teatro histórico de 1910 con fachada art-nouveau y estructura metálica importada de Escocia. Jardines diseñados por Burle Marx.",
    address: "Rua Conde d'Eu, 221, Fortaleza - CE, 60060-120, Brasil",
    lat: -3.7180,
    lng: -38.5300,
    search_query: "Theatro José de Alencar Fortaleza",
    emoji: "🎭",
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana (9-11h) luz sobre la fachada art-nouveau",
    photo_concepts: [
      {
        title: "Fachada art-nouveau del teatro",
        pose: "De pie frente a la fachada, mirando hacia arriba, mano en la barbilla",
        camera_angle: "Cámara baja, plano entero, fachada simétrica",
        best_time: "Mañana (9-11h) luz frontal",
        clothing: "Vestido elegante o traje, tonos que no compitan con la fachada",
        instagram_score: 8,
        camera_tip: "Gran angular para incluir la fachada completa",
        format: "Vertical 4:5",
      },
      {
        title: "Jardines de Burle Marx",
        pose: "Sentada en los jardines, azulejos portugueses al fondo",
        camera_angle: "Plano medio, azulejos como elemento decorativo",
        best_time: "Mañana (9-11h)",
        clothing: "Vestido estampado, colores que combinen con los azulejos",
        instagram_score: 7,
        camera_tip: "2x zoom para comprimir el fondo de azulejos",
        format: "Cuadrada",
      },
    ],
  },
  {
    name: "Catedral Metropolitana",
    name_en: "Metropolitan Cathedral",
    type: "visit",
    category: "landmark",
    description:
      "Catedral neogótica con vitrales franceses, la tercera más grande de Brasil. Stained glass impresionante al entrar.",
    address: "Rua Pedro I, 46, Fortaleza - CE, 60060-050, Brasil",
    lat: -3.7170,
    lng: -38.5310,
    search_query: "Catedral Metropolitana Fortaleza",
    emoji: "⛪",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Mañana (9-11h) luz entra por vitrales",
    photo_concepts: [
      {
        title: "Vitrales góticos de la Catedral",
        pose: "De pie bajo un vitral, mirando hacia arriba, luz de colores en el rostro",
        camera_angle: "Cámara baja, contrapicado, vitral dominando el encuadre",
        best_time: "Mañana (9-11h) luz natural máxima",
        clothing: "Ropa modesta, tonos claros para reflejar la luz de colores",
        instagram_score: 7,
        camera_tip: "ISO alto, sin flash, exponer para los vitrales",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Museu Cearense",
    name_en: "Ceará Museum",
    type: "visit",
    category: "museum",
    description:
      "Museo de historia y cultura cearense dentro del Fuerte de Nossa Senhora da Assunção. Piezas indígenas y coloniales.",
    address: "Forte de Nossa Senhora da Assunção, Fortaleza - CE, 60060-070, Brasil",
    lat: -3.7170,
    lng: -38.5310,
    search_query: "Museu Cearense Fortaleza",
    emoji: "🏛️",
    instagram_score: 6,
    difficulty: 2,
    best_time: "Mañana (10-12h) visita tranquila",
    photo_concepts: [
      {
        title: "Interior del Fuerte de Assunção",
        pose: "Caminando por el corredor del fuerte, luz natural lateral",
        camera_angle: "Plano americano, perspectiva del corredor",
        best_time: "Mañana (10-12h)",
        clothing: "Ropa casual fresca, tonos tierra",
        instagram_score: 6,
        camera_tip: "ISO alto para interior, manos firmes",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Forte de Nossa Senhora da Assunção",
    name_en: "Forte de Nossa Senhora da Assunção",
    type: "visit",
    category: "landmark",
    description:
      "Fuerte holandés-portugués del siglo XVII, origen de la ciudad de Fortaleza. Base militar activa con visitas guiadas.",
    address: "Praça do Forte, Fortaleza - CE, 60060-070, Brasil",
    lat: -3.7170,
    lng: -38.5310,
    search_query: "Forte de Nossa Senhora da Assunção Fortaleza",
    emoji: "🏰",
    instagram_score: 7,
    difficulty: 2,
    best_time: "Mañana (9-11h) antes del calor",
    photo_concepts: [
      {
        title: "Muros del fuerte colonial",
        pose: "Apoyada en el muro de piedra, mirando al mar",
        camera_angle: "Plano americano de perfil, muro de piedra al fondo",
        best_time: "Mañana (9-11h)",
        clothing: "Ropa casual, tonos neutros que combinen con la piedra",
        instagram_score: 7,
        camera_tip: "Modo retrato para separar el sujeto del muro",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Praia de Iracema",
    name_en: "Iracema Beach",
    type: "free",
    category: "beach",
    description:
      "Playa urbana bohemia con el puente dos Ingleses y la estatua de Iracema. Zona de bares y vida nocturna.",
    address: "Praia de Iracema, Fortaleza - CE, 60060-000, Brasil",
    lat: -3.7200,
    lng: -38.5100,
    search_query: "Praia de Iracema Fortaleza",
    emoji: "🏖️",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Atardecer (17:30-18:30h) o noche con luces",
    photo_concepts: [
      {
        title: "Puente dos Ingleses al atardecer",
        pose: "De pie en el puente metálico, mirando al horizonte, viento en el pelo",
        camera_angle: "Cámara baja, plano entero, puente en perspectiva",
        best_time: "Atardecer (17:30-18:30h)",
        clothing: "Vestido fluido, colores cálidos",
        instagram_score: 7,
        camera_tip: "HDR para el cielo y el puente metálico",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Centro Dragão do Mar",
    name_en: "Dragão do Mar Center of Art and Culture",
    type: "visit",
    category: "museum",
    description:
      "Complejo cultural con museos, cines, planetario y bares. Centro de la escena artística y nocturna de Fortaleza.",
    address: "Rua Dragão do Mar, 81, Fortaleza - CE, 60060-390, Brasil",
    lat: -3.7190,
    lng: -38.5400,
    search_query: "Centro Dragão do Mar Fortaleza",
    emoji: "🐉",
    instagram_score: 7,
    difficulty: 1,
    best_time: "Tarde-noche (17-22h) ambiente cultural",
    photo_concepts: [
      {
        title: "Arte urbano del Dragão do Mar",
        pose: "Frente a un mural o instalación, interacción con la obra",
        camera_angle: "Plano entero, mural como fondo dominante",
        best_time: "Tarde (17-19h) luz natural + iluminación del centro",
        clothing: "Ropa urbana, colores que contrasten con el arte",
        instagram_score: 7,
        camera_tip: "Gran angular para incluir el mural completo",
        format: "Vertical 4:5",
      },
    ],
  },
];

// --- Jericoacoara / Nordeste ---

export const CURATED_SPOTS_JERICOACOARA: CuratedSpot[] = [
  {
    name: "Duna do Pôr do Sol",
    name_en: "Sunset Dune",
    type: "free",
    category: "viewpoint",
    description:
      "Duna principal de Jericoacoara, punto de encuentro para ver el atardecer. Subida de 5 minutos, vista 360° del mar y las dunas.",
    viral_trend: "Videos del aplauso colectivo al sol esconderse",
    address: "Duna do Pôr do Sol, Jijoca de Jericoacoara - CE, Brasil",
    lat: -2.7900,
    lng: -41.6900,
    search_query: "Duna do Pôr do Sol Jericoacoara",
    emoji: "🌅",
    instagram_score: 10,
    difficulty: 2,
    best_time: "Atardecer (17:30-18:15h) exacto",
    photo_concepts: [
      {
        title: "Aplauso colectivo al sol",
        pose: "De pie en la cima de la duna, manos aplaudiendo sobre la cabeza, silueta",
        camera_angle: "Cámara baja, contraluz total, sol entre las manos",
        best_time: "Atardecer exacto (17:45-18:15h)",
        clothing: "Ropa ligera, vestido fluido que se mueva con el viento",
        instagram_score: 10,
        camera_tip: "Modo video a 60fps para cámara lenta del aplauso",
        format: "Vertical 9:16",
      },
      {
        title: "Silueta en la duna dorada",
        pose: "Sentada en la cresta de la duna, piernas extendidas, mirando al mar",
        camera_angle: "Cámara baja lateral, duna en primer plano, mar al fondo",
        best_time: "Atardecer (17:30-18:00h)",
        clothing: "Vestido blanco o claro para silueta nítida",
        instagram_score: 9,
        camera_tip: "Exponer para el cielo, HDR opcional",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Pedra Furada",
    name_en: "Pedra Furada",
    type: "tour",
    category: "landmark",
    description:
      "Arco de roca sobre el mar, símbolo de Jericoacoara. Caminata de 40 min por la playa en marea baja. Mejor en la mañana.",
    viral_trend: "Foto en el arco con el mar de fondo",
    address: "Pedra Furada, Jijoca de Jericoacoara - CE, Brasil",
    lat: -2.7800,
    lng: -41.7000,
    search_query: "Pedra Furada Jericoacoara",
    emoji: "🪨",
    instagram_score: 9,
    difficulty: 3,
    best_time: "Mañana (7-10h) marea baja y luz lateral",
    photo_concepts: [
      {
        title: "Arco de Pedra Furada",
        pose: "De pie frente al arco, enmarcada por la roca, mar al fondo",
        camera_angle: "Cámara baja, arco enmarcando al sujeto, mar visible",
        best_time: "Mañana (7-10h) marea baja, luz lateral",
        clothing: "Traje de baño, pareo, colores que contrasten con la roca",
        instagram_score: 9,
        camera_tip: "Gran angular para incluir el arco completo",
        format: "Vertical 4:5",
      },
      {
        title: "A través del arco",
        pose: "Caminando hacia el arco, vista de espaldas, mar al fondo",
        camera_angle: "Cámara detrás del arco, sujeto enmarcado por la abertura",
        best_time: "Mañana (7-10h)",
        clothing: "Vestido de playa, colores vivos",
        instagram_score: 8,
        camera_tip: "Esperar ola para dinamismo en el fondo",
        format: "Cuadrada",
      },
    ],
  },
  {
    name: "Lagoa do Paraíso",
    name_en: "Paradise Lagoon",
    type: "free",
    category: "beach",
    description:
      "Laguna de agua dulce cristalina con redes sobre el agua. El spot más fotografiado de Jeri. Hammocks y kioskos.",
    viral_trend: "Tumbado en la red sobre el agua turquesa",
    address: "Lagoa do Paraíso, Jijoca de Jericoacoara - CE, Brasil",
    lat: -2.8200,
    lng: -41.6800,
    search_query: "Lagoa do Paraíso Jericoacoara",
    emoji: "🛟",
    instagram_score: 10,
    difficulty: 2,
    best_time: "Mañana (8-11h) antes del sol fuerte",
    photo_concepts: [
      {
        title: "Red sobre el agua turquesa",
        pose: "Tumbada en la red sobre el agua, brazos relajados, mirada al cielo",
        camera_angle: "Cámara alta (drone o palo), vista cenital o 45°",
        best_time: "Mañana (8-11h) agua más cristalina",
        clothing: "Traje de baño, preferentemente blanco o amarillo",
        instagram_score: 10,
        camera_tip: "Drone si permitido, o palo selfie para vista cenital",
        format: "Vertical 4:5",
      },
      {
        title: "Brazo en el agua cristalina",
        pose: "Sentada en la orilla, mano tocando el agua, reflejo visible",
        camera_angle: "Cámara baja, primer plano de la mano y el agua",
        best_time: "Mañana (8-11h)",
        clothing: "Traje de baño, pulseras o anillos para detalle",
        instagram_score: 9,
        camera_tip: "Polarizador para reducir reflejos y ver el fondo",
        format: "Cuadrada",
      },
    ],
  },
  {
    name: "Lagoa Azul",
    name_en: "Blue Lagoon",
    type: "free",
    category: "beach",
    description:
      "Laguna de aguas azules rodeada de dunas y manglares. Más tranquila que Paraíso, ideal para nadar y remar.",
    address: "Lagoa Azul, Jijoca de Jericoacoara - CE, Brasil",
    lat: -2.8100,
    lng: -41.6700,
    search_query: "Lagoa Azul Jericoacoara",
    emoji: "💧",
    instagram_score: 8,
    difficulty: 2,
    best_time: "Mañana (7-10h) agua en calma",
    photo_concepts: [
      {
        title: "Remando en Lagoa Azul",
        pose: "De pie en una canoa o stand-up paddle, remando, dunas al fondo",
        camera_angle: "Cámara desde la orilla, plano entero, dunas como fondo",
        best_time: "Mañana (7-10h) agua en calma, viento mínimo",
        clothing: "Traje de baño, sombrero, gafas de sol",
        instagram_score: 8,
        camera_tip: "Polarizador para el agua y el cielo",
        format: "Horizontal",
      },
    ],
  },
  {
    name: "Praia de Jericoacoara",
    name_en: "Jericoacoara Beach",
    type: "free",
    category: "beach",
    description:
      "Playa principal del pueblo, arena firme ideal para kitesurf y windsurf. El pueblo es cerrado a vehículos, todo se camina.",
    address: "Praia de Jericoacoara, Jijoca de Jericoacoara - CE, Brasil",
    lat: -2.7900,
    lng: -41.6900,
    search_query: "Praia de Jericoacoara",
    emoji: "🏖️",
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana (7-10h) viento constante para kitesurf",
    photo_concepts: [
      {
        title: "Kitesurf en la playa de Jeri",
        pose: "Saltando con la cometa de kitesurf en el aire, pleno vuelo",
        camera_angle: "Cámara baja, congelar el salto, mar de fondo",
        best_time: "Mañana (7-10h) viento constante",
        clothing: "Traje de neopreno, ropa deportiva de kitesurf",
        instagram_score: 8,
        camera_tip: "Modo ráfaga a 60fps para congelar el salto",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Praia da Lagoinha (Ceará)",
    name_en: "Lagoinha Beach",
    type: "free",
    category: "beach",
    description:
      "Playa de arena roja entre acantilados, a 120 km de Fortaleza. Fondo de palmeras y dunas, paisaje de postal.",
    address: "Praia da Lagoinha, Paraipaba - CE, 62680-000, Brasil",
    lat: -2.8300,
    lng: -41.6900,
    search_query: "Praia da Lagoinha Ceará",
    emoji: "🌴",
    instagram_score: 8,
    difficulty: 3,
    best_time: "Mañana (7-10h) o atardecer dorado",
    photo_concepts: [
      {
        title: "Palmeras y dunas de Lagoinha",
        pose: "De pie entre las palmeras, mirando al mar, viento en el pelo",
        camera_angle: "Cámara baja, plano entero, palmeras enmarcando",
        best_time: "Mañana (7-10h) luz dorada lateral",
        clothing: "Vestido de playa, colores que contrasten con la arena roja",
        instagram_score: 8,
        camera_tip: "Gran angular para incluir palmeras y dunas",
        format: "Vertical 4:5",
      },
    ],
  },
  {
    name: "Canoa Quebrada",
    name_en: "Canoa Quebrada",
    type: "free",
    category: "beach",
    description:
      "Pueblo de pescadores con dunas coloradas y la famosa meia-lua (media luna) y estrella esculpida en el acantilado. Ambiente hippie-chic.",
    viral_trend: "Foto en el acantilado con la media luna y la estrella",
    address: "Canoa Quebrada, Aracati - CE, 62800-000, Brasil",
    lat: -4.5000,
    lng: -37.2500,
    search_query: "Canoa Quebrada Ceará",
    emoji: "🌙",
    instagram_score: 9,
    difficulty: 2,
    best_time: "Atardecer (17:30-18:30h) luz sobre el acantilado",
    photo_concepts: [
      {
        title: "Media luna y estrella en el acantilado",
        pose: "De pie junto a la meia-lua esculpida, mano tocando la estrella",
        camera_angle: "Cámara baja, plano entero, acantilado y mar al fondo",
        best_time: "Atardecer (17:30-18:30h)",
        clothing: "Ropa bohemia, colores vivos, accesorios hippie-chic",
        instagram_score: 9,
        camera_tip: "HDR para equilibrar el acantilado y el cielo",
        format: "Vertical 4:5",
      },
      {
        title: "Dunas coloradas de Canoa",
        pose: "Sentada en la duna colorada, piernas extendidas, mar al fondo",
        camera_angle: "Cámara baja lateral, duna en primer plano",
        best_time: "Atardecer (17:30-18:00h)",
        clothing: "Vestido blanco para contrastar con la arena roja",
        instagram_score: 8,
        camera_tip: "Polarizador para intensificar el color de la duna",
        format: "Horizontal",
      },
    ],
  },
  {
    name: "Praia do Forte (Bahía)",
    name_en: "Praia do Forte Beach",
    type: "free",
    category: "beach",
    description:
      "Pueblo costero al norte de Salvador con playas, piscinas naturales y el Projeto Tamar (tortugas marinas). Eco-reserva y resort.",
    address: "Praia do Forte, Mata de São João - BA, 48280-000, Brasil",
    lat: -12.5700,
    lng: -38.0000,
    search_query: "Praia do Forte Bahía",
    emoji: "🐢",
    instagram_score: 7,
    difficulty: 2,
    best_time: "Mañana (8-11h) visita al Projeto Tamar",
    photo_concepts: [
      {
        title: "Tortugas en el Projeto Tamar",
        pose: "Observando las tortugas en los tanques, expresión de asombro",
        camera_angle: "Sobre el hombro, tortuga en primer plano",
        best_time: "Mañana (8-11h)",
        clothing: "Ropa fresca de día, colores claros",
        instagram_score: 7,
        camera_tip: "Sin flash (asusta a las tortugas), ISO alto",
        format: "Cuadrada",
      },
    ],
  },
  {
    name: "Morro do Pai Inácio (Chapada Diamantina)",
    name_en: "Pai Inácio Hill",
    type: "tour",
    category: "viewpoint",
    description:
      "Mirador icónico de la Chapada Diamantina, subida corta y panorámica de 360°. Leyenda del Pai Inácio y vista de la meseta.",
    viral_trend: "Foto sentado en el borde con las montañas",
    address: "Morro do Pai Inácio, Palmeiras - BA, 46930-000, Brasil",
    lat: -12.4500,
    lng: -41.4700,
    search_query: "Morro do Pai Inácio Chapada Diamantina",
    emoji: "⛰️",
    instagram_score: 10,
    difficulty: 3,
    best_time: "Amanecer (5:30-7h) o atardecer (17-18h)",
    photo_concepts: [
      {
        title: "Borde del Pai Inácio con las montañas",
        pose: "Sentada en el borde del mirador, piernas colgando, mirada al horizonte",
        camera_angle: "Cámara baja detrás, plano americano, montañas al fondo",
        best_time: "Amanecer (5:30-7h) o atardecer (17-18h)",
        clothing: "Ropa de senderismo, chaqueta (hace frío al amanecer)",
        instagram_score: 10,
        camera_tip: "Gran angular para incluir el paisaje completo",
        format: "Vertical 4:5",
      },
      {
        title: "Panorámica 360° de la Chapada",
        pose: "De pie en la cima, brazos abiertos, vista panorámica",
        camera_angle: "Cámara baja, plano entero, horizonte nivelado",
        best_time: "Amanecer (5:30-7h) luz dorada",
        clothing: "Ropa de trekking, colores que contrasten con el paisaje",
        instagram_score: 9,
        camera_tip: "Modo panorámica del teléfono",
        format: "Horizontal",
      },
    ],
  },
  {
    name: "Lençóis Maranhenses",
    name_en: "Lençóis Maranhenses National Park",
    type: "tour",
    category: "viewpoint",
    description:
      "Parque nacional de dunas blancas y lagunas de agua dulce que se forman en la estación lluviosa. Paisaje único en el mundo, safari en 4x4.",
    viral_trend: "Videos zambulléndose en las lagunas entre dunas",
    address: "Parque Nacional dos Lençóis Maranhenses, Barreirinhas - MA, 65760-000, Brasil",
    lat: -2.5000,
    lng: -42.8000,
    search_query: "Lençóis Maranhenses Parque Nacional",
    emoji: "🏜️",
    instagram_score: 10,
    difficulty: 4,
    best_time: "Junio-septiembre, lagunas llenas. Mañana (6-10h)",
    photo_concepts: [
      {
        title: "Zambullida en la laguna entre dunas",
        pose: "Saltando a la laguna desde la duna, salpicadura congelada",
        camera_angle: "Cámara baja, congelar el salto, dunas blancas al fondo",
        best_time: "Mañana (6-10h) agua fresca, luz dorada",
        clothing: "Traje de baño, colores vivos que contrasten con la arena blanca",
        instagram_score: 10,
        camera_tip: "Modo ráfaga a 60fps para congelar la salpicadura",
        format: "Vertical 9:16",
      },
      {
        title: "Dunas blancas y laguna turquesa",
        pose: "Sentada en la orilla de la laguna, dunas blancas detrás",
        camera_angle: "Cámara alta (drone o duna elevada), vista cenital",
        best_time: "Mañana (7-10h) sol alto para ver el color del agua",
        clothing: "Traje de baño amarillo o rojo para máximo contraste",
        instagram_score: 10,
        camera_tip: "Drone ideal, o subir a una duna más alta",
        format: "Cuadrada",
      },
    ],
  },
];
