// Spots trending/instagramables curados de Río de Janeiro.
// Solo lugares icónicos que un grupo de amigos querría visitar y fotografiar.
// Las coordenadas son aproximadas y sirven para sesgar búsquedas en Google Places.

import type { CuratedSpot } from "@/lib/photo-types";
export type { CuratedSpot };

export const CURATED_SPOTS_RIO: CuratedSpot[] = [
  {
    name: "Cristo Redentor",
    name_en: "Christ the Redeemer",
    type: "visit",
    category: "landmark",
    description:
      "La estatua más icónica de Río y una de las 7 maravillas del mundo. Las vistas de la ciudad desde el mirador son espectaculares.",
    viral_trend: "Foto con los brazos abiertos imitando al Cristo",
    address: "Parque Nacional da Tijuca, Cosme Velho, Rio de Janeiro",
    lat: -22.9519,
    lng: -43.2105,
    search_query: "Cristo Redentor Rio de Janeiro",
    emoji: "✝️",
    photo_concepts: [
      {
        title: "Brazos abiertos imitando al Cristo",
        pose: "De pie, de espaldas al Cristo, brazos completamente abiertos imitando la pose de la estatua. Mirar hacia adelante, no a la cámara.",
        camera_angle: "Cámara baja a la altura del pecho, ligeramente hacia arriba para que el Cristo domine el encuadre.",
        best_time: "Mañana temprano (8-10am) para evitar multitudes y tener luz lateral.",
        clothing: "Camiseta blanca o de colores claros para contrastar con el cielo azul. Nada de patrones llamativos.",
        instagram_score: 10,
        camera_tip: "iPhone 1x o 0.5x gran angular para que el Cristo entre completo. Si hay gente, espera el hueco o usa 2x para recortar.",
        format: "Vertical 4:5",
      },
      {
        title: "Panorámica de Río desde el mirador",
        pose: "De pie en la baranda del mirador, apoyado en la barandilla, mirando hacia la ciudad. De perfil para que se vea el paisaje.",
        camera_angle: "Cámara a media altura, toma horizontal amplia capturando la bahía y las montañas.",
        best_time: "Mañana despejada para máxima visibilidad.",
        clothing: "Ropa casual, colores que contrasten con el verde de las montañas.",
        instagram_score: 9,
        camera_tip: "iPhone panorama o 0.5x. Drone prohibido, así que aprovecha la baranda como punto de apoyo.",
        format: "Horizontal 16:9",
      },
    ],
    instagram_score: 10,
    difficulty: 2,
    best_time: "Mañana temprano",
  },
  {
    name: "Copacabana Beach",
    name_en: "Copacabana Beach",
    type: "free",
    category: "beach",
    description:
      "La playa más famosa del mundo, con su icónico paseo de piedra portuguesa en forma de ondas. Punto de encuentro de cariocas y turistas.",
    viral_trend: "Foto tumbado en la arena con el Forte de Copacabana de fondo",
    address: "Av. Atlântica, Copacabana, Rio de Janeiro",
    lat: -22.9711,
    lng: -43.1822,
    search_query: "Copacabana Beach Rio de Janeiro",
    emoji: "🏖️",
    photo_concepts: [
      {
        title: "Tumbado en la arena con el fuerte de fondo",
        pose: "Acostado boca arriba en la arena, cabeza cerca de la cámara, Forte de Copacabana visible al fondo. Brazos relajados a los lados.",
        camera_angle: "Cámara muy baja, casi tocando la arena, apuntando hacia arriba para capturar el fuerte.",
        best_time: "Mañana (7-10am) cuando la playa está vacía y la luz es suave.",
        clothing: "Traje de baño, sin camisa. Gafas de sol opcionales para un look más playero.",
        instagram_score: 9,
        camera_tip: "iPhone 0.5x gran angular para maximizar el fondo. Limpia el lente, la arena lo empaña todo.",
        format: "Vertical 4:5",
      },
      {
        title: "Caminando por el paseo de piedras",
        pose: "Caminando descalzo por el paseo de piedra portuguesa, mirando al mar. Un paso adelante natural.",
        camera_angle: "Cámara a media altura, ligeramente lateral, capturando el patrón de ondas del suelo.",
        best_time: "Atardecer para la luz dorada sobre las piedras.",
        clothing: "Ropa de playa ligera, hawaiana abierta o vestido de lino.",
        instagram_score: 8,
        camera_tip: "iPhone 1x. El patrón del suelo es el protagonista, así que no lo recortes.",
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana temprano",
  },
  {
    name: "Ipanema Beach",
    name_en: "Ipanema Beach",
    type: "free",
    category: "beach",
    description:
      "La playa que inspiró la canción 'Garota de Ipanema'. Sus montañas Dois Irmãos al fondo crean la postal perfecta.",
    viral_trend: "Foto en el Posto 9 con las montañas Dois Irmãos detrás",
    address: "Av. Vieira Souto, Ipanema, Rio de Janeiro",
    lat: -22.9836,
    lng: -43.2048,
    search_query: "Ipanema Beach Rio de Janeiro",
    emoji: "🌊",
    photo_concepts: [
      {
        title: "Posto 9 con Dois Irmãos al fondo",
        pose: "De pie en la arena, de espaldas a la cámara, mirando hacia las montañas Dois Irmãos. Postura relajada, una mano en la cintura.",
        camera_angle: "Cámara a media altura, ligeramente alejada para que las montañas dominen el encuadre.",
        best_time: "Mañana (7-9am) para luz lateral sobre las montañas y menos gente.",
        clothing: "Traje de baño, sin camisa. Colores neutros para que el paisaje domine.",
        instagram_score: 10,
        camera_tip: "iPhone 1x o 2x para comprimir las montañas. Si usas 0.5x las montañas se ven muy pequeñas.",
        format: "Vertical 4:5",
      },
      {
        title: "Corriendo por la orilla",
        pose: "Corriendo a paso ligero por la orilla, salpicando agua. Mirar hacia adelante, no a la cámara.",
        camera_angle: "Cámara baja, en movimiento paralelo si usas Action 4. Si es iPhone, estática desde la arena.",
        best_time: "Atardecer para la luz dorada y sombras largas.",
        clothing: "Ropa deportiva, camiseta técnica. Nada de algodón pesado.",
        instagram_score: 8,
        camera_tip: "Action 4 en modo burst a 30fps para congelar el salpicar. iPhone en modo Live Photo.",
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana temprano",
  },
  {
    name: "Maracanã Stadium",
    name_en: "Maracanã Stadium",
    type: "event",
    category: "stadium",
    description:
      "El templo del fútbol brasileño. Ver un partido aquí es una experiencia que eriza la piel, con el ritmo de las torcidas.",
    viral_trend: "Foto con la camiseta de Brasil en las gradas del Maracanã",
    address: "Av. Pres. Castelo Branco, Maracanã, Rio de Janeiro",
    lat: -22.9121,
    lng: -43.2302,
    search_query: "Maracanã Stadium Rio de Janeiro",
    emoji: "⚽",
    photo_concepts: [
      {
        title: "Camiseta de Brasil en las gradas",
        pose: "De pie en las gradas, camiseta de Brasil visible, brazos en alto celebrando. Expresión de euforia.",
        camera_angle: "Cámara a la altura del pecho, ligeramente hacia arriba para capturar el techo del estadio.",
        best_time: "Durante partido (noche) con las luces del estadio encendidas.",
        clothing: "Camiseta amarilla de Brasil. OBLIGATORIO. Sin camiseta no hay foto.",
        instagram_score: 9,
        camera_tip: "iPhone 1x. El modo retrato puede separarte del fondo del estadio, pero mejor en modo normal para capturar el ambiente.",
        format: "Vertical 4:5",
      },
      {
        title: "Selfie con la cancha",
        pose: "Selfie desde las gradas altas, cancha de fondo. Sonrisa amplia, camiseta visible.",
        camera_angle: "Selfie desde abajo, cancha visible detrás.",
        best_time: "Antes del partido cuando la cancha está despejada.",
        clothing: "Camiseta de Brasil, bufanda o gorra del equipo.",
        instagram_score: 8,
        camera_tip: "iPhone cámara frontal 0.5x para que entre la cancha. Cuidado con el contraste de luz.",
        format: "Cuadrada 1:1",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Noche (durante partido)",
  },
  {
    name: "Escadaria Selarón",
    name_en: "Selarón Steps",
    type: "free",
    category: "street-art",
    description:
      "Escalera de 215 peldaños cubiertos con azulejos de todo el mundo, obra del artista chileno Jorge Selarón. Una de las postales más coloridas de Río.",
    viral_trend: "Foto sentado en los escalones de azulejos coloridos",
    address: "R. Joaquim Silva, Lapa, Rio de Janeiro",
    lat: -22.9136,
    lng: -43.1786,
    search_query: "Escadaria Selarón Rio de Janeiro",
    emoji: "🎨",
    photo_concepts: [
      {
        title: "Sentado en los escalones coloridos",
        pose: "Sentado en un escalón, una pierna estirada, la otra flexionada. Manos apoyadas atrás. Mirar a la cámara con expresión relajada.",
        camera_angle: "Cámara desde unos escalones más arriba, apuntando hacia abajo en diagonal. Captura los azulejos como telón de fondo.",
        best_time: "Mañana temprano (8-9am) para evitar multitudes. La luz entra lateral.",
        clothing: "Ropa de colores sólidos que contrasten con los azulejos. Blanco o negro funcionan bien.",
        instagram_score: 10,
        camera_tip: "iPhone 1x. Evita el gran angular que distorsiona los azulejos. Busca un tramo con azulejos de un solo color para más impacto.",
        format: "Vertical 4:5",
      },
      {
        title: "Caminando escaleras arriba",
        pose: "Caminando escaleras arriba, de espaldas a la cámara. Un pie en un escalón, el otro subiendo. Natural, no posado.",
        camera_angle: "Cámara desde abajo, apuntando hacia arriba, capturando la extensión de la escalera.",
        best_time: "Mañana para menos gente y luz suave.",
        clothing: "Vestido o ropa fluida que se mueva al caminar.",
        instagram_score: 9,
        camera_tip: "iPhone 1x. Pide a alguien que dispare desde el último escalón mientras tú subes.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 2,
    best_time: "Mañana temprano",
  },
  {
    name: "Pão de Açúcar",
    name_en: "Sugarloaf Mountain",
    type: "tour",
    category: "landmark",
    description:
      "El pan de azúcar es el mirador natural más espectacular de Río. Se sube en teleférico con vistas de 360° de la bahía y la ciudad.",
    viral_trend: "Foto en el mirador con la bahía de Guanabara al fondo",
    address: "Av. Pasteur, Urca, Rio de Janeiro",
    lat: -22.9486,
    lng: -43.1566,
    search_query: "Pão de Açúcar Sugarloaf Mountain Rio de Janeiro",
    emoji: "⛰️",
    photo_concepts: [
      {
        title: "Mirador con la bahía de fondo",
        pose: "De pie en el mirador, de espaldas a la cámara, brazos abiertos. Bahía de Guanabara y Niterói al fondo.",
        camera_angle: "Cámara baja a la altura de la cintura, ligeramente hacia arriba.",
        best_time: "Atardecer (17-18h) para la luz dorada sobre la bahía. Reserva el teleférico con tiempo.",
        clothing: "Camisa abierta o polo, shorts. Colores claros que contrasten con el cielo.",
        instagram_score: 10,
        camera_tip: "iPhone 0.5x gran angular para capturar toda la bahía. Cuidado con el viento, sujeta bien el teléfono.",
        format: "Vertical 4:5",
      },
      {
        title: "Silueta al atardecer",
        pose: "De pie en el borde del mirador, perfil recortado contra el sol poniente. No mirar a la cámara.",
        camera_angle: "Cámara a media altura, ligeramente lateral, sol detrás del sujeto.",
        best_time: "Atardecer exacto, cuando el sol toca el horizonte.",
        clothing: "Ropa ajustada para que la silueta sea nítida. Nada voluminoso.",
        instagram_score: 9,
        camera_tip: "iPhone 2x para comprimir el sol. Toca en el sol para bajar la exposición y crear silueta.",
        format: "Horizontal",
      },
    ],
    instagram_score: 10,
    difficulty: 2,
    best_time: "Atardecer",
  },
  {
    name: "Mirante Dona Marta",
    name_en: "Dona Marta Viewpoint",
    type: "free",
    category: "viewpoint",
    description:
      "Mirador dentro del Parque Nacional da Tijuca con la vista más completa del Cristo Redentor de frente y la bahía de Botafogo.",
    viral_trend: "Foto panorámica con el Cristo de frente y la bahía abajo",
    address: "Estr. Dona Marta, Santa Teresa, Rio de Janeiro",
    lat: -22.9683,
    lng: -43.2547,
    search_query: "Mirante Dona Marta Rio de Janeiro",
    emoji: "🔭",
    photo_concepts: [
      {
        title: "Cristo de frente con la bahía",
        pose: "De pie en la baranda, de espaldas a la cámara, mirando al Cristo. Una mano en la baranda, postura relajada.",
        camera_angle: "Cámara a media altura, toma horizontal para capturar el Cristo, la bahía y la ciudad.",
        best_time: "Mañana (6-8am) para niebla matinal que da un toque místico. O atardecer para luz dorada.",
        clothing: "Chaqueta o polo, colores oscuros para no competir con el paisaje.",
        instagram_score: 10,
        camera_tip: "iPhone 1x o panorama horizontal. El Cristo se ve de FRENTE aquí, no de espaldas como desde el Corcovado.",
        format: "Horizontal 16:9",
      },
      {
        title: "Brazos abiertos con el Cristo",
        pose: "De pie, brazos completamente abiertos en T, mirando al Cristo. El Cristo debe estar visible detrás.",
        camera_angle: "Cámara baja, apuntando hacia arriba, sujeto centrado con el Cristo arriba.",
        best_time: "Mañana despejada para que el Cristo se vea nítido.",
        clothing: "Polo o camiseta blanca para contrastar con el verde de la montaña.",
        instagram_score: 9,
        camera_tip: "iPhone 0.5x para que el Cristo entre completo. Si hay neblina, espera a que se disipe.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 2,
    best_time: "Mañana temprano",
  },
  {
    name: "Pedra do Telégrafo",
    name_en: "Telegraph Rock",
    type: "tour",
    category: "hiking",
    description:
      "La sendera más viral de Río. La caminata termina en un acantilado donde la perspectiva crea una ilusión óptica perfecta para Instagram.",
    viral_trend: "Ilusión de colgando del acantilado (en realidad está a 50 cm del suelo)",
    address: "Estr. do Telegrafo, Pedra de Guaratiba, Rio de Janeiro",
    lat: -23.0136,
    lng: -43.2856,
    search_query: "Pedra do Telégrafo Rio de Janeiro",
    emoji: "🧗",
    photo_concepts: [
      {
        title: "Ilusión del precipicio",
        pose: "Acostado boca abajo, brazos extendidos hacia el vacío. La gracia es el ángulo: es una ilusión de perspectiva, la roca tiene terreno debajo.",
        camera_angle: "Cámara muy baja, casi a nivel del suelo. Toma vertical 4:5.",
        best_time: "Mañana temprano (7-9am) para evitar multitudes y buena luz.",
        clothing: "Polo blanco/negro o sin polo para algo más playero. Shorts.",
        instagram_score: 10,
        camera_tip: "iPhone con gran angular. Action 4 para POV de la caminata.",
        format: "Vertical 4:5",
      },
      {
        title: "Sentado en el borde",
        pose: "Sentado en el borde de la roca, piernas colgando, mirando al horizonte. Postura contemplativa.",
        camera_angle: "Cámara a media altura, ligeramente lateral, mostrando el vacío debajo.",
        best_time: "Mañana para luz suave y menos gente esperando su turno.",
        clothing: "Ropa de senderismo, zapatillas visibles. Nada de sandalias.",
        instagram_score: 9,
        camera_tip: "iPhone 1x. No uses gran angular aquí, distorsiona el vacío y pierde el efecto.",
        format: "Vertical 4:5",
      },
      {
        title: "Salto en la cima",
        pose: "Saltando en la cima de la roca, brazos en alto. Captura en el aire.",
        camera_angle: "Cámara desde abajo, modo burst para congelar el salto.",
        best_time: "Mañana, cuando hay menos gente y el viento es calmo.",
        clothing: "Ropa deportiva, zapatillas con buen agarre.",
        instagram_score: 8,
        camera_tip: "iPhone modo burst o Live Photo. Action 4 a 60fps para slow motion.",
        format: "Horizontal",
      },
    ],
    instagram_score: 10,
    difficulty: 3,
    best_time: "Mañana temprano",
  },
  {
    name: "Pedra da Gávea",
    name_en: "Gávea Rock",
    type: "tour",
    category: "hiking",
    description:
      "La montaña más imponente de Río con 842 m de altura. La subida es exigente pero la vista desde la cima abarca toda la Zona Sur.",
    viral_trend: "Foto en el borde de la roca con la ciudad y el mar de fondo",
    address: "Estr. do Sorim, Barra da Tijuca, Rio de Janeiro",
    lat: -22.9972,
    lng: -43.2856,
    search_query: "Pedra da Gávea Rio de Janeiro",
    emoji: "⛰️",
    photo_concepts: [
      {
        title: "Borde de la roca con la ciudad",
        pose: "Sentado en el borde de la roca, piernas colgando, mirando hacia Barra da Tijuca y el mar. Postura relajada, manos apoyadas atrás.",
        camera_angle: "Cámara a media altura, ligeramente atrás, capturando el vacío y la ciudad abajo.",
        best_time: "Mañana (llegar antes de las 10am) para evitar nubes y tener visibilidad.",
        clothing: "Ropa técnica de senderismo. Colores vivos (rojo, naranja) para destacar contra el verde y azul.",
        instagram_score: 10,
        camera_tip: "iPhone 1x. NO uses gran angular cerca del borde, la distorsión es peligrosa visualmente. Drone si tienes permiso.",
        format: "Vertical 4:5",
      },
      {
        title: "De pie en la cima con brazos abiertos",
        pose: "De pie en la cima, brazos abiertos en cruz, mirando al horizonte. Postura de victoria.",
        camera_angle: "Cámara baja, apuntando hacia arriba, sujeto contra el cielo.",
        best_time: "Mañana despejada.",
        clothing: "Camiseta técnica, nada voluminoso que el viento mueva.",
        instagram_score: 9,
        camera_tip: "iPhone 0.5x para capturar el cielo y la cima. Cuidado con el viento fuerte.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 5,
    best_time: "Mañana temprano",
  },
  {
    name: "Arpoador",
    name_en: "Arpoador Rock",
    type: "free",
    category: "viewpoint",
    description:
      "La roca entre Copacabana e Ipanema donde los cariocas se reúnen cada atardecer para aplaudir al sol. El mejor sunset de la ciudad.",
    viral_trend: "Aplausos colectivos al atardecer cuando el sol toca el mar",
    address: "Arpoador, Rio de Janeiro",
    lat: -22.9914,
    lng: -43.1908,
    search_query: "Pedra do Arpoador Rio de Janeiro",
    emoji: "👏",
    photo_concepts: [
      {
        title: "Silueta al atardecer",
        pose: "Mirando hacia el horizonte, sol detrás. Una pierna ligeramente adelante.",
        camera_angle: "Cámara a la altura de la cintura, ligeramente hacia arriba.",
        best_time: "Atardecer (17:30-18:30). Los domingos hay aplausos al sol.",
        clothing: "Camisa abierta o sin camisa, shorts de playa.",
        instagram_score: 10,
        camera_tip: "iPhone 2x zoom para comprimir el fondo.",
        format: "Vertical 4:5",
      },
      {
        title: "De espaldas en la roca",
        pose: "Sentado en la roca, mar delante, Dois Irmãos al fondo. No mirar a cámara.",
        camera_angle: "Cámara a media altura, ligeramente atrás.",
        best_time: "Atardecer",
        clothing: "Ropa casual, nada llamativo para que el paisaje domine.",
        instagram_score: 9,
        format: "Horizontal",
      },
      {
        title: "Aplausos al sol",
        pose: "De pie, manos aplaudiendo hacia el sol poniente. Gente alrededor haciendo lo mismo.",
        camera_angle: "Cámara a media altura, capturando a la multitud aplaudiendo.",
        best_time: "Exactamente cuando el sol toca el horizonte (17:45-18:15 según temporada).",
        clothing: "Ropa de playa, nada formal.",
        instagram_score: 9,
        camera_tip: "iPhone 1x en modo video para capturar el sonido de los aplausos. O Live Photo.",
        format: "Cuadrada 1:1",
      },
    ],
    instagram_score: 10,
    difficulty: 1,
    best_time: "Atardecer",
  },
  {
    name: "Morro Dois Irmãos",
    name_en: "Two Brothers Hill",
    type: "tour",
    category: "hiking",
    description:
      "Las dos montañas gemelas que dominan el skyline de Ipanema. La subida por Vidigal ofrece vistas únicas de las playas del sur.",
    viral_trend: "Foto sentado en la cima con Ipanema y Leblon a los pies",
    address: "Morro Dois Irmãos, Vidigal, Rio de Janeiro",
    lat: -23.0036,
    lng: -43.2489,
    search_query: "Morro Dois Irmãos Rio de Janeiro",
    emoji: "🏔️",
    photo_concepts: [
      {
        title: "Sentado en la cima con Ipanema abajo",
        pose: "Sentado en la roca de la cima, piernas colgando, Ipanema y Leblon visibles abajo. Manos apoyadas en la roca.",
        camera_angle: "Cámara a media altura, ligeramente lateral, capturando el vacío y las playas abajo.",
        best_time: "Mañana (7-9am) para evitar nubes y calor. La subida es por sol.",
        clothing: "Ropa técnica de senderismo, zapatillas. Colores que contrasten con el verde.",
        instagram_score: 10,
        camera_tip: "iPhone 1x. El 0.5x hace que las playas se vean pequeñas, mejor 1x o 2x.",
        format: "Vertical 4:5",
      },
      {
        title: "De pie entre las dos cumbres",
        pose: "De pie en el paso entre las dos cumbres, brazos abiertos. Las dos montañas enmarcan la foto.",
        camera_angle: "Cámara baja, apuntando hacia arriba, sujeto centrado entre las dos rocas.",
        best_time: "Mañana despejada.",
        clothing: "Camiseta técnica, nada voluminoso.",
        instagram_score: 9,
        camera_tip: "iPhone 0.5x para que ambas cumbres entren en el encuadre.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 4,
    best_time: "Mañana temprano",
  },
  {
    name: "Jardim Botânico",
    name_en: "Rio de Janeiro Botanical Garden",
    type: "visit",
    category: "park",
    description:
      "Jardín botánico con más de 200 años, famoso por sus palmeras imperiales gigantes que forman un túnel verde espectacular.",
    viral_trend: "Foto caminando bajo el túnel de palmeras imperiales",
    address: "R. Jardim Botânico 1008, Jardim Botânico, Rio de Janeiro",
    lat: -22.9697,
    lng: -43.2256,
    search_query: "Jardim Botânico Rio de Janeiro",
    emoji: "🌴",
    photo_concepts: [
      {
        title: "Túnel de palmeras imperiales",
        pose: "Caminando por el centro del túnel de palmeras, de espaldas a la cámara. Paso natural, no posado.",
        camera_angle: "Cámara a media altura, centrada, capturando la simetría del túnel de palmeras.",
        best_time: "Mañana (8-10am) cuando la luz entra diagonal entre las palmeras. Menos gente.",
        clothing: "Vestido o ropa fluida, colores claros. Nada de patrones que compitan con las palmeras.",
        instagram_score: 10,
        camera_tip: "iPhone 1x, NO gran angular. La simetría es clave, el 0.5x la rompe. Centra perfectamente.",
        format: "Vertical 4:5",
      },
      {
        title: "Bajo una palmera imperial",
        pose: "Sentado o de pie al pie de una palmera imperial, mirando hacia arriba. Una mano tocando el tronco.",
        camera_angle: "Cámara desde el suelo, apuntando hacia arriba, capturando la altura de la palmera.",
        best_time: "Mañana con luz lateral.",
        clothing: "Ropa casual, colores tierra o verdes.",
        instagram_score: 8,
        camera_tip: "iPhone 0.5x gran angular para capturar toda la altura. Toca en el cielo para exponer correctamente.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana temprano",
  },
  {
    name: "Arcos da Lapa",
    name_en: "Lapa Arches",
    type: "free",
    category: "nightlife",
    description:
      "El acueducto colonial del siglo XVIII es el símbolo de Lapa, el barrio bohemio de Río. De noche se convierte en el epicentro de la fiesta y la samba.",
    viral_trend: "Foto nocturna bajo los arcos iluminados con la calle llena de gente",
    address: "Lapa, Rio de Janeiro",
    lat: -22.9128,
    lng: -43.1797,
    search_query: "Arcos da Lapa Rio de Janeiro",
    emoji: "🎭",
    photo_concepts: [
      {
        title: "Bajo los arcos iluminados",
        pose: "De pie bajo un arco, mirando hacia arriba, brazos relajados. El arco enmarca la foto.",
        camera_angle: "Cámara baja, apuntando hacia arriba, capturando la curva del arco y el cielo.",
        best_time: "Noche (20-23h) cuando los arcos están iluminados y la calle está viva.",
        clothing: "Ropa de noche, camisa oscura. Nada llamativo, los arcos son el protagonista.",
        instagram_score: 9,
        camera_tip: "iPhone modo Noche. Sujeta el teléfono contra una pared para estabilizar. El bonde (tranvía) pasa por arriba.",
        format: "Vertical 4:5",
      },
      {
        title: "Calle llena de gente y samba",
        pose: "Caminando por la calle bajo los arcos, gente y fiesta de fondo. Movimiento natural.",
        camera_angle: "Cámara a media altura, toma horizontal, capturando el ambiente nocturno.",
        best_time: "Viernes o sábado noche (22-1h) cuando Lapa está en su apogeo.",
        clothing: "Ropa casual de noche. Nada formal.",
        instagram_score: 8,
        camera_tip: "iPhone modo Noche o Live Photo. Action 4 para video con estabilización entre la multitud.",
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Noche",
  },
  {
    name: "Vista Chinesa",
    name_en: "Chinese View",
    type: "free",
    category: "viewpoint",
    description:
      "Mirador con un pagoda china dentro del Parque Nacional da Tijuca. Oferce una vista única de la Tijuca, Ipanema y el Maracanã.",
    viral_trend: "Foto junto al mirador chino con la selva y la ciudad al fondo",
    address: "Estr. da Vista Chinesa, Alto da Boa Vista, Rio de Janeiro",
    lat: -22.965,
    lng: -43.253,
    search_query: "Vista Chinesa Rio de Janeiro",
    emoji: "🏯",
    photo_concepts: [
      {
        title: "Junto al pagoda chino",
        pose: "De pie junto al pagoda chino, una mano apoyada en la baranda. Mirar hacia la vista, no a la cámara.",
        camera_angle: "Cámara a media altura, ligeramente lateral, capturando el pagoda y la vista de fondo.",
        best_time: "Mañana (7-9am) para niebla matinal entre las montañas. Efecto místico.",
        clothing: "Chaqueta o polo, colores que contrasten con el verde de la selva.",
        instagram_score: 9,
        camera_tip: "iPhone 1x. El pagoda es pequeño, no lo alejes demasiado. 2x si quieres comprimir el fondo.",
        format: "Vertical 4:5",
      },
      {
        title: "Panorámica de Tijuca y Ipanema",
        pose: "De pie en el mirador, brazos abiertos, mirando hacia Ipanema y el mar. Postura de asombro.",
        camera_angle: "Cámara baja, toma horizontal panorámica, capturando la selva, la ciudad y el mar.",
        best_time: "Mañana despejada para máxima visibilidad.",
        clothing: "Ropa de senderismo, colores vivos.",
        instagram_score: 9,
        camera_tip: "iPhone modo panorama. Si hay neblina, espera 10 minutos, suele disiparse.",
        format: "Horizontal 16:9",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Mañana temprano",
  },
  {
    name: "Parque Lage",
    name_en: "Parque Lage",
    type: "free",
    category: "park",
    description:
      "Mansión colonial rodeada de jardines tropicales al pie del Corcovado. La casa principal con sus arcos es un dream para fotografía.",
    viral_trend: "Foto en el patio de la mansión con los arcos y el Corcovado al fondo",
    address: "R. Jardim Botânico 414, Jardim Botânico, Rio de Janeiro",
    lat: -22.9578,
    lng: -43.2125,
    search_query: "Parque Lage Rio de Janeiro",
    emoji: "🏛️",
    photo_concepts: [
      {
        title: "Patio de la mansión con arcos",
        pose: "De pie en el patio interior, centrada entre los arcos, mirando hacia el Corcovado. Postura elegante.",
        camera_angle: "Cámara a media altura, centrada, capturando la simetría de los arcos y el Corcovado al fondo.",
        best_time: "Mañana (8-10am) cuando no hay gente y la luz entra suave por los arcos.",
        clothing: "Vestido elegante o ropa formal. El entorno pide algo clásico, no deportivo.",
        instagram_score: 10,
        camera_tip: "iPhone 1x. La simetría es TODO. Centra perfectamente entre los arcos. 0.5x si necesitas más amplitud.",
        format: "Vertical 4:5",
      },
      {
        title: "Sentado en los escalones de la mansión",
        pose: "Sentado en los escalones de entrada, una pierna estirada, mirando hacia los jardines. Relajado.",
        camera_angle: "Cámara desde abajo, ligeramente lateral, capturando la fachada de la mansión.",
        best_time: "Mañana o tarde para luz suave.",
        clothing: "Ropa casual elegante. Nada deportivo.",
        instagram_score: 8,
        camera_tip: "iPhone 1x. Usa el modo retrato para separar el sujeto de la fachada.",
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana temprano",
  },
  {
    name: "Pedra Bonita",
    name_en: "Pedra Bonita",
    type: "tour",
    category: "hiking",
    description:
      "Caminata corta y accesible con una de las mejores vistas de São Conrado y el mar. Punto de despegue de ala delta más famoso de Río.",
    viral_trend: "Foto con los ala delta despegando al fondo",
    address: "Estr. das Canoas, São Conrado, Rio de Janeiro",
    lat: -22.9925,
    lng: -43.2722,
    search_query: "Pedra Bonita Rio de Janeiro",
    emoji: "🪂",
    photo_concepts: [
      {
        title: "Ala delta despegando al fondo",
        pose: "De pie en el mirador, brazos abiertos simulando vuelo. Ala delta despegando detrás.",
        camera_angle: "Cámara a media altura, capturando el ala delta en el aire y el sujeto en primer plano.",
        best_time: "Mañana (9-11am) cuando hay viento y los ala delta están activos.",
        clothing: "Ropa de senderismo, colores vivos para destacar contra el cielo.",
        instagram_score: 9,
        camera_tip: "iPhone 1x o 2x para capturar el ala delta sin que se vea tiny. Modo burst para congelar el despegue.",
        format: "Vertical 4:5",
      },
      {
        title: "Sentado en el borde con São Conrado",
        pose: "Sentado en el borde de la roca, piernas colgando, mirando hacia São Conrado y el mar.",
        camera_angle: "Cámara a media altura, ligeramente lateral, capturando el vacío y la playa abajo.",
        best_time: "Mañana despejada.",
        clothing: "Ropa técnica, zapatillas con buen agarre.",
        instagram_score: 9,
        camera_tip: "iPhone 1x. NO uses gran angular cerca del borde.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 3,
    best_time: "Mañana",
  },
  {
    name: "Favela Santa Marta",
    name_en: "Santa Marta Favela",
    type: "visit",
    category: "landmark",
    description:
      "La primera favela pacificada de Río, famosa por el clip de 'They Don't Care About Us' de Michael Jackson. Sus casas coloridas escalan la montaña.",
    viral_trend: "Foto en la estatua de Michael Jackson replicando sus pasos de baile",
    address: "R. São Bernardo, Botafogo, Rio de Janeiro",
    lat: -22.9444,
    lng: -43.2056,
    search_query: "Favela Santa Marta Rio de Janeiro",
    emoji: "🕺",
    photo_concepts: [
      {
        title: "Estatua de Michael Jackson",
        pose: "Junto a la estatua de bronce de MJ, replicando su pose de baile. Pierna levantada, brazo en alto.",
        camera_angle: "Cámara a media altura, capturando la estatua y el sujeto lado a lado.",
        best_time: "Mañana (9-11am) para luz suave y menos turistas.",
        clothing: "Ropa casual. Si tienes una chaqueta tipo MJ, mejor.",
        instagram_score: 9,
        camera_tip: "iPhone 1x. La estatua es pequeña, acércate. Modo retrato para separar del fondo.",
        format: "Vertical 4:5",
      },
      {
        title: "Casas coloridas escalando la montaña",
        pose: "De pie en la plaza, mirando hacia arriba donde las casas coloridas escalan la montaña. Manos en la cintura.",
        camera_angle: "Cámara baja, apuntando hacia arriba, capturando la cascada de casas coloridas.",
        best_time: "Mañana o tarde para luz lateral sobre las fachadas.",
        clothing: "Ropa casual, colores sólidos.",
        instagram_score: 8,
        camera_tip: "iPhone 0.5x gran angular para capturar toda la extensión de casas. El funicular sube, úsalo.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Mañana",
  },
  {
    name: "Praia de Botafogo",
    name_en: "Botafogo Beach",
    type: "free",
    category: "beach",
    description:
      "Playa urbana con la mejor vista del Pão de Açúcar y la bahía de Guanabara. Ideal para pasear y ver el atardecer con la ciudad de fondo.",
    viral_trend: "Foto con el Pão de Açúcar reflejándose en el agua al atardecer",
    address: "Av. das Nações Unidas, Botafogo, Rio de Janeiro",
    lat: -22.9456,
    lng: -43.1864,
    search_query: "Praia de Botafogo Rio de Janeiro",
    emoji: "🌅",
    photo_concepts: [
      {
        title: "Pão de Açúcar reflejado en el agua",
        pose: "De pie en la orilla, de espaldas a la cámara, mirando al Pão de Açúcar. Reflejo en el agua calmada.",
        camera_angle: "Cámara baja, casi a nivel del agua, capturando el reflejo del Sugarloaf.",
        best_time: "Atardecer (17-18h) cuando la marea está baja y el agua está calmada.",
        clothing: "Ropa casual, colores que no compitan con el atardecer.",
        instagram_score: 9,
        camera_tip: "iPhone 2x para comprimir el Sugarloaf y que se vea grande. Toca en el cielo para exponer el atardecer.",
        format: "Horizontal",
      },
      {
        title: "Corriendo por la orilla al atardecer",
        pose: "Corriendo por la orilla, salpicando agua, Sugarloaf al fondo. Silueta contra el sol poniente.",
        camera_angle: "Cámara baja, en movimiento paralelo. Silueta del corredor contra el atardecer.",
        best_time: "Atardecer para luz dorada y sombras largas.",
        clothing: "Ropa deportiva, camiseta técnica.",
        instagram_score: 8,
        camera_tip: "Action 4 en modo burst. iPhone Live Photo para capturar el salpicar.",
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer",
  },
  {
    name: "Lagoa Rodrigo de Freitas",
    name_en: "Rodrigo de Freitas Lagoon",
    type: "free",
    category: "park",
    description:
      "La laguna corazón de la Zona Sur, rodeada de montañas. Pista de 7 km para caminar, andar en bici o patinar con vistas al Corcovado.",
    viral_trend: "Foto en el paddleboard en la laguna con el Cristo al fondo",
    address: "Lagoa Rodrigo de Freitas, Rio de Janeiro",
    lat: -22.9736,
    lng: -43.2131,
    search_query: "Lagoa Rodrigo de Freitas Rio de Janeiro",
    emoji: "🚣",
    photo_concepts: [
      {
        title: "Paddleboard con el Cristo al fondo",
        pose: "De pie en el paddleboard, remando, Corcovado y el Cristo visible al fondo. Postura equilibrada.",
        camera_angle: "Cámara a media altura desde la orilla o drone. Capturar el reflejo en la laguna.",
        best_time: "Mañana (7-9am) cuando la laguna está calmada y hay reflejos perfectos.",
        clothing: "Traje de baño, camiseta UV. Nada voluminoso.",
        instagram_score: 10,
        camera_tip: "iPhone con gran angular desde la orilla. Drone si tienes permiso. El reflejo del Cristo en el agua es la magia.",
        format: "Horizontal",
      },
      {
        title: "Bici o patín por la pista",
        pose: "En bici o patín por la pista de la laguna, montañas al fondo. Movimiento natural.",
        camera_angle: "Cámara baja, en movimiento paralelo si usas Action 4.",
        best_time: "Mañana o atardecer para luz dorada y menos calor.",
        clothing: "Ropa deportiva, casco opcional.",
        instagram_score: 8,
        camera_tip: "Action 4 montada en el manubrio o el pecho. iPhone en modo retrato desde la orilla.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Mañana temprano",
  },
  {
    name: "Praia do Flamengo",
    name_en: "Flamengo Beach",
    type: "free",
    category: "beach",
    description:
      "Playa extensa bordeada por el Parque do Flamengo, con vistas al Pão de Açúcar y la bahía. Punto favorito de los cariocas para hacer ejercicio.",
    viral_trend: "Foto corriendo por la orilla con el Sugarloaf al fondo",
    address: "Av. Infante Dom Henrique, Flamengo, Rio de Janeiro",
    lat: -22.9306,
    lng: -43.1689,
    search_query: "Praia do Flamengo Rio de Janeiro",
    emoji: "🏃",
    photo_concepts: [
      {
        title: "Corriendo con el Sugarloaf al fondo",
        pose: "Corriendo por la orilla, paso medio, Sugarloaf visible al fondo. Mirar al frente, no a la cámara.",
        camera_angle: "Cámara baja, en movimiento paralelo. Capturar la silueta contra el amanecer.",
        best_time: "Amanecer (5:30-7am) cuando los cariocas corren y la luz es dorada.",
        clothing: "Ropa deportiva, camiseta técnica. Zapatillas.",
        instagram_score: 9,
        camera_tip: "Action 4 en modo burst a 30fps. iPhone Live Photo para congelar el movimiento.",
        format: "Horizontal",
      },
      {
        title: "Sentado en el muro mirando la bahía",
        pose: "Sentado en el muro del malecón, piernas colgando, mirando a la bahía. Postura contemplativa.",
        camera_angle: "Cámara a media altura, ligeramente lateral, capturando la bahía y el Sugarloaf.",
        best_time: "Atardecer para luz dorada.",
        clothing: "Ropa casual, nada deportivo para esta toma.",
        instagram_score: 8,
        camera_tip: "iPhone 2x para comprimir el Sugarloaf. Toca en el cielo para exponer el atardecer.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Amanecer",
  },
  {
    name: "Igreja da Candelária",
    name_en: "Candelária Church",
    type: "visit",
    category: "landmark",
    description:
      "La iglesia más imponente del centro de Río, con su cúpula deslumbrante y fachada neoclásica. Joya arquitectónica del siglo XVIII.",
    viral_trend: "Foto del interior con la cúpula iluminada y los vitrales",
    address: "Praça Pio X, Centro, Rio de Janeiro",
    lat: -22.9006,
    lng: -43.1797,
    search_query: "Igreja da Candelária Rio de Janeiro",
    emoji: "⛪",
    photo_concepts: [
      {
        title: "Interior con cúpula iluminada",
        pose: "De pie en el centro de la nave, mirando hacia arriba, brazos a los lados. La cúpula domina el encuadre.",
        camera_angle: "Cámara desde el suelo, apuntando directamente hacia arriba, capturando la cúpula y los vitrales.",
        best_time: "Mañana (9-11am) cuando la luz entra por los vitrales y la cúpula está iluminada.",
        clothing: "Ropa modesta (es una iglesia). Nada de shorts cortos o tirantes.",
        instagram_score: 9,
        camera_tip: "iPhone 0.5x gran angular para capturar toda la cúpula. Sujeta el teléfono contra el suelo para estabilizar.",
        format: "Vertical 4:5",
      },
      {
        title: "Fachada neoclásica",
        pose: "De pie frente a la iglesia, de espaldas, mirando hacia la fachada. Postura reverente.",
        camera_angle: "Cámara a media altura, centrada, capturando la simetría de la fachada.",
        best_time: "Mañana para luz frontal sobre la fachada.",
        clothing: "Ropa modesta, colores sólidos.",
        instagram_score: 8,
        camera_tip: "iPhone 1x. La simetría es clave. Centra perfectamente. 0.5x si necesitas capturar toda la fachada.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana",
  },
  {
    name: "Theatro Municipal",
    name_en: "Municipal Theatre",
    type: "visit",
    category: "landmark",
    description:
      "Teatro inspirado en la Ópera de París, uno de los más bellos de Brasil. Su fachada y escalinata son un ícono del centro histórico.",
    viral_trend: "Foto en la escalinata imitando una noche de ópera",
    address: "Praça Floriano, Centro, Rio de Janeiro",
    lat: -22.9097,
    lng: -43.1764,
    search_query: "Theatro Municipal Rio de Janeiro",
    emoji: "🎭",
    photo_concepts: [
      {
        title: "Escalinata estilo ópera",
        pose: "De pie en la escalinata, una mano en la baranda, mirando hacia la fachada. Postura elegante, como llegando a una gala.",
        camera_angle: "Cámara desde abajo, ligeramente lateral, capturando la escalinata y la fachada del teatro.",
        best_time: "Mañana (9-11am) para luz suave y menos gente. O de noche si está iluminado.",
        clothing: "Ropa elegante. Traje o vestido formal. El entorno pide algo clásico.",
        instagram_score: 9,
        camera_tip: "iPhone 1x. La escalinata es el escenario, no la recortes. 0.5x si necesitas más amplitud.",
        format: "Vertical 4:5",
      },
      {
        title: "Fachada iluminada de noche",
        pose: "De pie frente a la fachada, de espaldas, mirando hacia el teatro. Postura contemplativa.",
        camera_angle: "Cámara a media altura, centrada, capturando la fachada iluminada.",
        best_time: "Noche (19-21h) cuando la fachada está iluminada.",
        clothing: "Ropa elegante de noche.",
        instagram_score: 8,
        camera_tip: "iPhone modo Noche. Sujeta contra una columna para estabilizar.",
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana o noche",
  },
  {
    name: "Museu do Amanhã",
    name_en: "Museum of Tomorrow",
    type: "visit",
    category: "museum",
    description:
      "Museo de ciencia futurista con una arquitectura deslumbrante a orillas de la bahía. El edificio solo ya es una obra de arte.",
    viral_trend: "Foto del exterior con el reflejo del museo en la bahía",
    address: "Praça Mauá 1, Centro, Rio de Janeiro",
    lat: -22.8947,
    lng: -43.1797,
    search_query: "Museu do Amanhã Rio de Janeiro",
    emoji: "🚀",
    photo_concepts: [
      {
        title: "Reflejo del museo en la bahía",
        pose: "De pie en el muelle, de espaldas a la cámara, mirando al museo. Reflejo del edificio en el agua.",
        camera_angle: "Cámara baja, casi a nivel del agua, capturando el reflejo del museo.",
        best_time: "Mañana (8-10am) cuando el agua está calmada y hay reflejos perfectos.",
        clothing: "Ropa moderna, líneas limpias. El edificio es futurista, la ropa debe acompañar.",
        instagram_score: 10,
        camera_tip: "iPhone 1x. El reflejo es la magia, busca el ángulo donde el agua está más calmada. 2x para comprimir.",
        format: "Horizontal",
      },
      {
        title: "Arquitectura futurista de cerca",
        pose: "De pie junto a las columnas del museo, mirando hacia arriba. Las líneas del edificio enmarcan la foto.",
        camera_angle: "Cámara desde el suelo, apuntando hacia arriba, capturando las líneas geométricas del edificio.",
        best_time: "Mañana o atardecer para luz que resalte las formas.",
        clothing: "Ropa minimalista, colores sólidos.",
        instagram_score: 9,
        camera_tip: "iPhone 0.5x gran angular para capturar las líneas. Las formas geométricas son el protagonista.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 1,
    best_time: "Mañana temprano",
  },
  {
    name: "MAR - Museu de Arte do Rio",
    name_en: "Museum of Art of Rio",
    type: "visit",
    category: "museum",
    description:
      "Museo de arte con una curva ondulada icónica que conecta dos edificios históricos. Exhibe arte brasileño y exposiciones temporales.",
    viral_trend: "Foto en la azotea con vista a la bahía y el Museu do Amanhã",
    address: "Praça Mauá 5, Centro, Rio de Janeiro",
    lat: -22.8972,
    lng: -43.1797,
    search_query: "Museu de Arte do Rio MAR Rio de Janeiro",
    emoji: "🖼️",
    photo_concepts: [
      {
        title: "Azotea con vista a la bahía",
        pose: "De pie en la azotea, de espaldas a la cámara, mirando hacia la bahía y el Museu do Amanhã. Brazos relajados.",
        camera_angle: "Cámara a media altura, capturando la bahía, el Museu do Amanhã y la curva del edificio MAR.",
        best_time: "Atardecer (17-18h) para luz dorada sobre la bahía.",
        clothing: "Ropa moderna, colores que contrasten con el cielo.",
        instagram_score: 9,
        camera_tip: "iPhone 1x. La curva ondulada del MAR es única, encuádrala. 0.5x si necesitas más amplitud.",
        format: "Horizontal",
      },
      {
        title: "Curva ondulada del edificio",
        pose: "De pie junto a la curva del edificio, una mano tocando la pared. Mirar hacia la cámara.",
        camera_angle: "Cámara a media altura, ligeramente lateral, capturando la curva del edificio.",
        best_time: "Mañana para luz suave sobre la fachada.",
        clothing: "Ropa minimalista, líneas limpias.",
        instagram_score: 8,
        camera_tip: "iPhone 1x. La curva es el protagonista, no la recortes.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer",
  },
  {
    name: "Bondinho do Pão de Açúcar",
    name_en: "Sugarloaf Cable Car",
    type: "transport",
    category: "landmark",
    description:
      "El teleférico que sube al Morro da Urca y al Pão de Açúcar. El viaje en sí es parte de la experiencia, con vistas aéreas de la bahía.",
    viral_trend: "Foto dentro del teleférico de vidrio con la bahía a los pies",
    address: "Av. Pasteur 520, Urca, Rio de Janeiro",
    lat: -22.9486,
    lng: -43.1566,
    search_query: "Bondinho Pão de Açúcar Rio de Janeiro",
    emoji: "🚡",
    photo_concepts: [
      {
        title: "Dentro del teleférico de vidrio",
        pose: "De pie dentro del teleférico, mirando hacia la bahía a través del vidrio. Una mano en el barandal.",
        camera_angle: "Cámara a media altura, capturando el sujeto, el vidrio y la bahía al fondo.",
        best_time: "Atardecer (17-18h) para la luz dorada sobre la bahía desde el aire.",
        clothing: "Ropa casual, colores que no se fundan con el vidrio.",
        instagram_score: 9,
        camera_tip: "iPhone 1x. El vidrio genera reflejos, pon el lente pegado al cristal. Evita el flash.",
        format: "Vertical 4:5",
      },
      {
        title: "Salida del teleférico",
        pose: "En el momento de salir del teleférico en la cima, un pie fuera, mirando la vista. Captura la transición.",
        camera_angle: "Cámara a media altura, desde dentro del teleférico, capturando la salida y la vista.",
        best_time: "Atardecer para luz dorada.",
        clothing: "Ropa casual, nada voluminoso.",
        instagram_score: 8,
        camera_tip: "Action 4 para POV. iPhone en modo burst para capturar el momento exacto.",
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer",
  },
  {
    name: "Forte de Copacabana",
    name_en: "Fort Copacabana",
    type: "visit",
    category: "viewpoint",
    description:
      "Fuerte militar de 1914 en el extremo de Copacabana con mirador al mar y al Pão de Açúcar. El café del fuerte tiene la mejor vista de la playa.",
    viral_trend: "Foto en el mirador del fuerte con Copacabana y el Sugarloaf",
    address: "Praça Coronel Eugênio Franco 1, Copacabana, Rio de Janeiro",
    lat: -22.9842,
    lng: -43.1908,
    search_query: "Forte de Copacabana Rio de Janeiro",
    emoji: "🏰",
    photo_concepts: [
      {
        title: "Mirador con Copacabana y Sugarloaf",
        pose: "De pie en el mirador del fuerte, de espaldas a la cámara, mirando hacia Copacabana y el Sugarloaf. Manos en la baranda.",
        camera_angle: "Cámara a media altura, capturando la extensión de Copacabana y el Sugarloaf al fondo.",
        best_time: "Mañana (8-10am) para luz frontal sobre la playa y el Sugarloaf.",
        clothing: "Ropa casual, colores claros. Nada que compita con el paisaje.",
        instagram_score: 9,
        camera_tip: "iPhone 1x o 2x para comprimir el Sugarloaf. El café del fuerte tiene la misma vista, aprovecha la terraza.",
        format: "Horizontal",
      },
      {
        title: "Café con vista",
        pose: "Sentado en la terraza del café del fuerte, taza de café en mano, Copacabana al fondo. Postura relajada.",
        camera_angle: "Cámara a media altura, ligeramente lateral, capturando la taza, el sujeto y la playa.",
        best_time: "Mañana para desayuno con vista.",
        clothing: "Ropa casual elegante. El entorno pide algo presentable.",
        instagram_score: 8,
        camera_tip: "iPhone 2x modo retrato para separar la taza y el sujeto del fondo. El bokeh resalta la vista.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana",
  },
  {
    name: "Pedra do Sal",
    name_en: "Pedra do Sal",
    type: "free",
    category: "nightlife",
    description:
      "Considerada la cuna de la samba en Río. Los lunes y viernes hay rodas de samba al aire libre en este callejón histórico de la Salud.",
    viral_trend: "Video bailando samba con la banda en la calle",
    address: "R. Pedra do Sal, Saúde, Rio de Janeiro",
    lat: -22.8986,
    lng: -43.1889,
    search_query: "Pedra do Sal Rio de Janeiro",
    emoji: "🥁",
    photo_concepts: [
      {
        title: "Bailando samba con la banda",
        pose: "Bailando samba en medio de la roda, gente y músicos alrededor. Movimiento natural, no coreografiado.",
        camera_angle: "Cámara a media altura, en movimiento si usas Action 4. Capturar el ambiente de la calle.",
        best_time: "Lunes o viernes noche (19-22h) cuando hay roda de samba al aire libre.",
        clothing: "Ropa casual, nada formal. Ropa que te deje moverte.",
        instagram_score: 9,
        camera_tip: "Action 4 a 60fps para slow motion del baile. iPhone en modo video 4K. El sonido ambiente es clave, no lo filtres.",
        format: "Vertical 9:16",
      },
      {
        title: "Con los músicos",
        pose: "Junto a los músicos de la roda, sonriendo, instrumentos de fondo. Postura de fan.",
        camera_angle: "Cámara a media altura, capturando al sujeto y los músicos tocando.",
        best_time: "Lunes o viernes noche durante la roda.",
        clothing: "Ropa casual, colores vivos para destacar entre la gente.",
        instagram_score: 8,
        camera_tip: "iPhone 1x. Modo retrato no funciona bien en noche con movimiento, mejor modo normal.",
        format: "Cuadrada 1:1",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Lunes o viernes noche",
  },
  {
    name: "Praia de São Conrado",
    name_en: "São Conrado Beach",
    type: "free",
    category: "beach",
    description:
      "Playa al pie de la Pedra da Gávea, donde aterrizan los ala delta. Más tranquila que Copacabana, con arena extensa y la montaña de fondo.",
    viral_trend: "Foto con los ala delta aterrizando en la arena detrás",
    address: "Av. Niemeyer, São Conrado, Rio de Janeiro",
    lat: -22.9989,
    lng: -43.2461,
    search_query: "Praia de São Conrado Rio de Janeiro",
    emoji: "🪁",
    photo_concepts: [
      {
        title: "Ala delta aterrizando en la arena",
        pose: "De pie en la arena, mirando hacia el ala delta que aterriza. Un brazo señalando al cielo.",
        camera_angle: "Cámara a media altura, capturando el ala delta en el aire y la Pedra da Gávea al fondo.",
        best_time: "Mañana (10-12h) cuando los ala delta están aterrizando.",
        clothing: "Ropa de playa, traje de baño. Colores que contrasten con el cielo.",
        instagram_score: 9,
        camera_tip: "iPhone 1x o 2x para capturar el ala delta sin que se vea tiny. Modo burst para congelar el aterrizaje.",
        format: "Vertical 4:5",
      },
      {
        title: "Pedra da Gávea desde la playa",
        pose: "Acostado en la arena, cabeza hacia la cámara, Pedra da Gávea dominando el fondo. Brazos relajados.",
        camera_angle: "Cámara muy baja, casi tocando la arena, apuntando hacia la montaña.",
        best_time: "Mañana para luz lateral sobre la montaña.",
        clothing: "Traje de baño, sin camisa. Gafas de sol opcionales.",
        instagram_score: 8,
        camera_tip: "iPhone 0.5x gran angular para que la montaña domine. Limpia el lente, la arena lo empaña.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana",
  },
];
