import type { CuratedSpot } from "@/lib/photo-types";
export type { CuratedSpot };

export const CURATED_SPOTS_SP: CuratedSpot[] = [
  {
    name: "Beco do Batman",
    name_en: "Batman's Alley",
    type: "free",
    category: "street-art",
    description:
      "Callejón emblemático de Vila Madalena repleto de murales y graffitis en constante cambio. Punto de peregrinación para amantes del arte urbano y uno de los spots más instagramables de São Paulo.",
    viral_trend: "Murales cambiantes + fotos con arte urbano",
    photo_concepts: [
      {
        title: "Frente al mural",
        pose: "De espaldas al mural, mirando hacia la calle. No posar, caminar naturalmente.",
        camera_angle: "Cámara a media altura, gran angular para capturar el mural completo.",
        best_time: "Mañana (8-10am) cuando hay menos gente y mejor luz.",
        clothing: "Ropa colorida que contraste con el graffiti.",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para capturar todo el mural.",
        format: "Vertical 4:5",
      },
      {
        title: "Perspectiva del callejón",
        pose: "Caminando por el centro del callejón, de espaldas al fotógrafo.",
        camera_angle: "Cámara baja a ras de suelo, mirando hacia arriba para profundidad.",
        best_time: "Mediodía con luz cenital que ilumina las paredes.",
        clothing: "Outfit monocromático para destacar contra el color.",
        instagram_score: 8,
        camera_tip: "Modo retrato para separar la figura del fondo.",
        format: "Vertical 9:16",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana",
    address: "R. Gonçalo Afonso, 157 - Vila Madalena, São Paulo - SP",
    lat: -23.5544,
    lng: -46.6906,
    search_query: "Beco do Batman Vila Madalena São Paulo",
    emoji: "🎨",
  },
  {
    name: "MASP - Museu de Arte de São Paulo",
    name_en: "São Paulo Museum of Art",
    type: "visit",
    category: "museum",
    description:
      "Icono arquitectónico en la Avenida Paulista con la colección de arte europeo más importante del hemisferio sur. Su estructura suspendida deja un vacío libre debajo, plaza muy fotografiada.",
    viral_trend: "Foto bajo el vano libre del edificio + cristales suspendidos",
    photo_concepts: [
      {
        title: "Bajo el vano libre",
        pose: "De pie bajo el vano libre del edificio, brazos relajados, mirando hacia arriba.",
        camera_angle: "Cámara baja en el suelo apuntando hacia arriba para capturar el vano.",
        best_time: "Mañana (9-11am) con luz suave y menos tráfico.",
        clothing: "Ropa minimalista en blanco o negro para contrasto arquitectónico.",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para abarcar toda la estructura.",
        format: "Vertical 4:5",
      },
      {
        title: "Cristales suspendidos",
        pose: "Frente a los cristales suspendidos, perfil, mirando la colección.",
        camera_angle: "Cámara a la altura de los ojos, ligero contrapicado.",
        best_time: "Tarde (14-16h) cuando la luz entra por los cristales.",
        clothing: "Outfit elegante, tonos neutros.",
        instagram_score: 8,
        camera_tip: "Evitar reflejos con polarizador o ajustando el ángulo.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana",
    address: "Av. Paulista, 1578 - Bela Vista, São Paulo - SP",
    lat: -23.5614,
    lng: -46.6565,
    search_query: "MASP Museu de Arte São Paulo Avenida Paulista",
    emoji: "🖼️",
  },
  {
    name: "Avenida Paulista",
    name_en: "Paulista Avenue",
    type: "free",
    category: "landmark",
    description:
      "El principal eje financiero y cultural de São Paulo. Llena de museos, centros culturales, cafés y ciclovía. Los domingos se cierra al tráfico y se llena de artistas callejeros.",
    viral_trend: "Ciclovía dominical + skyline de rascacielos",
    photo_concepts: [
      {
        title: "Ciclovía dominical",
        pose: "Montando bicicleta o caminando por la ciclovía, movimiento natural.",
        camera_angle: "Cámara a media altura, plano americano en movimiento.",
        best_time: "Domingo por la mañana (10-12h) cuando está cerrada al tráfico.",
        clothing: "Outfit casual deportivo, colores vivos.",
        instagram_score: 8,
        camera_tip: "Modo ráfaga para capturar el momento en movimiento.",
        format: "Vertical 4:5",
      },
      {
        title: "Skyline de rascacielos",
        pose: "De espaldas a la cámara, mirando hacia los rascacielos al fondo.",
        camera_angle: "Cámara baja, contrapicado para enfatizar la altura de los edificios.",
        best_time: "Blue hour (18-19h) con luces de la ciudad encendidas.",
        clothing: "Ropa oscura para silueta contra el cielo.",
        instagram_score: 8,
        camera_tip: "HDR para equilibrar cielo y edificios.",
        format: "Vertical 9:16",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Domingo mañana",
    address: "Av. Paulista - Bela Vista, São Paulo - SP",
    lat: -23.5613,
    lng: -46.6565,
    search_query: "Avenida Paulista São Paulo",
    emoji: "🏙️",
  },
  {
    name: "Parque Ibirapuera",
    name_en: "Ibirapuera Park",
    type: "free",
    category: "park",
    description:
      "El 'Central Park' paulistano: 158 hectáreas de lagos, museos (Niemeyer), pabellones y senderos. Ideal para correr, andar en patineta o hacer picnic. Uno de los parques urbanos más visitados de Latinoamérica.",
    viral_trend: "Lago con reflejos + arquitectura de Niemeyer",
    photo_concepts: [
      {
        title: "Reflejos en el lago",
        pose: "Sentado o de pie junto al lago, mirando el reflejo del agua.",
        camera_angle: "Cámara baja cerca del agua para capturar el reflejo.",
        best_time: "Mañana (7-9am) con agua en calma y luz dorada.",
        clothing: "Ropa clara, tonos pastel que armonicen con el paisaje.",
        instagram_score: 8,
        camera_tip: "Usar el agua como espejo, simetría perfecta.",
        format: "Horizontal",
      },
      {
        title: "Arquitectura de Niemeyer",
        pose: "Caminando hacia el pabellón Niemeyer, figura pequeña contra la estructura.",
        camera_angle: "Cámara a media altura, gran angular para capturar las curvas.",
        best_time: "Tarde (16-18h) con sombras largas que resaltan las formas.",
        clothing: "Outfit minimalista, blanco o negro.",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x para líneas arquitectónicas.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Av. Pedro Álvares Cabral - Vila Mariana, São Paulo - SP",
    lat: -23.5874,
    lng: -46.6576,
    search_query: "Parque Ibirapuera São Paulo",
    emoji: "🌳",
  },
  {
    name: "Farol Santander",
    name_en: "Santander Lighthouse",
    type: "visit",
    category: "viewpoint",
    description:
      "Mirador en lo alto del Edifício Altino Arantes (Banespa) a 160 m. Vistas 360° de la ciudad, incluida la cúpula del Theatro Municipal. Acceso gratuito con reserva.",
    viral_trend: "Vista 360 de São Paulo desde el mirador",
    photo_concepts: [
      {
        title: "Vista 360 de la ciudad",
        pose: "De espaldas a la ventana, mirando el horizonte de la ciudad.",
        camera_angle: "Cámara a la altura de los ojos, gran angular para abarcar el panorama.",
        best_time: "Atardecer (17-18h) para luces doradas sobre la ciudad.",
        clothing: "Ropa elegante, tonos oscuros para contrastar con el cielo.",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x y evitar reflejos en el cristal.",
        format: "Vertical 9:16",
      },
      {
        title: "Cúpula del Theatro Municipal",
        pose: "A un lado del mirador, apuntando hacia la cúpula visible.",
        camera_angle: "Cámara a media altura, zoom 2x para detalle de la cúpula.",
        best_time: "Mañana con cielo despejado.",
        clothing: "Outfit urbano, tonos neutros.",
        instagram_score: 7,
        camera_tip: "Zoom 2x para aislar la cúpula del fondo.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 2,
    best_time: "Atardecer",
    address: "R. João Brícola, 24 - Centro Histórico, São Paulo - SP",
    lat: -23.5473,
    lng: -46.6373,
    search_query: "Farol Santander Banespa mirador São Paulo",
    emoji: "🗼",
  },
  {
    name: "Terraço Itália",
    name_en: "Terraço Itália",
    type: "visit",
    category: "viewpoint",
    description:
      "Restaurante y mirador en el piso 45 del Edifício Itália, a 168 m. Una de las mejores vistas panorámicas del centro de São Paulo, especialmente al atardecer.",
    viral_trend: "Atardecer panorámico desde el piso 45",
    photo_concepts: [
      {
        title: "Atardecer panorámico",
        pose: "De pie junto al ventanal, silueta contra el atardecer.",
        camera_angle: "Cámara a la altura de los ojos, contrapicado ligero.",
        best_time: "Atardecer (18-19h) para la golden hour.",
        clothing: "Ropa elegante de noche, tonos oscuros.",
        instagram_score: 9,
        camera_tip: "Silueta contra el cielo, exposición baja para el cielo.",
        format: "Vertical 9:16",
      },
      {
        title: "Skyline nocturno",
        pose: "Sentado junto al ventanal con una copa, mirando la ciudad.",
        camera_angle: "Cámara a media altura, plano medio.",
        best_time: "Noche (20-22h) con luces de la ciudad encendidas.",
        clothing: "Outfit elegante, vestido o camisa oscura.",
        instagram_score: 8,
        camera_tip: "Modo noche para reducir ruido en poca luz.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Atardecer",
    address: "Av. Ipiranga, 344 - 45º andar - República, São Paulo - SP",
    lat: -23.5449,
    lng: -46.6477,
    search_query: "Terraço Itália mirador Edifício Itália São Paulo",
    emoji: "🌆",
  },
  {
    name: "Edifício Copan",
    name_en: "Copan Building",
    type: "free",
    category: "landmark",
    description:
      "Rascacielos ondulado diseñado por Oscar Niemeyer en el centro histórico, con 1.160 apartamentos y su icónica fachada curva. Símbolo modernista de la ciudad.",
    viral_trend: "Fachada ondulada de Niemeyer desde la calle",
    photo_concepts: [
      {
        title: "Fachada ondulada",
        pose: "De pie frente al edificio, mirando hacia arriba, figura pequeña.",
        camera_angle: "Cámara baja en el suelo, contrapicado extremo.",
        best_time: "Mañana (8-10am) con luz lateral que resalta las curvas.",
        clothing: "Ropa minimalista para no competir con la arquitectura.",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x para capturar toda la curva.",
        format: "Vertical 9:16",
      },
      {
        title: "Detalle de las ondas",
        pose: "Caminando junto a la fachada, mano tocando la pared.",
        camera_angle: "Cámara a media altura, plano medio, paralelo a la fachada.",
        best_time: "Tarde (16-18h) con sombras que resaltan las líneas.",
        clothing: "Outfit urbano, tonos tierra.",
        instagram_score: 7,
        camera_tip: "Zoom 2x para detalle de la textura ondulada.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Av. São Luís, 23 - República, São Paulo - SP",
    lat: -23.5466,
    lng: -46.6428,
    search_query: "Edifício Copan Niemeyer São Paulo",
    emoji: "🏢",
  },
  {
    name: "Theatro Municipal de São Paulo",
    name_en: "São Paulo Municipal Theatre",
    type: "visit",
    category: "landmark",
    description:
      "Teatro lírico inaugurado en 1911 con inspiración en la Ópera de París. Interior lujoso, escalinatas de mármol y cúpula de vidrio. Escenario de la Semana de Arte Moderna de 1922.",
    viral_trend: "Escaleras de mármol + cúpula de vidrio",
    photo_concepts: [
      {
        title: "Escaleras de mármol",
        pose: "Bajando las escaleras de mármol con elegancia, mano en la baranda.",
        camera_angle: "Cámara a media altura, picado ligero desde arriba.",
        best_time: "Mañana (10-12h) con luz natural del vestíbulo.",
        clothing: "Vestido elegante o traje, tonos claros.",
        instagram_score: 9,
        camera_tip: "Modo retrato para separar la figura del fondo.",
        format: "Vertical 4:5",
      },
      {
        title: "Cúpula de vidrio",
        pose: "Acostado en el suelo mirando hacia la cúpula, brazos abiertos.",
        camera_angle: "Cámara en el suelo apuntando al techo, gran angular.",
        best_time: "Mediodía con luz cenital entrando por la cúpula.",
        clothing: "Ropa elegante, colores que contrasten con el vidrio.",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x para capturar toda la cúpula.",
        format: "Vertical 9:16",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Mañana",
    address: "Praça Ramos de Azevedo, s/n - República, São Paulo - SP",
    lat: -23.5452,
    lng: -46.6393,
    search_query: "Theatro Municipal São Paulo",
    emoji: "🎭",
  },
  {
    name: "Mercado Municipal de São Paulo",
    name_en: "Municipal Market of São Paulo",
    type: "meal",
    category: "food",
    description:
      "Mercado histórico con vitrales y arquitectura de inspiración europea. Famoso por el sándwich de mortadela y los pasteis de bacalao. Paraíso gastronómico en el centro.",
    viral_trend: "Sándwich de mortadela gigante + vitrales",
    photo_concepts: [
      {
        title: "Sándwich de mortadela",
        pose: "Sosteniendo el sándwich de mortadela con dos manos, primer plano.",
        camera_angle: "Cámara a la altura de los ojos, plano medio desde arriba.",
        best_time: "Mediodía (12-14h) con luz natural de los vitrales.",
        clothing: "Outfit casual, delantal o ropa de mercado.",
        instagram_score: 8,
        camera_tip: "Modo retrato para desenfocar el fondo del mercado.",
        format: "Vertical 4:5",
      },
      {
        title: "Vitrales del mercado",
        pose: "Caminando bajo los vitrales, mirando hacia arriba.",
        camera_angle: "Cámara baja, contrapicado para capturar los vitrales.",
        best_time: "Mañana (9-11am) con luz entrando por los vitrales.",
        clothing: "Ropa colorida que combine con los vitrales.",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x para abarcar los vitrales.",
        format: "Vertical 9:16",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mediodía",
    address: "R. da Cantareira, 306 - Centro Histórico, São Paulo - SP",
    lat: -23.5418,
    lng: -46.6294,
    search_query: "Mercado Municipal São Paulo mortadela",
    emoji: "🥪",
  },
  {
    name: "Escadaria do Patápio",
    name_en: "Patápio Staircase",
    type: "free",
    category: "street-art",
    description:
      "Escalera colorida de Vila Madalena decorada con mosaicos y pinturas, conectando la Rua Harmonia con el Beco do Batman. Cada escalón es una obra de arte colectiva.",
    viral_trend: "Escaleras de mosaico colorido",
    photo_concepts: [
      {
        title: "Sentado en las escaleras",
        pose: "Sentado en un escalón, una pierna extendida, mirando a la cámara.",
        camera_angle: "Cámara a media altura, ligeramente desde arriba.",
        best_time: "Mañana (8-10am) con luz suave y menos gente.",
        clothing: "Ropa colorida que combine con los mosaicos.",
        instagram_score: 8,
        camera_tip: "Modo retrato para separar la figura de los mosaicos.",
        format: "Vertical 4:5",
      },
      {
        title: "Perspectiva de las escaleras",
        pose: "Caminando bajando las escaleras, de espaldas al fotógrafo.",
        camera_angle: "Cámara alta, picado para mostrar la extensión de las escaleras.",
        best_time: "Tarde (16-18h) con sombras que resaltan los mosaicos.",
        clothing: "Outfit casual, tonos neutros para contrastar.",
        instagram_score: 7,
        camera_tip: "Gran angular 0.5x para capturar toda la escalera.",
        format: "Vertical 9:16",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Escadaria do Patápio - Vila Madalena, São Paulo - SP",
    lat: -23.5538,
    lng: -46.6908,
    search_query: "Escadaria do Patápio Vila Madalena São Paulo",
    emoji: "🪜",
  },
  {
    name: "Anjo da Vila Madalena",
    name_en: "Angel of Vila Madalena",
    type: "free",
    category: "street-art",
    description:
      "Mural de un ángel de grandes alas pintado por Thiago Versonato en Vila Madalena. Las alas sirven de telón de fondo para fotos: el spot 'alas de ángel' más viral de São Paulo.",
    viral_trend: "Alas de ángel para fotos",
    photo_concepts: [
      {
        title: "Alas de ángel",
        pose: "De pie frente al mural, brazos ligeramente abiertos como alas.",
        camera_angle: "Cámara a media altura, centrada para alinear las alas.",
        best_time: "Mañana (8-10am) con luz uniforme y menos gente.",
        clothing: "Ropa blanca o clara para contrastar con las alas coloridas.",
        instagram_score: 9,
        camera_tip: "Alinear hombros con las alas del mural.",
        format: "Vertical 4:5",
      },
      {
        title: "Detalle del mural",
        pose: "De perfil junto al mural, mano tocando las alas.",
        camera_angle: "Cámara a media altura, plano medio, paralelo al mural.",
        best_time: "Tarde (16-18h) con luz lateral.",
        clothing: "Outfit bohemio, tonos tierra.",
        instagram_score: 7,
        camera_tip: "Zoom 2x para detalle de las alas.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana",
    address: "R. Gonçalo Afonso - Vila Madalena, São Paulo - SP",
    lat: -23.5543,
    lng: -46.6904,
    search_query: "Anjo da Vila Madalena mural alas São Paulo",
    emoji: "😇",
  },
  {
    name: "Japan House São Paulo",
    name_en: "Japan House São Paulo",
    type: "visit",
    category: "museum",
    description:
      "Centro cultural japonés en la Avenida Paulista con exposiciones itinerantes, gastronomía, diseño y tecnología. Una ventana a la cultura japonesa en el corazón de São Paulo.",
    viral_trend: "Exposiciones inmersivas + diseño japonés",
    photo_concepts: [
      {
        title: "Exposición inmersiva",
        pose: "Interactuando con una exposición, expresión de asombro.",
        camera_angle: "Cámara a la altura de los ojos, plano medio.",
        best_time: "Mañana (10-12h) con luz controlada del interior.",
        clothing: "Outfit minimalista japonés, tonos neutros.",
        instagram_score: 8,
        camera_tip: "Modo retrato para separar la figura de la exposición.",
        format: "Vertical 4:5",
      },
      {
        title: "Diseño japonés",
        pose: "Sentado en un banco de diseño japonés, postura relajada.",
        camera_angle: "Cámara baja, ligeramente contrapicado.",
        best_time: "Tarde (14-16h) con luz suave del interior.",
        clothing: "Ropa elegante, líneas limpias.",
        instagram_score: 7,
        camera_tip: "Simetría y líneas rectas, estética japonesa.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Av. Paulista, 52 - Bela Vista, São Paulo - SP",
    lat: -23.5626,
    lng: -46.6548,
    search_query: "Japan House São Paulo Avenida Paulista",
    emoji: "🇯🇵",
  },
  {
    name: "Catedral Metropolitana da Sé",
    name_en: "Sé Cathedral",
    type: "free",
    category: "landmark",
    description:
      "Catedral neogótica en el corazón histórico de São Paulo, con cripta y vitrales coloridos. Símbolo de la ciudad frente a la Praça da Sé, punto cero de sus carreteras.",
    viral_trend: "Vitrales góticos + plaza del marco cero",
    photo_concepts: [
      {
        title: "Fachada de la catedral",
        pose: "De pie frente a la catedral, brazos abiertos, mirando hacia arriba.",
        camera_angle: "Cámara baja, contrapicado para capturar toda la fachada.",
        best_time: "Mañana (8-10am) con luz frontal.",
        clothing: "Ropa elegante, tonos oscuros para contrastar.",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x para abarcar toda la catedral.",
        format: "Vertical 9:16",
      },
      {
        title: "Vitrales góticos",
        pose: "Acostado en el suelo mirando los vitrales, brazos abiertos.",
        camera_angle: "Cámara en el suelo apuntando al techo, gran angular.",
        best_time: "Mediodía con luz cenital entrando por los vitrales.",
        clothing: "Ropa clara que combine con los colores de los vitrales.",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x y exposición baja para los colores.",
        format: "Vertical 9:16",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Praça da Sé, s/n - Centro Histórico, São Paulo - SP",
    lat: -23.5532,
    lng: -46.6332,
    search_query: "Catedral da Sé São Paulo",
    emoji: "⛪",
  },
  {
    name: "Mirante Sesc Paulista",
    name_en: "Sesc Paulista Observatory",
    type: "visit",
    category: "viewpoint",
    description:
      "Mirador en el piso 26 del Sesc Paulista con vista abierta hacia la Avenida Paulista y el skyline. Acceso accesible con programación cultural y restaurante.",
    viral_trend: "Vista de la Avenida Paulista desde arriba",
    photo_concepts: [
      {
        title: "Vista de la Paulista",
        pose: "De espaldas al ventanal, mirando la Avenida Paulista.",
        camera_angle: "Cámara a la altura de los ojos, gran angular.",
        best_time: "Atardecer (17-18h) para luces doradas.",
        clothing: "Ropa urbana elegante, tonos oscuros.",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x para abarcar toda la avenida.",
        format: "Vertical 9:16",
      },
      {
        title: "Skyline nocturno",
        pose: "Sentado junto al ventanal, mirando las luces de la ciudad.",
        camera_angle: "Cámara a media altura, plano medio.",
        best_time: "Noche (19-21h) con luces encendidas.",
        clothing: "Outfit elegante de noche.",
        instagram_score: 7,
        camera_tip: "Modo noche para reducir ruido.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 2,
    best_time: "Atardecer",
    address: "Av. Paulista, 119 - Bela Vista, São Paulo - SP",
    lat: -23.5631,
    lng: -46.6541,
    search_query: "Mirante Sesc Paulista observatorio",
    emoji: "🔭",
  },
  {
    name: "Instituto Moreira Salles - São Paulo",
    name_en: "Moreira Salles Institute - São Paulo",
    type: "visit",
    category: "museum",
    description:
      "Centro cultural en la Avenida Paulista con fotografía, cine, literatura y música. Entrada gratuita, café y una de las bibliotecas más bonitas de la ciudad para fotografiar.",
    viral_trend: "Biblioteca y exposiciones de fotografía",
    photo_concepts: [
      {
        title: "Biblioteca fotogénica",
        pose: "Caminando entre las estanterías, mano tocando un libro.",
        camera_angle: "Cámara a media altura, plano medio, paralelo a las estanterías.",
        best_time: "Mañana (10-12h) con luz natural.",
        clothing: "Outfit intelectual, tonos neutros.",
        instagram_score: 8,
        camera_tip: "Modo retrato para desenfocar el fondo de libros.",
        format: "Vertical 4:5",
      },
      {
        title: "Exposición de fotografía",
        pose: "Observando una foto en la exposición, perfil.",
        camera_angle: "Cámara a la altura de los ojos, plano medio.",
        best_time: "Tarde (14-16h) con luz controlada.",
        clothing: "Ropa elegante, tonos oscuros.",
        instagram_score: 7,
        camera_tip: "Evitar reflejos en los cristales de las fotos.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Av. Paulista, 2424 - Jardim Paulista, São Paulo - SP",
    lat: -23.5696,
    lng: -46.6679,
    search_query: "Instituto Moreira Salles IMS Paulista",
    emoji: "📚",
  },
  {
    name: "Pinacoteca de São Paulo",
    name_en: "São Paulo Art Gallery",
    type: "visit",
    category: "museum",
    description:
      "El museo de arte más antiguo de São Paulo (1905), en un edificio neoclásico reformado. Colección destacada de arte brasileño del siglo XIX y XX, con patio de vidrio muy fotogénico.",
    viral_trend: "Patio de vidrio + arte brasileño",
    photo_concepts: [
      {
        title: "Patio de vidrio",
        pose: "Caminando por el patio de vidrio, mirando hacia arriba.",
        camera_angle: "Cámara baja, contrapicado para capturar el techo de vidrio.",
        best_time: "Mañana (10-12h) con luz cenital.",
        clothing: "Ropa elegante, tonos claros.",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x para abarcar el patio.",
        format: "Vertical 9:16",
      },
      {
        title: "Arte brasileño",
        pose: "Observando una obra, expresión contemplativa.",
        camera_angle: "Cámara a la altura de los ojos, plano medio.",
        best_time: "Tarde (14-16h) con luz suave.",
        clothing: "Outfit artístico, tonos tierra.",
        instagram_score: 7,
        camera_tip: "Modo retrato para separar la figura del cuadro.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Praça da Luz, 2 - Bom Retiro, São Paulo - SP",
    lat: -23.534,
    lng: -46.6336,
    search_query: "Pinacoteca de São Paulo Praça da Luz",
    emoji: "🏛️",
  },
  {
    name: "Estação da Luz",
    name_en: "Luz Station",
    type: "free",
    category: "landmark",
    description:
      "Estación de tren de estilo victoriano inaugurada en 1901, con torre de reloj inspirada en la Big Ben. Sede del Museu da Língua Portuguesa y punto histórico del centro.",
    viral_trend: "Arquitectura victoriana + torre del reloj",
    photo_concepts: [
      {
        title: "Fachada victoriana",
        pose: "De pie frente a la estación, mirando hacia arriba.",
        camera_angle: "Cámara baja, contrapicado para capturar la fachada y torre.",
        best_time: "Mañana (8-10am) con luz frontal.",
        clothing: "Ropa elegante vintage, tonos sepia o tierra.",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x para abarcar toda la fachada.",
        format: "Vertical 9:16",
      },
      {
        title: "Torre del reloj",
        pose: "Caminando bajo la torre del reloj, figura pequeña.",
        camera_angle: "Cámara baja, contrapicado extremo hacia la torre.",
        best_time: "Tarde (16-18h) con luz dorada.",
        clothing: "Outfit urbano, tonos neutros.",
        instagram_score: 7,
        camera_tip: "Zoom 2x para detalle de la torre.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Praça da Luz, 1 - Bom Retiro, São Paulo - SP",
    lat: -23.5354,
    lng: -46.6333,
    search_query: "Estação da Luz São Paulo",
    emoji: "🚉",
  },
  {
    name: "Parque da Luz",
    name_en: "Luz Park",
    type: "free",
    category: "park",
    description:
      "Jardín histórico del siglo XIX frente a la Estação da Luz, con esculturas, fuentes y árboles centenarios. Espacio tranquilo y museo al aire libre en pleno centro.",
    viral_trend: "Esculturas + jardín histórico",
    photo_concepts: [
      {
        title: "Esculturas del jardín",
        pose: "Junto a una escultura, mano apoyada, mirada pensativa.",
        camera_angle: "Cámara a media altura, plano medio.",
        best_time: "Mañana (8-10am) con luz suave.",
        clothing: "Ropa elegante, tonos naturales.",
        instagram_score: 7,
        camera_tip: "Modo retrato para separar la figura de la escultura.",
        format: "Vertical 4:5",
      },
      {
        title: "Senderos del parque",
        pose: "Caminando por un sendero entre árboles centenarios.",
        camera_angle: "Cámara baja, gran angular para capturar el sendero.",
        best_time: "Tarde (16-18h) con luz dorada filtrando entre árboles.",
        clothing: "Outfit casual, tonos tierra.",
        instagram_score: 7,
        camera_tip: "Gran angular 0.5x para profundidad del sendero.",
        format: "Vertical 9:16",
      },
    ],
    instagram_score: 7,
    difficulty: 1,
    best_time: "Mañana",
    address: "Praça da Luz, s/n - Bom Retiro, São Paulo - SP",
    lat: -23.5351,
    lng: -46.6341,
    search_query: "Parque da Luz São Paulo esculturas",
    emoji: "🌿",
  },
  {
    name: "Praça do Pôr do Sol",
    name_en: "Sunset Square",
    type: "free",
    category: "park",
    description:
      "Plaza elevada en Pinheiros con vista abierta al horizonte, uno de los mejores lugares de São Paulo para ver el atardecer. Ambiente joven con food trucks y música.",
    viral_trend: "Atardecer con vista al horizonte",
    photo_concepts: [
      {
        title: "Atardecer en la plaza",
        pose: "Sentado en el borde de la plaza, piernas colgando, mirando el atardecer.",
        camera_angle: "Cámara a media altura, contrapicado ligero.",
        best_time: "Atardecer (18-19h) para la golden hour.",
        clothing: "Outfit casual, tonos cálidos que combinen con el atardecer.",
        instagram_score: 9,
        camera_tip: "Silueta contra el cielo, exposición baja.",
        format: "Vertical 9:16",
      },
      {
        title: "Food trucks y ambiente",
        pose: "Con una bebida junto a un food truck, sonriendo.",
        camera_angle: "Cámara a la altura de los ojos, plano medio.",
        best_time: "Tarde (17-19h) con ambiente previo al atardecer.",
        clothing: "Ropa casual joven, colores vivos.",
        instagram_score: 7,
        camera_tip: "Modo retrato para desenfocar el fondo.",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer",
    address: "R. Des. Eliseu Guilherme, 200 - Pinheiros, São Paulo - SP",
    lat: -23.5679,
    lng: -46.6964,
    search_query: "Praça do Pôr do Sol Pinheiros São Paulo",
    emoji: "🌇",
  },
  {
    name: "Rua Augusta",
    name_en: "Augusta Street",
    type: "free",
    category: "nightlife",
    description:
      "Calle bohemia que conecta el centro con los Jardins, epicentro de la vida nocturna paulistana. Bares, clubes, tiendas alternativas y ambiente LGBTQIA+ vibrante hasta el amanecer.",
    viral_trend: "Nocturna + neón + ambiente bohemio",
    photo_concepts: [
      {
        title: "Neón nocturno",
        pose: "De pie bajo un letrero de neón, mirada directa a la cámara.",
        camera_angle: "Cámara a la altura de los ojos, plano medio.",
        best_time: "Noche (22-2h) con neones encendidos.",
        clothing: "Outfit nocturno vibrante, colores neón o brillantes.",
        instagram_score: 9,
        camera_tip: "Modo noche y usar el neón como luz principal.",
        format: "Vertical 4:5",
      },
      {
        title: "Ambiente bohemio",
        pose: "Caminando por la calle, riendo, movimiento natural.",
        camera_angle: "Cámara a media altura, plano americano en movimiento.",
        best_time: "Noche (23-1h) con ambiente callejero activo.",
        clothing: "Ropa bohemia, capas y accesorios.",
        instagram_score: 8,
        camera_tip: "Modo ráfaga para capturar el momento espontáneo.",
        format: "Vertical 9:16",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Noche",
    address: "R. Augusta - Consolação, São Paulo - SP",
    lat: -23.5576,
    lng: -46.6643,
    search_query: "Rua Augusta nightlife São Paulo",
    emoji: "🌃",
  },
];
