// Spots trending/instagramables curados del Sur de Brasil.
// Florianópolis, Balneário Camboriú, y Serra Gaúcha (Gramado/Canela).

export type CuratedSpot = {
  name: string;
  name_en?: string;
  type: "visit" | "tour" | "meal" | "event" | "free" | "transport";
  category:
    | "landmark"
    | "viewpoint"
    | "beach"
    | "hiking"
    | "street-art"
    | "stadium"
    | "museum"
    | "park"
    | "nightlife"
    | "food";
  description: string;
  viral_trend?: string;
  address: string;
  lat: number;
  lng: number;
  search_query: string;
  emoji: string;
};

export const CURATED_SPOTS_FLORIANOPOLIS: CuratedSpot[] = [
  {
    name: "Ponte Hercílio Luz",
    name_en: "Hercílio Luz Bridge",
    type: "visit",
    category: "landmark",
    description: "El puente más icónico de Florianópolis, símbolo de la ciudad. Perfecto al atardecer.",
    viral_trend: "Silueta al atardecer con el puente iluminado",
    address: "Centro, Florianópolis - SC",
    lat: -27.5945,
    lng: -48.5477,
    search_query: "Ponte Hercílio Luz Florianópolis",
    emoji: "🌉",
  },
  {
    name: "Santo Antônio de Lisboa",
    type: "visit",
    category: "landmark",
    description: "Barrio colonial azorés con calles adoquinadas y casas coloridas frente al mar.",
    viral_trend: "Calles coloniales con barcos al atardecer",
    address: "Santo Antônio de Lisboa, Florianópolis - SC",
    lat: -27.5283,
    lng: -48.5233,
    search_query: "Santo Antônio de Lisboa Florianópolis",
    emoji: "🏘️",
  },
  {
    name: "Ilha do Campeche",
    name_en: "Campeche Island",
    type: "tour",
    category: "beach",
    description: "La 'Caribe brasileño' — agua turquesa cristalina y arena blanca. Acceso limitado por barco.",
    viral_trend: "Agua turquesa estilo Caribe desde arriba",
    address: "Praia do Campeche, Florianópolis - SC",
    lat: -27.6828,
    lng: -48.4789,
    search_query: "Ilha do Campeche Florianópolis",
    emoji: "🏝️",
  },
  {
    name: "Praia Mole",
    type: "free",
    category: "beach",
    description: "Playa joven y trendy, surf y parapente. La playa 'see and be seen' de Floripa.",
    viral_trend: "Parapentistas sobre la playa con morro de fondo",
    address: "Praia Mole, Florianópolis - SC",
    lat: -27.6406,
    lng: -48.4494,
    search_query: "Praia Mole Florianópolis",
    emoji: "🏄",
  },
  {
    name: "Dunas da Joaquina",
    name_en: "Joaquina Sand Dunes",
    type: "free",
    category: "beach",
    description: "Dunas masivas junto a playa famosa de surf. Desierto se encuentra océano.",
    viral_trend: "Sandboard y saltos en las dunas",
    address: "Praia da Joaquina, Florianópolis - SC",
    lat: -27.6289,
    lng: -48.4456,
    search_query: "Dunas da Joaquina Florianópolis",
    emoji: "🏜️",
  },
  {
    name: "Mirante da Lagoa da Conceição",
    type: "visit",
    category: "viewpoint",
    description: "Mirador panorámico de la laguna, dunas y océano en un solo cuadro.",
    viral_trend: "Panorámica de laguna + dunas + océano",
    address: "SC-404, Lagoa da Conceição, Florianópolis - SC",
    lat: -27.5828,
    lng: -48.4506,
    search_query: "Mirante da Lagoa da Conceição Florianópolis",
    emoji: "⛰️",
  },
  {
    name: "Jurerê Internacional",
    type: "free",
    category: "beach",
    description: "El 'Miami brasileño' — beach clubs de lujo, yates y mansiones.",
    viral_trend: "Beach club cabana con champagne",
    address: "Jurerê Internacional, Florianópolis - SC",
    lat: -27.4389,
    lng: -48.5039,
    search_query: "Jurerê Internacional Florianópolis",
    emoji: "🛥️",
  },
  {
    name: "Lagoinha do Leste",
    type: "tour",
    category: "hiking",
    description: "Playa salvaje accesible solo por sendero de 45 min. La 'pedra do surfista' es viral.",
    viral_trend: "Foto en el borde del acantilado con playa abajo",
    address: "Lagoinha do Leste, Florianópolis - SC",
    lat: -27.7689,
    lng: -48.5039,
    search_query: "Lagoinha do Leste Florianópolis",
    emoji: "🥾",
  },
  {
    name: "Praia da Joaquina",
    type: "free",
    category: "beach",
    description: "Playa famosa mundialmente por el surf, con dunas adyacentes.",
    address: "Praia da Joaquina, Florianópolis - SC",
    lat: -27.6289,
    lng: -48.4456,
    search_query: "Praia da Joaquina Florianópolis",
    emoji: "🏄‍♀️",
  },
  {
    name: "Mercado Público",
    type: "meal",
    category: "food",
    description: "Mercado histórico con restaurantes de mariscos frescos y ambiente animado.",
    address: "Rua dos Açorianos, Centro, Florianópolis - SC",
    lat: -27.5945,
    lng: -48.5528,
    search_query: "Mercado Público Florianópolis",
    emoji: "🦐",
  },
  {
    name: "Lagoa da Conceição",
    type: "free",
    category: "park",
    description: "Laguna rodeada de colinas verdes, centro de la vida bohemia de Floripa.",
    address: "Lagoa da Conceição, Florianópolis - SC",
    lat: -27.5828,
    lng: -48.4506,
    search_query: "Lagoa da Conceição Florianópolis",
    emoji: "🛶",
  },
  {
    name: "Praia do Moçambique",
    type: "free",
    category: "beach",
    description: "Playa larga y salvaje dentro del Parque Natural, ideal para surf y naturaleza.",
    address: "Praia do Moçambique, Florianópolis - SC",
    lat: -27.5189,
    lng: -48.3889,
    search_query: "Praia do Moçambique Florianópolis",
    emoji: "🌊",
  },
  {
    name: "Ribeirão da Ilha",
    type: "meal",
    category: "food",
    description: "Pueblo de pescadores con restaurantes de ostras, vista a la bahía.",
    address: "Ribeirão da Ilha, Florianópolis - SC",
    lat: -27.5189,
    lng: -48.5233,
    search_query: "Ribeirão da Ilha Florianópolis",
    emoji: "🦪",
  },
  {
    name: "Praia do Campeche",
    type: "free",
    category: "beach",
    description: "Playa con vista a la Ilha do Campeche, arena blanca y agua clara.",
    address: "Praia do Campeche, Florianópolis - SC",
    lat: -27.6828,
    lng: -48.4789,
    search_query: "Praia do Campeche Florianópolis",
    emoji: "🏖️",
  },
  {
    name: "Praia do Forte",
    type: "visit",
    category: "landmark",
    description: "Fuerte histórico con vista panorámica de la bahía y el puente.",
    address: "Praia do Forte, Florianópolis - SC",
    lat: -27.6039,
    lng: -48.5778,
    search_query: "Forte de Santa Cruz de Anhatomirim Florianópolis",
    emoji: "🏰",
  },
];

export const CURATED_SPOTS_BALNEARIO: CuratedSpot[] = [
  {
    name: "FG Big Wheel",
    name_en: "FG Big Wheel",
    type: "visit",
    category: "viewpoint",
    description: "Rueda de observación de 65m dentro de una reserva natural. Vistas 360° únicas.",
    viral_trend: "Panorámica de skyline + bosque + océano desde la cabina",
    address: "Alameda César Nascimento, Balneário Camboriú - SC",
    lat: -26.9939,
    lng: -48.6239,
    search_query: "FG Big Wheel Balneário Camboriú",
    emoji: "🎡",
  },
  {
    name: "Estrada da Rainha",
    name_en: "Queen's Road",
    type: "visit",
    category: "viewpoint",
    description: "Camino escénico con vista al skyline de BC, el 'Dubai brasileño'. Mural de girasoles.",
    viral_trend: "Skyline + mural de girasoles",
    address: "Estrada da Rainha, Balneário Camboriú - SC",
    lat: -26.9889,
    lng: -48.6339,
    search_query: "Estrada da Rainha Balneário Camboriú",
    emoji: "🌻",
  },
  {
    name: "Praia das Laranjeiras",
    type: "free",
    category: "beach",
    description: "La playa más fotografiada de Brasil en Google Maps. Parada del teleférico Unipraias.",
    address: "Praia das Laranjeiras, Balneário Camboriú - SC",
    lat: -26.9789,
    lng: -48.6039,
    search_query: "Praia das Laranjeiras Balneário Camboriú",
    emoji: "🏖️",
  },
  {
    name: "Passarela da Barra",
    type: "free",
    category: "viewpoint",
    description: "Mirador emblemático con vista a la costa, barcos y luces de la ciudad al atardecer.",
    address: "Passarela da Barra, Balneário Camboriú - SC",
    lat: -26.9639,
    lng: -48.6439,
    search_query: "Passarela da Barra Balneário Camboriú",
    emoji: "🌅",
  },
  {
    name: "Praia Central",
    type: "free",
    category: "beach",
    description: "Playa urbana con skyline de rascacielos de fondo, la más concurrida de BC.",
    address: "Av. Atlântica, Balneário Camboriú - SC",
    lat: -26.9889,
    lng: -48.6339,
    search_query: "Praia Central Balneário Camboriú",
    emoji: "🏙️",
  },
  {
    name: "Unipraias Parque",
    type: "tour",
    category: "landmark",
    description: "Teleférico que conecta la playa con la montaña, vistas espectaculares del litoral.",
    address: "Av. Atlântica, 5250, Balneário Camboriú - SC",
    lat: -26.9789,
    lng: -48.6039,
    search_query: "Unipraias Parque Teleférico Balneário Camboriú",
    emoji: "🚡",
  },
  {
    name: "Cristo Luz",
    type: "visit",
    category: "landmark",
    description: "Estatua de Cristo con vista panorámica de la ciudad, similar al Corcovado.",
    address: "Morro da Cruz, Balneário Camboriú - SC",
    lat: -26.9689,
    lng: -48.6539,
    search_query: "Cristo Luz Balneário Camboriú",
    emoji: "✝️",
  },
  {
    name: "Praia dos Amores",
    type: "free",
    category: "beach",
    description: "Playa preservada entre rocas, accesible por sendero desde Estrada da Rainha.",
    address: "Praia dos Amores, Balneário Camboriú - SC",
    lat: -26.9839,
    lng: -48.6139,
    search_query: "Praia dos Amores Balneário Camboriú",
    emoji: "💕",
  },
];

export const CURATED_SPOTS_SERRA_GAUCHA: CuratedSpot[] = [
  {
    name: "Rua Coberta",
    name_en: "Covered Street",
    type: "visit",
    category: "landmark",
    description: "Calle peatonal cubierta con dosel transparente, cafés y plantas colgantes. Corazón de Gramado.",
    viral_trend: "Corredor cubierto con plantas y luz cálida",
    address: "Rua Coberta, Gramado - RS",
    lat: -29.3789,
    lng: -50.8739,
    search_query: "Rua Coberta Gramado",
    emoji: "🌿",
  },
  {
    name: "Lago Negro",
    name_en: "Black Lake",
    type: "free",
    category: "park",
    description: "Lago rodeado de pinos negros con barcos cisé. Paisaje alpino europeo en Brasil.",
    viral_trend: "Barcos cisé + reflejos en el agua oscura",
    address: "Lago Negro, Gramado - RS",
    lat: -29.3689,
    lng: -50.8639,
    search_query: "Lago Negro Gramado",
    emoji: "🦢",
  },
  {
    name: "Catedral de Pedra",
    name_en: "Stone Cathedral",
    type: "visit",
    category: "landmark",
    description: "Catedral gótica de piedra, una de las 7 maravillas de Brasil. Espectacular de noche.",
    viral_trend: "Fachada iluminada de noche (blue hour)",
    address: "Av. João Cordeiro, Canela - RS",
    lat: -29.3589,
    lng: -50.8239,
    search_query: "Catedral de Pedra Canela",
    emoji: "⛪",
  },
  {
    name: "Cascata do Caracol",
    name_en: "Caracol Waterfall",
    type: "tour",
    category: "park",
    description: "Cascada de 131m en parque con senderos y teleférico. Una de las más famosas de Brasil.",
    viral_trend: "Cascada desde el teleférico (perspectiva aérea)",
    address: "Parque do Caracol, Canela - RS",
    lat: -29.3189,
    lng: -50.8239,
    search_query: "Cascata do Caracol Canela",
    emoji: "💦",
  },
  {
    name: "Mini Mundo",
    name_en: "Mini World",
    type: "tour",
    category: "landmark",
    description: "Parque con réplicas en miniatura de castillos y ciudades europeas.",
    address: "Rua Horácio Cardoso, Gramado - RS",
    lat: -29.3789,
    lng: -50.8739,
    search_query: "Mini Mundo Gramado",
    emoji: "🏰",
  },
  {
    name: "Snowland",
    type: "tour",
    category: "landmark",
    description: "Centro de nieve indoor, único en Brasil. Ski y snowboard todo el año.",
    address: "RS-235, Gramado - RS",
    lat: -29.3989,
    lng: -50.8539,
    search_query: "Snowland Gramado",
    emoji: "❄️",
  },
  {
    name: "Parque do Caracol",
    type: "tour",
    category: "park",
    description: "Parque con senderos, miradores y la famosa Cascata do Caracol.",
    address: "Parque do Caracol, Canela - RS",
    lat: -29.3189,
    lng: -50.8239,
    search_query: "Parque do Caracol Canela",
    emoji: "🌲",
  },
  {
    name: "Vinícola Aurora",
    type: "tour",
    category: "food",
    description: "Bodega histórica con tours de degustación en el corazón de Bento Gonçalves.",
    address: "Av. São Vito, Bento Gonçalves - RS",
    lat: -29.1689,
    lng: -51.5139,
    search_query: "Vinícola Aurora Bento Gonçalves",
    emoji: "🍷",
  },
  {
    name: "Vale dos Vinhedos",
    name_en: "Valley of Vineyards",
    type: "tour",
    category: "food",
    description: "Valle de viñedos con bodegas, paisajes y degustaciones. Ruta del vino brasileño.",
    address: "Vale dos Vinhedos, Bento Gonçalves - RS",
    lat: -29.1489,
    lng: -51.4939,
    search_query: "Vale dos Vinhedos Bento Gonçalves",
    emoji: "🍇",
  },
  {
    name: "Maria Fumaça",
    name_en: "Steam Train",
    type: "transport",
    category: "landmark",
    description: "Tren a vapor histórico que recorre Carlos Barbosa, Bento y Garibaldi.",
    viral_trend: "Tren a vapor humeando entre viñedos",
    address: "Estação Ferroviária, Canela - RS",
    lat: -29.3589,
    lng: -50.8239,
    search_query: "Maria Fumaça Canela Bento Gonçalves",
    emoji: "🚂",
  },
];
