// Spots trending/instagramables curados de ciudades de Latinoamérica.
// Solo lugares icónicos que un grupo de amigos querría visitar y fotografiar.
// Las coordenadas son aproximadas y sirven para sesgar búsquedas en Google Places.

import type { CuratedSpot } from "@/lib/photo-types";
export type { CuratedSpot };

export const CURATED_SPOTS_BUENOS_AIRES: CuratedSpot[] = [
  {
    name: "Caminito (La Boca)",
    name_en: "Caminito (La Boca)",
    type: "free",
    category: "street-art",
    description:
      "Callejón museo al aire libre en el barrio de La Boca, famoso por sus casas de chapa pintadas de colores vibrantes y por ser el lugar donde nació el tango. Una de las postales más icónicas de Buenos Aires.",
    viral_trend: "Foto bailando tango en la calle colorida con los artistas callejeros",
    photo_concepts: [
      {
        title: "Tango en la calle colorida",
        pose: "Pareja o amigos cogidos del brazo en pose de tango improvisada, un pie adelantado",
        camera_angle: "Cámara a la altura del pecho, ligeramente baja para incluir las casas de colores",
        best_time: "Mañana temprano (evitar multitudes) o mediodía para colores saturados",
        clothing: "Ropa de colores vibrantes que contrasten con las casas; pañuelo rojo opcional",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para incluir las casas y el cielo",
        format: "Vertical 4:5",
      },
      {
        title: "Silueta contra la pared pintada",
        pose: "De espaldas, un brazo extendido tocando la pared de chapa colorida",
        camera_angle: "Cámara frontal a la altura de la cintura, ligeramente inclinada",
        best_time: "Tarde dorada para luz cálida sobre las chapas",
        clothing: "Outfit monocromo para contrastar con el color del fondo",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana temprano",
    address: "Caminito, La Boca, Buenos Aires",
    lat: -34.6442,
    lng: -58.3719,
    search_query: "Caminito La Boca Buenos Aires",
    emoji: "🎨",
  },
  {
    name: "El Ateneo Grand Splendid",
    name_en: "El Ateneo Grand Splendid",
    type: "visit",
    category: "landmark",
    description:
      "Librería instalada en un antiguo teatro de 1919, considerada una de las más bellas del mundo. Conserva el escenario, las balconadas y la cúpula pintada, con estanterías donde antes estaban los butacas.",
    viral_trend: "Foto sentado en una butaca leyendo con el escenario de fondo",
    photo_concepts: [
      {
        title: "Lectura en el escenario",
        pose: "Sentado en una butaca del patio de butacas, libro abierto, mirada al escenario",
        camera_angle: "Cámara baja a la altura de la butaca, ligeramente hacia arriba para captar la cúpula",
        best_time: "Mañana entre semana para menos gente",
        clothing: "Outfit elegante tipo biblioteca; abrigo o blazer",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para captar la cúpula y los palcos",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana entre semana",
    address: "Av. Santa Fe 1860, Recoleta, Buenos Aires",
    lat: -34.5953,
    lng: -58.4103,
    search_query: "El Ateneo Grand Splendid Buenos Aires",
    emoji: "📚",
  },
  {
    name: "Palacio Barolo",
    name_en: "Barolo Palace",
    type: "tour",
    category: "landmark",
    description:
      "Edificio neogótico de 1923 inspirado en la Divina Comedia de Dante. Su faro en la cima se enciende ocasionalmente y ofrece vistas panorámicas del Congreso y la ciudad.",
    viral_trend: "Foto nocturna con el faro del palacio iluminado",
    photo_concepts: [
      {
        title: "Faro iluminado de noche",
        pose: "De pie en la terraza de la cima, brazos extendidos hacia la ciudad iluminada",
        camera_angle: "Cámara baja contrapicado para captar el faro y el cielo nocturno",
        best_time: "Noche cuando el faro está encendido (consultar agenda)",
        clothing: "Abrigo oscuro; el frío nocturno pide capas",
        instagram_score: 8,
        camera_tip: "Modo Noche del iPhone; trípode si es posible",
        format: "Vertical 4:5",
      },
      {
        title: "Arcadas góticas",
        pose: "Caminando bajo los arcos del interior, mirando hacia la luz del ventanal",
        camera_angle: "Cámara frontal a la altura del hombro, simetría con los arcos",
        best_time: "Tarde con luz lateral por los ventanales",
        clothing: "Outfit elegante con tonos oscuros",
        instagram_score: 8,
        format: "Horizontal",
      },
    ],
    instagram_score: 8,
    difficulty: 2,
    best_time: "Noche (faro encendido)",
    address: "Av. de Mayo 1370, Monserrat, Buenos Aires",
    lat: -34.6097,
    lng: -58.3925,
    search_query: "Palacio Barolo Buenos Aires",
    emoji: "🏛️",
  },
  {
    name: "Galerías Pacífico",
    name_en: "Galerías Pacífico",
    type: "visit",
    category: "landmark",
    description:
      "Centro comercial en un edificio histórico de 1889 con una cúpula pintada al fresco por grandes muralistas argentinos. El patio de comidas y los pasillos son una joya arquitectónica.",
    viral_trend: "Foto bajo la cúpula de frescos mirando hacia arriba",
    photo_concepts: [
      {
        title: "Bajo la cúpula de frescos",
        pose: "Tumbado en el suelo mirando hacia arriba, brazos abiertos en cruz",
        camera_angle: "Cámara apuntando al techo desde el suelo, simetría perfecta",
        best_time: "Mañana para menos gente y luz uniforme",
        clothing: "Cualquiera; el techo es el protagonista",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x; usar nivel de cámara para simetría",
        format: "Cuadrada",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Florida 753, San Nicolás, Buenos Aires",
    lat: -34.6033,
    lng: -58.3756,
    search_query: "Galerías Pacífico Buenos Aires",
    emoji: "🛍️",
  },
  {
    name: "Obelisco",
    name_en: "Obelisk",
    type: "free",
    category: "landmark",
    description:
      "El símbolo de Buenos Aires, un obelisco de 67 metros erigido en 1936 en el cruce de Corrientes y 9 de Julio, la avenida más ancha del mundo. Punto de reunión para celebraciones y protestas.",
    viral_trend: "Foto abrazando el Obelisco desde abajo con perspectiva",
    photo_concepts: [
      {
        title: "Abrazando el Obelisco",
        pose: "Brazos abiertos como abrazando la base del obelisco, cabeza hacia atrás",
        camera_angle: "Cámara en el suelo, contrapicado extremo para captar toda la altura",
        best_time: "Blue hour para cielo azul profundo y luces encendidas",
        clothing: "Outfit urbano; chaqueta oscura",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x; cuidado con la distorsión de la perspectiva",
        format: "Vertical 4:5",
      },
      {
        title: "Obelisco con tráfico nocturno",
        pose: "Sentado en la mediana de Av. 9 de Julio, quieto mientras pasan los autos",
        camera_angle: "Cámara en trípode, exposición larga para estelas de luces",
        best_time: "Noche con tráfico para estelas de faros",
        clothing: "Abrigo oscuro",
        instagram_score: 8,
        camera_tip: "Trípode y modo Noche; exposición larga 2-3s",
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Blue hour",
    address: "Av. Corrientes y Av. 9 de Julio, Buenos Aires",
    lat: -34.6037,
    lng: -58.3817,
    search_query: "Obelisco Buenos Aires",
    emoji: "🗼",
  },
  {
    name: "Casa Rosada",
    name_en: "Pink House",
    type: "visit",
    category: "landmark",
    description:
      "Sede del gobierno argentino, famosa por su fachada rosada y por el balcón desde el que hablaba Evita Perón. Una de las postales más reconocibles de la Plaza de Mayo.",
    viral_trend: "Foto imitando a Evita en el balcón (desde la plaza)",
    photo_concepts: [
      {
        title: "Evita en la plaza",
        pose: "Brazo en alto saludando a la multitud, imitando el gesto de Evita",
        camera_angle: "Cámara frontal a la altura del pecho, balcón de fondo",
        best_time: "Mañana para luz frontal sobre la fachada",
        clothing: "Vestido o blazer elegante; recogido opcional",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Balcarce 50, Monserrat, Buenos Aires",
    lat: -34.6081,
    lng: -58.3703,
    search_query: "Casa Rosada Buenos Aires",
    emoji: "🩷",
  },
  {
    name: "Plaza de Mayo",
    name_en: "May Square",
    type: "free",
    category: "landmark",
    description:
      "La plaza histórica más importante de Buenos Aires, rodeada por la Casa Rosada, la Catedral y el Cabildo. Escenario de los grandes momentos políticos del país.",
    viral_trend: "Foto panorámica de la plaza con la Pirámide de Mayo y la Casa Rosada",
    photo_concepts: [
      {
        title: "Panorámica de la plaza",
        pose: "De pie junto a la Pirámide de Mayo, brazos relajados",
        camera_angle: "Cámara a la altura de los ojos, panorámica de izquierda a derecha",
        best_time: "Tarde para luz cálida sobre la Casa Rosada",
        clothing: "Casual urbano",
        instagram_score: 7,
        camera_tip: "Modo Panorama o gran angular 0.5x",
        format: "Horizontal panorámica",
      },
    ],
    instagram_score: 7,
    difficulty: 1,
    best_time: "Tarde",
    address: "Plaza de Mayo, Monserrat, Buenos Aires",
    lat: -34.6086,
    lng: -58.3728,
    search_query: "Plaza de Mayo Buenos Aires",
    emoji: "🏛️",
  },
  {
    name: "Cementerio de la Recoleta",
    name_en: "Recoleta Cemetery",
    type: "visit",
    category: "landmark",
    description:
      "Cementerio histórico con mausoleos de mármol labrado y callejones laberínticos. Aquí está la tumba de Evita Perón. Un museo al aire libre de arquitectura funeraria.",
    viral_trend: "Foto entre los mausoleos con la luz filtrándose entre las bóvedas",
    photo_concepts: [
      {
        title: "Luz entre mausoleos",
        pose: "Caminando por un callejón entre bóvedas, mirada al frente",
        camera_angle: "Cámara baja a la altura de la cintura, perspectiva del callejón",
        best_time: "Mediodía para luz cenital que filtra entre las bóvedas",
        clothing: "Outfit oscuro y elegante; abrigo largo",
        instagram_score: 9,
        camera_tip: "Gran angular para captar la altura de los mausoleos",
        format: "Vertical 4:5",
      },
      {
        title: "Mausoleo de Evita",
        pose: "De pie junto a la placa de la familia Duarte, mano en el corazón",
        camera_angle: "Cámara frontal a la altura del pecho",
        best_time: "Mañana para menos gente",
        clothing: "Sobrio y respetuoso",
        instagram_score: 7,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mediodía",
    address: "Junín 1760, Recoleta, Buenos Aires",
    lat: -34.5886,
    lng: -58.4172,
    search_query: "Cementerio de la Recoleta Buenos Aires",
    emoji: "🕯️",
  },
  {
    name: "Teatro Colón",
    name_en: "Colón Theatre",
    type: "visit",
    category: "landmark",
    description:
      "Uno de los teatros de ópera más prestigiosos del mundo, con una acústica legendaria y una arquitectura neoclásica deslumbrante. La sala principal es una joya dorada.",
    viral_trend: "Foto en la sala principal con la lámpara central y los palcos dorados",
    photo_concepts: [
      {
        title: "Sala dorada",
        pose: "Sentado en un palco, mano en la baranda, mirada a la lámpara central",
        camera_angle: "Cámara a la altura de los ojos, ligeramente hacia arriba para la lámpara",
        best_time: "Antes de la función con sala vacía (tour guiado)",
        clothing: "Elegante de noche; vestido o traje oscuro",
        instagram_score: 9,
        camera_tip: "No usar flash; modo Noche para la poca luz",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Antes de la función",
    address: "Cerrito 628, San Nicolás, Buenos Aires",
    lat: -34.6011,
    lng: -58.3831,
    search_query: "Teatro Colón Buenos Aires",
    emoji: "🎭",
  },
  {
    name: "Puerto Madero",
    name_en: "Puerto Madero",
    type: "free",
    category: "nightlife",
    description:
      "Antiguo puerto reconvertido en barrio moderno con rascacielos, restaurantes sobre los diques y el Puente de la Mujer de Santiago Calatrava. El waterfront más elegante de la ciudad.",
    viral_trend: "Foto en el Puente de la Mujer al atardecer con los rascacielos reflejados",
    photo_concepts: [
      {
        title: "Atardecer en el dique",
        pose: "Apoyado en la baranda del dique, mirada al atardecer",
        camera_angle: "Cámara a la altura de los ojos, reflejos en el agua",
        best_time: "Atardecer para cielo dorado y reflejos",
        clothing: "Outfit elegante urbano; chaqueta de noche",
        instagram_score: 8,
        format: "Horizontal",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Atardecer",
    address: "Puerto Madero, Buenos Aires",
    lat: -34.6106,
    lng: -58.3642,
    search_query: "Puerto Madero Buenos Aires",
    emoji: "🌆",
  },
  {
    name: "Puente de la Mujer",
    name_en: "Women's Bridge",
    type: "free",
    category: "landmark",
    description:
      "Puente giratorio peatonal diseñado por Santiago Calatrava que simula una pareja bailando tango. Se ha vuelto el ícono moderno de Puerto Madero.",
    viral_trend: "Foto en el puente con el atardecer y los edificios de fondo",
    photo_concepts: [
      {
        title: "Silueta en el puente",
        pose: "Caminando por el centro del puente, silueta contra el cielo dorado",
        camera_angle: "Cámara baja contrapicado para captar el mástil del puente",
        best_time: "Atardecer / blue hour",
        clothing: "Silueta; cualquier ropa oscura funciona",
        instagram_score: 9,
        camera_tip: "Exposición bloqueada en el cielo para silueta",
        format: "Vertical 4:5",
      },
      {
        title: "Geometría del mástil",
        pose: "De pie bajo el mástil, mirando hacia arriba",
        camera_angle: "Cámara en el suelo apuntando al cenit",
        best_time: "Día con cielo azul",
        clothing: "Casual",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x",
        format: "Cuadrada",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer",
    address: "Puente de la Mujer, Puerto Madero, Buenos Aires",
    lat: -34.6094,
    lng: -58.3647,
    search_query: "Puente de la Mujer Buenos Aires",
    emoji: "🌉",
  },
  {
    name: "Plaza San Martín",
    name_en: "San Martín Square",
    type: "free",
    category: "park",
    description:
      "Plaza arbolada en Retiro con el monumento al General San Martín y vistas a la Torre de los Ingleses. Un oasis verde en el centro de la ciudad.",
    viral_trend: "Foto en la plaza con la Torre Monumental de fondo",
    photo_concepts: [
      {
        title: "Bajo los árboles",
        pose: "Sentado en un banco bajo la arboleda, libro o café en mano",
        camera_angle: "Cámara a la altura de los ojos, profundidad de campo con la torre desenfocada",
        best_time: "Mañana para luz suave filtrada por las hojas",
        clothing: "Casual otoñal; bufanda",
        instagram_score: 7,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 7,
    difficulty: 1,
    best_time: "Mañana",
    address: "Plaza San Martín, Retiro, Buenos Aires",
    lat: -34.5914,
    lng: -58.3747,
    search_query: "Plaza San Martín Retiro Buenos Aires",
    emoji: "🌳",
  },
];

export const CURATED_SPOTS_CARTAGENA: CuratedSpot[] = [
  {
    name: "Callejón Angosto (Umbrella Street)",
    name_en: "Umbrella Street",
    type: "free",
    category: "street-art",
    description:
      "Callejón decorado con paraguas de colores suspendidos en Getsemaní. Se ha vuelto viral en Instagram como el spot más colorido de Cartagena.",
    viral_trend: "Foto bajo el túnel de paraguas de colores",
    photo_concepts: [
      {
        title: "Túnel de paraguas",
        pose: "Caminando bajo los paraguas, mirando hacia arriba con una sonrisa",
        camera_angle: "Cámara baja apuntando ligeramente arriba para captar los paraguas",
        best_time: "Mañana temprano para evitar multitudes",
        clothing: "Vestido blanco o colores pastel que complementen los paraguas",
        instagram_score: 10,
        camera_tip: "Gran angular 0.5x para captar todo el techo de paraguas",
        format: "Vertical 4:5",
      },
      {
        title: "Detalle de un paraguas",
        pose: "Mano sosteniendo un paraguas individual sobre la cabeza",
        camera_angle: "Primer plano, fondo desenfocado del callejón",
        best_time: "Mediodía para colores saturados",
        clothing: "N/A (foco en el paraguas)",
        instagram_score: 8,
        format: "Cuadrada",
      },
    ],
    instagram_score: 10,
    difficulty: 1,
    best_time: "Mañana temprano",
    address: "Callejón Angosto, Getsemaní, Cartagena",
    lat: 10.4214,
    lng: -75.5481,
    search_query: "Callejón Angosto Getsemaní Cartagena",
    emoji: "☂️",
  },
  {
    name: "Torre del Reloj",
    name_en: "Clock Tower",
    type: "free",
    category: "landmark",
    description:
      "La puerta principal de la ciudad amurallada y el símbolo de Cartagena. La torre del reloj de estilo neoclásico separa el centro histórico de Getsemaní.",
    viral_trend: "Foto de noche con la torre iluminada y los colores cálidos",
    photo_concepts: [
      {
        title: "Torre iluminada de noche",
        pose: "De pie frente a la torre, brazos cruzados o caminando hacia ella",
        camera_angle: "Cámara frontal a la altura del pecho, simetría con la torre",
        best_time: "Noche con la torre iluminada en tonos cálidos",
        clothing: "Vestido o camisa clara para destacar en la oscuridad",
        instagram_score: 9,
        camera_tip: "Modo Noche del iPhone; sin flash",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Noche",
    address: "Plaza de los Coches, Centro, Cartagena",
    lat: 10.4231,
    lng: -75.5478,
    search_query: "Torre del Reloj Cartagena",
    emoji: "🕰️",
  },
  {
    name: "Las Bóvedas",
    name_en: "Las Bóvedas",
    type: "visit",
    category: "landmark",
    description:
      "Antiguas mazmorras coloniales en el extremo de las murallas, hoy convertidas en mercado de artesanías. Los arcos de piedra son una postal clásica.",
    viral_trend: "Foto bajo los arcos de piedra con las artesanías coloridas",
    photo_concepts: [
      {
        title: "Arcos coloniales",
        pose: "Caminando bajo la sucesión de arcos, mirada al frente",
        camera_angle: "Cámara baja a la altura de la cintura, perspectiva de los arcos en repetición",
        best_time: "Mañana para luz suave y menos turistas",
        clothing: "Vestido floral o colores tropicales",
        instagram_score: 8,
        camera_tip: "Gran angular para captar la repetición de arcos",
        format: "Horizontal",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Las Bóvedas, Santa Catalina, Cartagena",
    lat: 10.4267,
    lng: -75.5519,
    search_query: "Las Bóvedas Cartagena",
    emoji: "🏛️",
  },
  {
    name: "Barrio San Diego",
    name_en: "San Diego Neighborhood",
    type: "free",
    category: "landmark",
    description:
      "Barrio colonial con calles empedradas, balcones cubiertos de buganvillas y plazas tranquilas. Una de las zonas más encantadoras dentro de la ciudad amurallada.",
    viral_trend: "Foto en una calle empedrada con buganvillas y balcones coloniales",
    photo_concepts: [
      {
        title: "Buganvillas y balcones",
        pose: "Apoyada/o en una esquina, mano en una buganvilla",
        camera_angle: "Cámara a la altura de los ojos, calle empedrada como guía",
        best_time: "Mañana para luz suave y flores frescas",
        clothing: "Vestido blanco o claro para contrastar con las flores",
        instagram_score: 9,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana",
    address: "San Diego, Centro Histórico, Cartagena",
    lat: 10.4258,
    lng: -75.5506,
    search_query: "Barrio San Diego Cartagena",
    emoji: "🌺",
  },
  {
    name: "Castillo San Felipe de Barajas",
    name_en: "San Felipe de Barajas Castle",
    type: "visit",
    category: "landmark",
    description:
      "La fortaleza colonial más grande construida por los españoles en América. Sus túneles laberínticos y murallas ofrecen vistas panorámicas de la ciudad.",
    viral_trend: "Foto en los túneles oscuros o en la cima con la ciudad al fondo",
    photo_concepts: [
      {
        title: "Túnel laberíntico",
        pose: "Caminando agachado por el túnel, mano en la pared de piedra",
        camera_angle: "Cámara baja, perspectiva del túnel con luz al fondo",
        best_time: "Mañana para rayos de luz en los túneles",
        clothing: "Ropa cómoda y cerrada; el castillo tiene superficies irregulares",
        instagram_score: 8,
        camera_tip: "Modo Noche; la luz es escasa en los túneles",
        format: "Vertical 4:5",
      },
      {
        title: "Cima panorámica",
        pose: "Brazos abiertos en la cima con Cartagena al fondo",
        camera_angle: "Cámara baja contrapicado para captar la muralla y la ciudad",
        best_time: "Atardecer para luz dorada sobre la ciudad",
        clothing: "Ropa cómoda; sombrero para el sol",
        instagram_score: 9,
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Atardecer",
    address: "Calle 30, San Diego, Cartagena",
    lat: 10.4228,
    lng: -75.5403,
    search_query: "Castillo San Felipe de Barajas Cartagena",
    emoji: "🏰",
  },
  {
    name: "Convento de la Popa",
    name_en: "La Popa Convent",
    type: "visit",
    category: "viewpoint",
    description:
      "Convento agustino del siglo XVII en el punto más alto de Cartagena. Ofrece la mejor vista panorámica de la ciudad amurallada, el mar y la bahía.",
    viral_trend: "Foto panorámica de Cartagena desde el convento al atardecer",
    photo_concepts: [
      {
        title: "Panorámica al atardecer",
        pose: "De pie en el mirador, brazos abiertos con la ciudad al fondo",
        camera_angle: "Cámara a la altura de los ojos, panorámica de 180°",
        best_time: "Atardecer para cielo dorado y ciudad iluminada",
        clothing: "Vestido o camisa clara; el viento de la cima ayuda",
        instagram_score: 9,
        camera_tip: "Modo Panorama o gran angular 0.5x",
        format: "Horizontal panorámica",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Atardecer",
    address: "Cerro de La Popa, Cartagena",
    lat: 10.4169,
    lng: -75.5328,
    search_query: "Convento de la Popa Cartagena",
    emoji: "⛪",
  },
  {
    name: "Playa de Bocagrande",
    name_en: "Bocagrande Beach",
    type: "free",
    category: "beach",
    description:
      "Playa urbana en el barrio de rascacielos de Bocagrande, con vista a la bahía y al skyline de Cartagena. Arena dorada y ambiente playero a minutos del centro.",
    viral_trend: "Foto en la playa con los rascacielos de Bocagrande de fondo",
    photo_concepts: [
      {
        title: "Skyline playero",
        pose: "De pie en la arena, mirando al mar, rascacielos a la espalda",
        camera_angle: "Cámara a la altura de los ojos, playa y skyline en el mismo plano",
        best_time: "Mañana para luz suave y menos calor",
        clothing: "Traje de baño + kimono o vestido de playa",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
      {
        title: "Reflejo en la orilla",
        pose: "Caminando por la orilla descalzo, salpicando agua",
        camera_angle: "Cámara baja a la altura del suelo, reflejo en la arena mojada",
        best_time: "Atardecer para reflejos dorados",
        clothing: "Traje de baño + ropa ligera",
        instagram_score: 9,
        format: "Horizontal",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Av. San Martín, Bocagrande, Cartagena",
    lat: 10.4014,
    lng: -75.5536,
    search_query: "Playa de Bocagrande Cartagena",
    emoji: "🏖️",
  },
  {
    name: "Getsemaní",
    name_en: "Getsemaní",
    type: "free",
    category: "nightlife",
    description:
      "Barrio bohemio fuera de las murallas, lleno de arte callejero, música y bares. La Plaza de la Trinidad es su corazón, donde se reúnen locales y viajeros de noche.",
    viral_trend: "Foto con los murales callejeros y la Plaza de la Trinidad de noche",
    photo_concepts: [
      {
        title: "Murales nocturnos",
        pose: "Apoyado contra un mural, una pierna cruzada, actitud relajada",
        camera_angle: "Cámara frontal a la altura del pecho, mural como fondo",
        best_time: "Noche con luz de faroles sobre los murales",
        clothing: "Outfit urbano colorido; accesorios llamativos",
        instagram_score: 9,
        camera_tip: "Modo Noche; aprovechar la luz cálida de las farolas",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Noche",
    address: "Getsemaní, Cartagena",
    lat: 10.4219,
    lng: -75.5481,
    search_query: "Getsemaní Cartagena",
    emoji: "🎺",
  },
  {
    name: "Las Murallas",
    name_en: "The Walls",
    type: "free",
    category: "landmark",
    description:
      "Las murallas coloniales que rodean el casco antiguo, de más de 11 km. Caminar por encima al atardecer con una copa de vino es una tradición cartagenera.",
    viral_trend: "Foto sentado en las murallas viendo el atardecer sobre el mar",
    photo_concepts: [
      {
        title: "Atardecer sobre las murallas",
        pose: "Sentado en la muralla, piernas colgando, copa en mano",
        camera_angle: "Cámara a la altura de los ojos, mar y sol al fondo",
        best_time: "Atardecer para el sol cayendo sobre el mar",
        clothing: "Vestido de verano o camisa ligera",
        instagram_score: 10,
        camera_tip: "Silueta contra el sol; exposición bloqueada en el cielo",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 1,
    best_time: "Atardecer",
    address: "Murallas de Cartagena, Centro Histórico, Cartagena",
    lat: 10.4242,
    lng: -75.5508,
    search_query: "Murallas de Cartagena",
    emoji: "🌅",
  },
  {
    name: "Plaza Santo Domingo",
    name_en: "Santo Domingo Square",
    type: "free",
    category: "landmark",
    description:
      "Plaza colonial presidida por la Iglesia de Santo Domingo y la escultura 'Mujer Reclinada' de Botero. Llena de cafés y terrazas, es un punto de encuentro icónico.",
    viral_trend: "Foto con la escultura de Botero y la iglesia de fondo",
    photo_concepts: [
      {
        title: "Con la Botero",
        pose: "Sentado o recostado imitando la pose de la escultura de Botero",
        camera_angle: "Cámara frontal a la altura de la escultura, iglesia de fondo",
        best_time: "Mañana para luz suave y menos gente",
        clothing: "Vestido o camisa de colores vivos",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Plaza Santo Domingo, Centro, Cartagena",
    lat: 10.4244,
    lng: -75.5503,
    search_query: "Plaza Santo Domingo Cartagena",
    emoji: "🗿",
  },
  {
    name: "Plaza de la Trinidad",
    name_en: "Trinidad Square",
    type: "free",
    category: "nightlife",
    description:
      "La plaza más animada de Getsemaní, rodeada de bares y restaurantes. De noche se llena de música en vivo, artistas callejeros y ambiente festivo.",
    viral_trend: "Video de la plaza de noche con música y ambiente callejero",
    photo_concepts: [
      {
        title: "Ambiente nocturno",
        pose: "Con una cerveza o cóctel en mano, sonriendo con el grupo",
        camera_angle: "Cámara a la altura del pecho, plaza e iglesia iluminadas de fondo",
        best_time: "Noche con la plaza llena de música",
        clothing: "Outfit casual de noche; colores cálidos",
        instagram_score: 8,
        camera_tip: "Modo Noche; captar las luces de colores de los bares",
        format: "Vertical 4:5",
      },
      {
        title: "Artistas callejeros",
        pose: "Grabando o aplaudiendo a un artista callejero",
        camera_angle: "Cámara a la altura de los ojos, enfoque en el artista",
        best_time: "Noche",
        clothing: "Casual",
        instagram_score: 8,
        format: "Vertical 9:16 (Reel)",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Noche",
    address: "Plaza de la Trinidad, Getsemaní, Cartagena",
    lat: 10.4214,
    lng: -75.5489,
    search_query: "Plaza de la Trinidad Getsemaní Cartagena",
    emoji: "🎶",
  },
];

export const CURATED_SPOTS_BOGOTA: CuratedSpot[] = [
  {
    name: "La Candelaria",
    name_en: "La Candelaria",
    type: "free",
    category: "landmark",
    description:
      "El barrio histórico y cultural de Bogotá, con calles empedradas, casas coloniales coloridas, murales y museos. El corazón fundacional de la ciudad.",
    viral_trend: "Foto en una calle empedrada con murales y casas coloniales",
    photo_concepts: [
      {
        title: "Calle empedrada con murales",
        pose: "Caminando por la calle empedrada, mirada al frente",
        camera_angle: "Cámara baja a la altura de la cintura, perspectiva de la calle",
        best_time: "Mañana para luz suave y menos gente",
        clothing: "Outfit colorido; bufanda o sombrero andino",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para captar las casas y el cielo",
        format: "Vertical 4:5",
      },
      {
        title: "Frente a un mural",
        pose: "Apoyado contra un mural, cruzado de brazos",
        camera_angle: "Cámara frontal a la altura del pecho",
        best_time: "Tarde para luz lateral sobre los murales",
        clothing: "Outfit urbano; chaqueta de colores",
        instagram_score: 8,
        format: "Cuadrada",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Mañana",
    address: "La Candelaria, Bogotá",
    lat: 4.5981,
    lng: -74.0728,
    search_query: "La Candelaria Bogotá",
    emoji: "🏘️",
  },
  {
    name: "Cerro de Monserrate",
    name_en: "Monserrate Hill",
    type: "tour",
    category: "viewpoint",
    description:
      "Cerro de 3.152 m con una iglesia en la cima y la mejor vista panorámica de Bogotá. Se sube en teleférico, funicular o caminando por un sendero de 1.500 m de desnivel.",
    viral_trend: "Foto en la cima con Bogotá extendida a los pies al atardecer",
    photo_concepts: [
      {
        title: "Bogotá a los pies",
        pose: "Brazos abiertos en el mirador, ciudad extendida al fondo",
        camera_angle: "Cámara baja contrapicado para captar la ciudad y el cielo",
        best_time: "Atardecer para luz dorada sobre la sabana",
        clothing: "Abrigo grueso; la cima es fría a 3.152 m",
        instagram_score: 10,
        camera_tip: "Gran angular 0.5x para captar toda la ciudad",
        format: "Horizontal",
      },
      {
        title: "Iglesia blanca",
        pose: "De pie frente a la iglesia, mirada al frente",
        camera_angle: "Cámara frontal a la altura de los ojos, simetría con la iglesia",
        best_time: "Mañana para luz frontal",
        clothing: "Abrigo; el clima es frío",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 3,
    best_time: "Atardecer",
    address: "Cerro de Monserrate, Bogotá",
    lat: 4.6056,
    lng: -74.0575,
    search_query: "Cerro de Monserrate Bogotá",
    emoji: "⛪",
  },
  {
    name: "Plazoleta Chorro de Quevedo",
    name_en: "Chorro de Quevedo Square",
    type: "free",
    category: "landmark",
    description:
      "Pequeña plazoleta donde se fundó Bogotá en 1538. Ambiente bohemio, artistas callejeros y la famosa bebida local: el chicha en barro.",
    viral_trend: "Foto con un vaso de chicha en la plazoleta bohemio",
    photo_concepts: [
      {
        title: "Chicha en barro",
        pose: "Sosteniendo un vaso de barro con chicha, brindis a la cámara",
        camera_angle: "Cámara frontal a la altura del rostro, plazoleta de fondo",
        best_time: "Tarde con ambiente bohemio",
        clothing: "Outfit casual; ruana o bufanda andina",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Tarde",
    address: "Calle 12C #2-82, La Candelaria, Bogotá",
    lat: 4.5969,
    lng: -74.0714,
    search_query: "Chorro de Quevedo Bogotá",
    emoji: "🍺",
  },
  {
    name: "Museo del Oro",
    name_en: "Gold Museum",
    type: "visit",
    category: "museum",
    description:
      "El museo más importante de Colombia, con más de 34.000 piezas de oro precolombino. La sala final de la exposición es una experiencia inmersiva de luz y oro.",
    viral_trend: "Foto en la sala dorada rodeado de piezas de oro iluminadas",
    photo_concepts: [
      {
        title: "Sala dorada inmersiva",
        pose: "De pie en el centro de la sala, brazos ligeramente abiertos, mirada asombrada",
        camera_angle: "Cámara a la altura de los ojos, sala circular de fondo",
        best_time: "Cualquier hora (interior); evitar fines de semana",
        clothing: "Outfit oscuro para que el oro destaque",
        instagram_score: 9,
        camera_tip: "Sin flash (prohibido); modo Noche",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Entre semana",
    address: "Calle 16 #5-41, La Candelaria, Bogotá",
    lat: 4.6020,
    lng: -74.0728,
    search_query: "Museo del Oro Bogotá",
    emoji: "🥇",
  },
  {
    name: "Plaza Bolívar",
    name_en: "Bolívar Square",
    type: "free",
    category: "landmark",
    description:
      "La plaza principal de Bogotá, rodeada por la Catedral, el Capitolio, el Palacio de Justicia y el Alcaldía. Monumento ecuestre a Bolívar en el centro.",
    viral_trend: "Foto panorámica de la plaza con la Catedral y el Capitolio",
    photo_concepts: [
      {
        title: "Panorámica de la plaza",
        pose: "De pie en el centro, brazos relajados",
        camera_angle: "Cámara a la altura de los ojos, panorámica de la plaza",
        best_time: "Mañana para luz frontal sobre la Catedral",
        clothing: "Casual urbano; abrigo ligero",
        instagram_score: 7,
        camera_tip: "Modo Panorama o gran angular 0.5x",
        format: "Horizontal panorámica",
      },
    ],
    instagram_score: 7,
    difficulty: 1,
    best_time: "Mañana",
    address: "Plaza de Bolívar, La Candelaria, Bogotá",
    lat: 4.5981,
    lng: -74.0728,
    search_query: "Plaza Bolívar Bogotá",
    emoji: "🏛️",
  },
  {
    name: "Usaquén",
    name_en: "Usaquén",
    type: "free",
    category: "food",
    description:
      "Barrio colonial anexado a Bogotá, con plazas encantadoras, restaurantes y un mercado de pulgas los domingos. Ambiente relajado y arquitectura de pueblo.",
    viral_trend: "Foto en el mercado dominical de Usaquén con artesanías",
    photo_concepts: [
      {
        title: "Mercado dominical",
        pose: "Sosteniendo una artesanía, sonriendo entre los puestos",
        camera_angle: "Cámara a la altura del pecho, puestos coloridos de fondo",
        best_time: "Domingo por la mañana (solo hay mercado domingos)",
        clothing: "Outfit casual de fin de semana; sombrero opcional",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Domingo por la mañana",
    address: "Usaquén, Bogotá",
    lat: 4.7014,
    lng: -74.0392,
    search_query: "Usaquén Bogotá",
    emoji: "🛍️",
  },
  {
    name: "Parque Simón Bolívar",
    name_en: "Simón Bolívar Park",
    type: "free",
    category: "park",
    description:
      "El parque más grande de Bogotá, pulmón verde de la ciudad. Lago, jardines, ciclovías y escenario para conciertos masivos. Ideal para picnic y día al aire.",
    viral_trend: "Foto en bote en el lago o picnic en el césped",
    photo_concepts: [
      {
        title: "Picnic en el césped",
        pose: "Sentado en una manta con fruta y café, piernas cruzadas",
        camera_angle: "Cámara alta desde arriba, plano cenital",
        best_time: "Mañana o tarde para luz suave",
        clothing: "Outfit casual de día; colores claros",
        instagram_score: 8,
        camera_tip: "Plano cenital desde arriba con gran angular",
        format: "Cuadrada",
      },
      {
        title: "Bote en el lago",
        pose: "Remando en un bote del lago, sonriendo",
        camera_angle: "Cámara a la altura del agua desde otro bote o el muelle",
        best_time: "Tarde para reflejos dorados",
        clothing: "Ropa cómoda; chaleco salvavidas",
        instagram_score: 7,
        format: "Horizontal",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Tarde",
    address: "Av. Calle 63, Bogotá",
    lat: 4.6583,
    lng: -74.0956,
    search_query: "Parque Simón Bolívar Bogotá",
    emoji: "🌳",
  },
  {
    name: "Jardín Botánico de Bogotá",
    name_en: "Bogotá Botanical Garden",
    type: "visit",
    category: "park",
    description:
      "Jardín botánico con invernaderos de cristal, bosque de niebla y colección de flora andina. El invernadero de palmas es uno de los más grandes del mundo.",
    viral_trend: "Foto dentro del invernadero de cristal con plantas tropicales",
    photo_concepts: [
      {
        title: "Invernadero de cristal",
        pose: "Caminando entre las palmas del invernadero, mano tocando una hoja",
        camera_angle: "Cámara baja a la altura de la cintura, cúpula de cristal de fondo",
        best_time: "Mañana para luz uniforme filtrada por el cristal",
        clothing: "Outfit verde o tierra para integrarse con la flora",
        instagram_score: 8,
        camera_tip: "Gran angular 0.5x para captar la cúpula",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Calle 63 #68-95, Bogotá",
    lat: 4.6683,
    lng: -74.1039,
    search_query: "Jardín Botánico Bogotá",
    emoji: "🌿",
  },
  {
    name: "Catedral de Sal de Zipaquirá",
    name_en: "Salt Cathedral of Zipaquirá",
    type: "visit",
    category: "landmark",
    description:
      "Catedral tallada dentro de una mina de sal a 200 m bajo tierra. Una de las maravillas arquitectónicas de Colombia, con iluminación dramática en las naves de sal.",
    viral_trend: "Foto en la nave principal con la cruz iluminada en la roca de sal",
    photo_concepts: [
      {
        title: "Cruz iluminada en la sal",
        pose: "De pie en la nave principal, brazos a los lados, mirada a la cruz",
        camera_angle: "Cámara baja contrapicado para captar la cruz y la bóveda",
        best_time: "Cualquier hora (interior subterráneo)",
        clothing: "Abrigo; la temperatura es fresca bajo tierra",
        instagram_score: 10,
        camera_tip: "Modo Noche; sin flash (prohibido)",
        format: "Vertical 4:5",
      },
      {
        title: "Túnel de sal",
        pose: "Caminando por un túnel iluminado, silueta",
        camera_angle: "Cámara baja, perspectiva del túnel",
        best_time: "Cualquier hora",
        clothing: "Abrigo oscuro",
        instagram_score: 9,
        format: "Horizontal",
      },
    ],
    instagram_score: 10,
    difficulty: 2,
    best_time: "Cualquier hora (interior)",
    address: "Parque de la Sal, Zipaquirá, Cundinamarca",
    lat: 5.0219,
    lng: -74.0042,
    search_query: "Catedral de Sal Zipaquirá",
    emoji: "⛏️",
  },
];

export const CURATED_SPOTS_LIMA: CuratedSpot[] = [
  {
    name: "Barranco",
    name_en: "Barranco",
    type: "free",
    category: "nightlife",
    description:
      "El barrio bohemio de Lima, con casas republicanas, murales, bares y galerías de arte. El Puente de los Suspiros es su ícono romántico.",
    viral_trend: "Foto en el Puente de los Suspiros con la vista al mar",
    photo_concepts: [
      {
        title: "Murales de Barranco",
        pose: "Apoyado contra un mural, actitud relajada",
        camera_angle: "Cámara frontal a la altura del pecho, mural de fondo",
        best_time: "Tarde para luz suave sobre los murales",
        clothing: "Outfit bohemio; sombrero o pañuelo",
        instagram_score: 9,
        format: "Vertical 4:5",
      },
      {
        title: "Atardecer desde el Puente",
        pose: "Apoyado en la baranda del Puente de los Suspiros, mirada al mar",
        camera_angle: "Cámara a la altura de los ojos, mar y atardecer de fondo",
        best_time: "Atardecer para cielo dorado",
        clothing: "Casual de tarde; chaqueta ligera",
        instagram_score: 9,
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer",
    address: "Barranco, Lima",
    lat: -12.1467,
    lng: -77.0219,
    search_query: "Barranco Lima",
    emoji: "🎨",
  },
  {
    name: "Parque del Amor",
    name_en: "Love Park",
    type: "free",
    category: "viewpoint",
    description:
      "Parque en el malecón de Miraflores con mosaicos de Gaudí y la escultura 'El Beso'. Vistas al océano Pacífico y lugar favorito para ver el atardecer.",
    viral_trend: "Foto imitando el beso de la escultura con el océano de fondo",
    photo_concepts: [
      {
        title: "El Beso con el océano",
        pose: "Pareja besándose imitando la escultura, ojos cerrados",
        camera_angle: "Cámara frontal a la altura de la escultura, océano de fondo",
        best_time: "Atardecer para luz dorada y mar de fondo",
        clothing: "Outfit romántico; colores cálidos",
        instagram_score: 10,
        camera_tip: "Gran angular 0.5x para captar la escultura y el mar",
        format: "Vertical 4:5",
      },
      {
        title: "Mosaicos de Gaudí",
        pose: "Sentado sobre los mosaicos del malecón, piernas cruzadas",
        camera_angle: "Cámara alta desde arriba, plano cenital",
        best_time: "Tarde para luz suave",
        clothing: "Outfit colorido que combine con los mosaicos",
        instagram_score: 8,
        format: "Cuadrada",
      },
    ],
    instagram_score: 10,
    difficulty: 1,
    best_time: "Atardecer",
    address: "Malecón Cisneros, Miraflores, Lima",
    lat: -12.1325,
    lng: -77.0306,
    search_query: "Parque del Amor Lima",
    emoji: "💋",
  },
  {
    name: "Circuito Mágico del Agua",
    name_en: "Magic Water Circuit",
    type: "event",
    category: "park",
    description:
      "Parque con 13 fuentes ornamentales que se iluminan de noche con show de luces y agua. La fuente principal tiene un espectáculo de proyecciones sincronizado con música.",
    viral_trend: "Video del show de luces y agua en la fuente principal",
    photo_concepts: [
      {
        title: "Show de luces y agua",
        pose: "Caminando entre las fuentes, mojándose con el agua",
        camera_angle: "Cámara baja a la altura de la cintura, fuentes iluminadas de fondo",
        best_time: "Noche durante el show (18:00-21:30)",
        clothing: "Ropa que se pueda mojar; chanclas",
        instagram_score: 9,
        camera_tip: "Modo Noche; vídeo en cámara lenta para el agua",
        format: "Vertical 9:16 (Reel)",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Noche (show 18:00-21:30)",
    address: "Parque de la Reserva, Lima",
    lat: -12.1414,
    lng: -77.0283,
    search_query: "Circuito Mágico del Agua Lima",
    emoji: "⛲",
  },
  {
    name: "Plaza Mayor",
    name_en: "Main Square",
    type: "free",
    category: "landmark",
    description:
      "La plaza fundacional de Lima, rodeada por la Catedral, el Palacio de Gobierno y la Municipalidad. Patrimonio de la Humanidad y corazón del Centro Histórico.",
    viral_trend: "Foto panorámica con la Catedral y el Palacio de Gobierno",
    photo_concepts: [
      {
        title: "Panorámica de la Plaza Mayor",
        pose: "De pie en el centro de la plaza, brazos relajados",
        camera_angle: "Cámara a la altura de los ojos, panorámica de la plaza",
        best_time: "Mañana para luz frontal sobre la Catedral",
        clothing: "Casual urbano",
        instagram_score: 8,
        camera_tip: "Modo Panorama o gran angular 0.5x",
        format: "Horizontal panorámica",
      },
      {
        title: "Frente a la Catedral",
        pose: "Sentado en las escaleras de la Catedral, mirada al frente",
        camera_angle: "Cámara baja a la altura de las escaleras, Catedral de fondo",
        best_time: "Tarde para luz cálida",
        clothing: "Casual; sombrero para el sol",
        instagram_score: 7,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Plaza Mayor, Centro Histórico, Lima",
    lat: -12.0464,
    lng: -77.0303,
    search_query: "Plaza Mayor Lima",
    emoji: "🏛️",
  },
  {
    name: "Malecón de Miraflores",
    name_en: "Miraflores Boardwalk",
    type: "free",
    category: "viewpoint",
    description:
      "Paseo peatonal sobre los acantilados de Miraflores con vistas al Pacífico. Parques, áreas de parapente y los mejores atardeceres de Lima.",
    viral_trend: "Foto con parapentistas volando sobre el acantilado al atardecer",
    photo_concepts: [
      {
        title: "Parapente al atardecer",
        pose: "De pie en el malecón, mirando a los parapentistas",
        camera_angle: "Cámara a la altura de los ojos, parapente y mar de fondo",
        best_time: "Atardecer para cielo dorado y parapentistas",
        clothing: "Casual de tarde; chaqueta por la brisa",
        instagram_score: 10,
        camera_tip: "Zoom 2x para acercar parapentistas; gran angular para el paisaje",
        format: "Vertical 4:5",
      },
      {
        title: "Silueta en el acantilado",
        pose: "De espaldas al borde del malecón, silueta contra el atardecer",
        camera_angle: "Cámara baja contrapicado, sol al fondo",
        best_time: "Atardecer / blue hour",
        clothing: "Ropa oscura para silueta",
        instagram_score: 9,
        camera_tip: "Exposición bloqueada en el cielo",
        format: "Horizontal",
      },
    ],
    instagram_score: 10,
    difficulty: 1,
    best_time: "Atardecer",
    address: "Malecón de Miraflores, Lima",
    lat: -12.1306,
    lng: -77.0311,
    search_query: "Malecón de Miraflores Lima",
    emoji: "🪂",
  },
  {
    name: "Huaca Pucllana",
    name_en: "Huaca Pucllana",
    type: "visit",
    category: "landmark",
    description:
      "Sitio arqueológico preinca de adobe en pleno corazón de Miraflores. Pirámide de 500 d.C. que contrasta con el moderno barrio que la rodea.",
    viral_trend: "Foto de la pirámide de adobe con los edificios modernos detrás",
    photo_concepts: [
      {
        title: "Pirámide vs. rascacielos",
        pose: "De pie frente a la pirámide, brazos abiertos",
        camera_angle: "Cámara baja contrapicado para captar la pirámide y los edificios",
        best_time: "Atardecer para luz dorada sobre el adobe",
        clothing: "Casual; colores tierra",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para el contraste pirámide/edificios",
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer",
    address: "Calle General Borgoño, Miraflores, Lima",
    lat: -12.1186,
    lng: -77.0342,
    search_query: "Huaca Pucllana Lima",
    emoji: "🏺",
  },
  {
    name: "Museo Larco",
    name_en: "Larco Museum",
    type: "visit",
    category: "museum",
    description:
      "Museo en una casona colonial del siglo XVIII con la mejor colección de cerámica precolombina del Perú. Famoso por su sala de arte erótico mochica.",
    viral_trend: "Foto en el jardín del museo con buganvillas y la casona colonial",
    photo_concepts: [
      {
        title: "Jardín con buganvillas",
        pose: "Sentado en una banca del jardín, rodeado de buganvillas",
        camera_angle: "Cámara a la altura de los ojos, casona colonial de fondo",
        best_time: "Mañana para luz suave y flores frescas",
        clothing: "Outfit elegante; vestido o blazer",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
      {
        title: "Cerámica precolombina",
        pose: "Observando una vitrina de cerámica mochica",
        camera_angle: "Cámara a la altura del hombro, vitrina de fondo desenfocada",
        best_time: "Cualquier hora (interior)",
        clothing: "Elegante de museo",
        instagram_score: 7,
        camera_tip: "Sin flash; modo Noche",
        format: "Cuadrada",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Av. Bolívar 1515, Pueblo Libre, Lima",
    lat: -12.0719,
    lng: -77.0703,
    search_query: "Museo Larco Lima",
    emoji: "🏺",
  },
  {
    name: "Parque Kennedy",
    name_en: "Kennedy Park",
    type: "free",
    category: "park",
    description:
      "El parque central de Miraflores, lleno de gatos que se han vuelto una atracción. Rodeado de cafés, ferias de arte y ambiente animado de día y noche.",
    viral_trend: "Foto con los gatos del parque que se han vuelto famosos",
    photo_concepts: [
      {
        title: "Con los gatos del parque",
        pose: "Sentado en un banco con un gato en el regazo",
        camera_angle: "Cámara a la altura del gato, primer plano",
        best_time: "Tarde para luz suave y gatos activos",
        clothing: "Casual; ropa que no atraiga pelo",
        instagram_score: 8,
        format: "Cuadrada",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Tarde",
    address: "Parque Kennedy, Miraflores, Lima",
    lat: -12.1214,
    lng: -77.0297,
    search_query: "Parque Kennedy Miraflores Lima",
    emoji: "🐱",
  },
  {
    name: "Puente de los Suspiros",
    name_en: "Bridge of Sighs",
    type: "free",
    category: "landmark",
    description:
      "Puente de madera en Barranco, rodeado de leyendas románticas. Se dice que quien cruza sin mirar el río y pide un deseo, este se cumple.",
    viral_trend: "Foto en el puente de noche con las luces y el ambiente bohemio",
    photo_concepts: [
      {
        title: "Deseo en el puente",
        pose: "Cruzando el puente con ojos cerrados, pidiendo un deseo",
        camera_angle: "Cámara a la altura de los ojos, puente iluminado de fondo",
        best_time: "Noche con el puente iluminado",
        clothing: "Outfit bohemio; vestido o camisa ligera",
        instagram_score: 9,
        camera_tip: "Modo Noche; sin flash",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Noche",
    address: "Jirón de la Unión, Barranco, Lima",
    lat: -12.1464,
    lng: -77.0217,
    search_query: "Puente de los Suspiros Barranco Lima",
    emoji: "🌉",
  },
];

export const CURATED_SPOTS_SANTIAGO: CuratedSpot[] = [
  {
    name: "Cerro Santa Lucía",
    name_en: "Santa Lucía Hill",
    type: "free",
    category: "viewpoint",
    description:
      "Cerro histórico donde Pedro de Valdivia fundó Santiago en 1541. Hoy es un parque con terrazas, fuentes y miradores con vistas al centro y la cordillera.",
    viral_trend: "Foto en el mirador con la cordillera de los Andes de fondo",
    photo_concepts: [
      {
        title: "Cordillera desde el mirador",
        pose: "Brazos abiertos en el mirador, cordillera de los Andes al fondo",
        camera_angle: "Cámara baja contrapicado para captar la cordillera",
        best_time: "Mañana para cielo despejado y cordillera visible",
        clothing: "Casual; lentes de sol por la altura",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para captar la cordillera completa",
        format: "Horizontal",
      },
      {
        title: "Terrazas y fuentes",
        pose: "Caminando por las escaleras de piedra del cerro",
        camera_angle: "Cámara baja a la altura de la cintura, perspectiva de las escaleras",
        best_time: "Tarde para luz dorada",
        clothing: "Outfit urbano; chaqueta",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Mañana",
    address: "Cerro Santa Lucía, Santiago",
    lat: -33.4389,
    lng: -70.6478,
    search_query: "Cerro Santa Lucía Santiago",
    emoji: "⛰️",
  },
  {
    name: "Templo Bahá'í",
    name_en: "Bahá'í Temple",
    type: "free",
    category: "landmark",
    description:
      "Templo bahá'í de Sudamérica, una obra arquitectónica de cristal translúcido que parece una flor. La luz que filtra crea un ambiente etéreo único.",
    viral_trend: "Foto del templo de cristal con la luz filtrándose al atardecer",
    photo_concepts: [
      {
        title: "Templo de cristal al atardecer",
        pose: "De pie frente al templo, brazos relajados",
        camera_angle: "Cámara baja contrapicado para captar la cúpula de cristal",
        best_time: "Atardecer para luz dorada filtrándose por el cristal",
        clothing: "Outfit minimalista; blanco o colores claros",
        instagram_score: 10,
        camera_tip: "Gran angular 0.5x; la simetría es clave",
        format: "Vertical 4:5",
      },
      {
        title: "Interior etéreo",
        pose: "Sentado en silencio dentro del templo, mirada al techo",
        camera_angle: "Cámara baja apuntando al techo de cristal",
        best_time: "Mediodía para máxima luz cenital",
        clothing: "Sobrio y respetuoso",
        instagram_score: 9,
        camera_tip: "Sin flash; modo Noche",
        format: "Cuadrada",
      },
    ],
    instagram_score: 10,
    difficulty: 2,
    best_time: "Atardecer",
    address: "Av. Francisco Bilbao 7400, Las Condes, Santiago",
    lat: -33.3619,
    lng: -70.5189,
    search_query: "Templo Bahá'í Santiago Chile",
    emoji: "🪷",
  },
  {
    name: "Parque Bicentenario",
    name_en: "Bicentennial Park",
    type: "free",
    category: "park",
    description:
      "Parque urbano de 27 hectáreas en Vitacura con lagos, esculturas y áreas verdes. Uno de los pulmones más elegantes de Santiago con vista a la cordillera.",
    viral_trend: "Foto junto al lago con la cordillera de los Andes reflejada",
    photo_concepts: [
      {
        title: "Reflejo de la cordillera",
        pose: "Sentado junto al lago, cordillera reflejada en el agua",
        camera_angle: "Cámara a la altura del agua, reflejo en primer plano",
        best_time: "Mañana para viento calmado y reflejos nítidos",
        clothing: "Casual elegante; colores claros",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para captar el reflejo completo",
        format: "Horizontal",
      },
      {
        title: "Esculturas del parque",
        pose: "Interactuando con una escultura del parque",
        camera_angle: "Cámara a la altura de los ojos, escultura de fondo",
        best_time: "Tarde para luz suave",
        clothing: "Outfit artístico; colores vibrantes",
        instagram_score: 7,
        format: "Cuadrada",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Parque Bicentenario, Vitacura, Santiago",
    lat: -33.4056,
    lng: -70.6056,
    search_query: "Parque Bicentenario Vitacura Santiago",
    emoji: "🌳",
  },
  {
    name: "Cerro San Cristóbal",
    name_en: "San Cristóbal Hill",
    type: "tour",
    category: "viewpoint",
    description:
      "El cerro más alto de Santiago con 880 m, coronado por una estatua de la Virgen. Se sube en funicular o teleférico y ofrece la mejor vista de la ciudad y la cordillera.",
    viral_trend: "Foto junto a la Virgen con toda Santiago y los Andes al fondo",
    photo_concepts: [
      {
        title: "Virgen con la ciudad",
        pose: "De pie junto a la estatua de la Virgen, brazos abiertos",
        camera_angle: "Cámara baja contrapicado para captar la estatua y la ciudad",
        best_time: "Atardecer para luz dorada sobre la ciudad",
        clothing: "Abrigo; la cima es fresca",
        instagram_score: 10,
        camera_tip: "Gran angular 0.5x para captar estatua + ciudad + cordillera",
        format: "Horizontal",
      },
      {
        title: "Teleférico sobre Santiago",
        pose: "Dentro del teleférico, mirando por la ventana",
        camera_angle: "Cámara a la altura de los ojos, ciudad a través del cristal",
        best_time: "Mañana para luz clara",
        clothing: "Casual; lentes de sol",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 2,
    best_time: "Atardecer",
    address: "Cerro San Cristóbal, Santiago",
    lat: -33.4256,
    lng: -70.6367,
    search_query: "Cerro San Cristóbal Santiago",
    emoji: "🚠",
  },
  {
    name: "Plaza de Armas",
    name_en: "Arms Square",
    type: "free",
    category: "landmark",
    description:
      "La plaza principal de Santiago, fundacional, rodeada por la Catedral, el Correo y el Museo Histórico. Corazón del casco histórico de la capital.",
    viral_trend: "Foto panorámica de la plaza con la Catedral Metropolitana",
    photo_concepts: [
      {
        title: "Catedral Metropolitana",
        pose: "De pie frente a la Catedral, mirada al frente",
        camera_angle: "Cámara a la altura de los ojos, simetría con la fachada",
        best_time: "Mañana para luz frontal sobre la Catedral",
        clothing: "Casual urbano",
        instagram_score: 7,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 7,
    difficulty: 1,
    best_time: "Mañana",
    address: "Plaza de Armas, Santiago Centro",
    lat: -33.4378,
    lng: -70.6506,
    search_query: "Plaza de Armas Santiago",
    emoji: "🏛️",
  },
  {
    name: "Palacio de La Moneda",
    name_en: "La Moneda Palace",
    type: "visit",
    category: "landmark",
    description:
      "Sede del gobierno chileno, palacio neoclásico del siglo XVIII. Testigo de la historia, incluyendo el bombardeo de 1973. Cambio de guardia cada dos días.",
    viral_trend: "Foto con el cambio de guardia en la Plaza de la Constitución",
    photo_concepts: [
      {
        title: "Cambio de guardia",
        pose: "De pie en la plaza, guardias marchando de fondo",
        camera_angle: "Cámara a la altura de los ojos, palacio de fondo",
        best_time: "Días de cambio de guardia (consultar agenda, 10:00)",
        clothing: "Elegante; traje o blazer",
        instagram_score: 8,
        camera_tip: "Modo ráfaga para captar el momento exacto",
        format: "Horizontal",
      },
      {
        title: "Fachada neoclásica",
        pose: "Caminando frente a la fachada del palacio",
        camera_angle: "Cámara baja a la altura de la cintura, simetría con el palacio",
        best_time: "Mañana para luz suave",
        clothing: "Elegante urbano",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Días de cambio de guardia (10:00)",
    address: "Plaza de la Constitución, Santiago Centro",
    lat: -33.4436,
    lng: -70.6539,
    search_query: "Palacio de La Moneda Santiago",
    emoji: "🛡️",
  },
  {
    name: "Sky Costanera",
    name_en: "Sky Costanera",
    type: "visit",
    category: "viewpoint",
    description:
      "Mirador en el piso 61 de la Torre Costanera Center, el rascacielos más alto de Sudamérica. Vistas de 360° de Santiago y la cordillera a 300 m de altura.",
    viral_trend: "Foto panorámica de 360° con la cordillera y toda la ciudad",
    photo_concepts: [
      {
        title: "360° de Santiago",
        pose: "Apoyado en el cristal, ciudad a los pies",
        camera_angle: "Cámara a la altura de los ojos, ciudad a través del cristal",
        best_time: "Atardecer para luz dorada y luces de la ciudad",
        clothing: "Elegante; el mirador es premium",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x; cuidado con los reflejos del cristal",
        format: "Horizontal",
      },
      {
        title: "Cordillera desde el cielo",
        pose: "De espaldas al cristal, silueta contra la cordillera",
        camera_angle: "Cámara baja contrapicado, cordillera de fondo",
        best_time: "Mañana para cordillera despejada",
        clothing: "Ropa oscura para silueta",
        instagram_score: 9,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Atardecer",
    address: "Av. Andrés Bello 2425, Providencia, Santiago",
    lat: -33.4172,
    lng: -70.6097,
    search_query: "Sky Costanera Santiago",
    emoji: "🏙️",
  },
  {
    name: "Barrio Bellavista",
    name_en: "Bellavista Neighborhood",
    type: "free",
    category: "nightlife",
    description:
      "Barrio bohemio al pie del Cerro San Cristóbal, conocido por sus murales, bares, restaurantes y vida nocturna. La Chascona, casa de Neruda, está aquí.",
    viral_trend: "Foto con los murales callejeros y el ambiente bohemio de noche",
    photo_concepts: [
      {
        title: "Murales nocturnos",
        pose: "Apoyado contra un mural, copa en mano",
        camera_angle: "Cámara frontal a la altura del pecho, mural de fondo",
        best_time: "Noche con luz de faroles sobre los murales",
        clothing: "Outfit bohemio de noche",
        instagram_score: 9,
        camera_tip: "Modo Noche; aprovechar las luces cálidas",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 1,
    best_time: "Noche",
    address: "Bellavista, Providencia, Santiago",
    lat: -33.4336,
    lng: -70.6389,
    search_query: "Barrio Bellavista Santiago",
    emoji: "🎭",
  },
  {
    name: "La Chascona (Casa de Neruda)",
    name_en: "La Chascona (Neruda's House)",
    type: "visit",
    category: "museum",
    description:
      "Una de las tres casas del poeta Pablo Neruda en Chile, en Bellavista. Llena de objetos curiosos y con un diseño caprichoso que refleja la personalidad del Nobel.",
    viral_trend: "Foto en el jardín o junto a la entrada con la placa de Neruda",
    photo_concepts: [
      {
        title: "Jardín de Neruda",
        pose: "Sentado en el jardín, rodeado de objetos curiosos",
        camera_angle: "Cámara a la altura de los ojos, casa de fondo",
        best_time: "Mañana para luz suave en el jardín",
        clothing: "Outfit artístico; colores cálidos",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Fernando Márquez de la Plata 0192, Bellavista, Santiago",
    lat: -33.4342,
    lng: -70.6386,
    search_query: "La Chascona Neruda Santiago",
    emoji: "✒️",
  },
];

export const CURATED_SPOTS_CUSCO: CuratedSpot[] = [
  {
    name: "Machu Picchu (Guardhouse Viewpoint)",
    name_en: "Machu Picchu (Guardhouse Viewpoint)",
    type: "tour",
    category: "viewpoint",
    description:
      "La vista clásica y más fotografiada de Machu Picchu, desde la caseta de guardia. La postal icónica con la ciudadela completa y el Huayna Picchu al fondo.",
    viral_trend: "Foto clásica de la postal de Machu Picchu desde la caseta de guardia",
    photo_concepts: [
      {
        title: "La postal clásica",
        pose: "Brazos abiertos con la ciudadela completa al fondo",
        camera_angle: "Cámara baja a la altura de la cintura, ciudadela y Huayna Picchu",
        best_time: "Amanecer (6:00-7:00) para niebla mística y menos gente",
        clothing: "Ropa de trekking; capa o poncho andino",
        instagram_score: 10,
        camera_tip: "Gran angular 0.5x; llegar temprano es clave",
        format: "Horizontal",
      },
      {
        title: "Salto sobre Machu Picchu",
        pose: "Saltando con la ciudadela al fondo",
        camera_angle: "Cámara baja, modo ráfaga para captar el salto",
        best_time: "Mañana para luz suave",
        clothing: "Ropa de trekking; colores vivos",
        instagram_score: 9,
        camera_tip: "Modo ráfaga; alguien ayuda con la cámara",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 4,
    best_time: "Amanecer (6:00-7:00)",
    address: "Machu Picchu, Aguas Calientes, Cusco",
    lat: -13.1631,
    lng: -72.5450,
    search_query: "Machu Picchu Guardhouse viewpoint",
    emoji: "🏔️",
  },
  {
    name: "Machu Picchu Sun Gate (Inti Punku)",
    name_en: "Machu Picchu Sun Gate (Inti Punku)",
    type: "tour",
    category: "hiking",
    description:
      "La puerta por donde entraban los caminantes del Camino Inca. Caminata de 1 hora desde la ciudadela con vistas espectaculares de Machu Picchu desde lo alto.",
    viral_trend: "Foto en la puerta del sol con Machu Picchu al fondo",
    photo_concepts: [
      {
        title: "Puerta del Sol",
        pose: "De pie en la puerta de piedra, brazos abiertos, Machu Picchu al fondo",
        camera_angle: "Cámara baja contrapicado para captar la puerta y la ciudadela",
        best_time: "Amanecer para los primeros rayos de sol (Inti Punku = Puerta del Sol)",
        clothing: "Ropa de trekking en capas; hace frío al amanecer",
        instagram_score: 10,
        camera_tip: "Gran angular 0.5x; llegar al amanecer es épico",
        format: "Horizontal",
      },
    ],
    instagram_score: 10,
    difficulty: 4,
    best_time: "Amanecer",
    address: "Inti Punku, Machu Picchu, Cusco",
    lat: -13.1589,
    lng: -72.5356,
    search_query: "Inti Punku Sun Gate Machu Picchu",
    emoji: "☀️",
  },
  {
    name: "Plaza de Armas de Cusco",
    name_en: "Cusco Main Square",
    type: "free",
    category: "landmark",
    description:
      "El corazón de la capital inca, rodeada por la Catedral y la Iglesia de la Compañía. Arco de piedra, fuentes y el ambiente de la ciudad imperial a 3.400 m.",
    viral_trend: "Foto de noche con la Catedral iluminada y la plaza animada",
    photo_concepts: [
      {
        title: "Catedral iluminada de noche",
        pose: "Sentado en las escaleras de la plaza, Catedral iluminada de fondo",
        camera_angle: "Cámara a la altura de los ojos, Catedral de fondo",
        best_time: "Noche con la Catedral iluminada",
        clothing: "Abrigo grueso; Cusco es frío de noche",
        instagram_score: 9,
        camera_tip: "Modo Noche; sin flash",
        format: "Vertical 4:5",
      },
      {
        title: "Fuentes de día",
        pose: "Caminando junto a las fuentes de la plaza",
        camera_angle: "Cámara baja a la altura de la cintura, fuentes y Catedral de fondo",
        best_time: "Tarde para luz dorada",
        clothing: "Outfit andino; poncho o chullo",
        instagram_score: 8,
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Noche",
    address: "Plaza de Armas, Cusco",
    lat: -13.5164,
    lng: -71.9789,
    search_query: "Plaza de Armas Cusco",
    emoji: "🏛️",
  },
  {
    name: "Barrio San Blas",
    name_en: "San Blas Neighborhood",
    type: "free",
    category: "landmark",
    description:
      "El barrio de los artesanos en Cusco, con calles empinadas empedradas, talleres y galerías. El punto más alto del centro histórico con vistas a la ciudad.",
    viral_trend: "Foto en las calles empinadas de San Blas con vista a Cusco",
    photo_concepts: [
      {
        title: "Calles empinadas con vista",
        pose: "Caminando cuesta arriba, mirada al frente",
        camera_angle: "Cámara baja a la altura de la cintura, perspectiva de la calle",
        best_time: "Tarde para luz dorada sobre la ciudad",
        clothing: "Outfit andino; chullo o bufanda",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para captar la calle y la vista",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Tarde",
    address: "San Blas, Cusco",
    lat: -13.5136,
    lng: -71.9739,
    search_query: "Barrio San Blas Cusco",
    emoji: "🎨",
  },
  {
    name: "Sacsayhuamán",
    name_en: "Sacsayhuamán",
    type: "visit",
    category: "landmark",
    description:
      "Fortaleza inca con piedras ciclópeas de hasta 200 toneladas encajadas con precisión milimétrica. Sitio del Inti Raymi cada 24 de junio.",
    viral_trend: "Foto junto a las enormes piedras encajadas sin argamasa",
    photo_concepts: [
      {
        title: "Piedras ciclópeas",
        pose: "Apoyado contra una piedra gigante, mano sobre la roca",
        camera_angle: "Cámara a la altura de los ojos, piedra de fondo",
        best_time: "Mañana para luz suave y menos turistas",
        clothing: "Ropa de trekking; colores tierra",
        instagram_score: 8,
        camera_tip: "Usar la escala humana para mostrar el tamaño de las piedras",
        format: "Vertical 4:5",
      },
      {
        title: "Vista de Cusco desde la fortaleza",
        pose: "Brazos abiertos con Cusco al fondo",
        camera_angle: "Cámara baja contrapicado para captar la ciudad",
        best_time: "Atardecer para luz dorada sobre Cusco",
        clothing: "Abrigo; la fortaleza es ventosa",
        instagram_score: 9,
        format: "Horizontal",
      },
    ],
    instagram_score: 9,
    difficulty: 2,
    best_time: "Mañana",
    address: "Sacsayhuamán, Cusco",
    lat: -13.5086,
    lng: -71.9706,
    search_query: "Sacsayhuamán Cusco",
    emoji: "🪨",
  },
  {
    name: "Rainbow Mountain (Vinicunca)",
    name_en: "Rainbow Mountain (Vinicunca)",
    type: "tour",
    category: "hiking",
    description:
      "Montaña a 5.200 m con franjas de colores minerales: rojo, ocre, turquesa y violeta. Una de las caminatas más espectaculares y virales del Perú.",
    viral_trend: "Foto en la cima con las franjas de colores de la montaña",
    photo_concepts: [
      {
        title: "Cima arcoíris",
        pose: "Brazos abiertos en la cima, franjas de colores al fondo",
        camera_angle: "Cámara baja contrapicado para captar las franjas y el cielo",
        best_time: "Mañana para cielo despejado (llueve por la tarde)",
        clothing: "Ropa de trekking en capas; abrigo y guantes a 5.200 m",
        instagram_score: 10,
        camera_tip: "Gran angular 0.5x; llevar oxígeno por la altura",
        format: "Horizontal",
      },
      {
        title: "Con la bandera andina",
        pose: "Sosteniendo la bandera wiphala al viento",
        camera_angle: "Cámara a la altura de los ojos, bandera y montaña de fondo",
        best_time: "Mañana",
        clothing: "Ropa de trekking; colores que complementen la montaña",
        instagram_score: 9,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 10,
    difficulty: 5,
    best_time: "Mañana",
    address: "Vinicunca, Pitumarca, Cusco",
    lat: -13.8689,
    lng: -71.3039,
    search_query: "Vinicunca Rainbow Mountain Cusco",
    emoji: "🌈",
  },
  {
    name: "Sacred Valley (Valle Sagrado)",
    name_en: "Sacred Valley",
    type: "tour",
    category: "landmark",
    description:
      "El valle sagrado de los incas entre Cusco y Machu Picchu, con pueblos como Pisac y Ollantaytambo. Terrazas, ruinas y el río Urubamba con la cordillera de fondo.",
    viral_trend: "Foto en las terrazas de Ollantaytambo con el valle y montañas",
    photo_concepts: [
      {
        title: "Terrazas incas",
        pose: "De pie en las terrazas, brazos abiertos, valle al fondo",
        camera_angle: "Cámara baja contrapicado para captar las terrazas y el valle",
        best_time: "Tarde para luz dorada sobre el valle",
        clothing: "Ropa de trekking; sombrero para el sol",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para captar terrazas + valle + cordillera",
        format: "Horizontal",
      },
      {
        title: "Río Urubamba",
        pose: "Sentado junto al río, pies en el agua",
        camera_angle: "Cámara a la altura del agua, río y cordillera de fondo",
        best_time: "Mañana para luz suave",
        clothing: "Ropa cómoda; chanclas",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 3,
    best_time: "Tarde",
    address: "Valle Sagrado, Cusco",
    lat: -13.5756,
    lng: -72.0906,
    search_query: "Valle Sagrado de los Incas Cusco",
    emoji: "🌾",
  },
  {
    name: "Qorikancha",
    name_en: "Qorikancha (Temple of the Sun)",
    type: "visit",
    category: "museum",
    description:
      "El templo inca más importante, dedicado al dios Sol, recubierto de oro en su origen. Sobre él se construyó el convento de Santo Domingo, creando un contraste único.",
    viral_trend: "Foto de los muros incas perfectos con el convento colonial encima",
    photo_concepts: [
      {
        title: "Muros incas perfectos",
        pose: "Apoyado contra el muro inca, mano sobre la piedra",
        camera_angle: "Cámara a la altura de los ojos, muro y convento de fondo",
        best_time: "Mañana para luz suave",
        clothing: "Outfit andino; colores tierra",
        instagram_score: 8,
        camera_tip: "Mostrar la precisión del encaje sin argamasa",
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 8,
    difficulty: 1,
    best_time: "Mañana",
    address: "Plazoleta Santo Domingo, Cusco",
    lat: -13.5189,
    lng: -71.9756,
    search_query: "Qorikancha Cusco",
    emoji: "☀️",
  },
  {
    name: "Ollantaytambo",
    name_en: "Ollantaytambo",
    type: "tour",
    category: "landmark",
    description:
      "Fortaleza inca y pueblo viviente en el Valle Sagrado, con terrazas gigantescas y templo inacabado. Parada clave en el camino a Machu Picchu.",
    viral_trend: "Foto en lo alto de las terrazas con el valle y el río Urubamba",
    photo_concepts: [
      {
        title: "Cima de las terrazas",
        pose: "Brazos abiertos en lo alto, valle y río Urubamba al fondo",
        camera_angle: "Cámara baja contrapicado para captar el valle",
        best_time: "Atardecer para luz dorada sobre el valle",
        clothing: "Ropa de trekking; sombrero",
        instagram_score: 9,
        camera_tip: "Gran angular 0.5x para captar terrazas + valle",
        format: "Horizontal",
      },
      {
        title: "Calle del pueblo viviente",
        pose: "Caminando por una calle empedrada del pueblo",
        camera_angle: "Cámara baja a la altura de la cintura, perspectiva de la calle",
        best_time: "Mañana para luz suave",
        clothing: "Outfit andino; chullo",
        instagram_score: 8,
        format: "Vertical 4:5",
      },
    ],
    instagram_score: 9,
    difficulty: 3,
    best_time: "Atardecer",
    address: "Ollantaytambo, Valle Sagrado, Cusco",
    lat: -13.2586,
    lng: -72.2636,
    search_query: "Ollantaytambo Valle Sagrado Cusco",
    emoji: "🏛️",
  },
];
